### ISSUE TITLE
🖼️ Fallback Avatar

### ISSUE THREAD

**Issue by alexanderadam** [gitbutlerapp/gitbutler#2512]
I guess this shouldn't look like this? :wink: 

![image](https://github.com/gitbutlerapp/issues/assets/372620/4dca3b33-9ecf-4c51-ae62-e3b849223491)

**Comment by mtsgrd** [comment]
This has been fixed [here](https://github.com/gitbutlerapp/gitbutler/commit/033b7f22b968707b40faa4cbc299f080b6789ad9).
