### ISSUE TITLE
Create rpm package for Linux

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2516]
Provide rpm distributions for Fedora / CentOS users

**Comment by JohnVillalovos** [comment]
Please add this. As a Fedora user it would be appreciated.

**Comment by buckaroogeek** [comment]
Another Fedora user with an interest in an rpm package. I am also a fedora packager with some modest experience packaging some applications (mostly go lang based). Willing to help in this area.  Thanks

**Comment by MostafaMohamed2002** [comment]
another fedora user here .

**Comment by tonislcs** [comment]
Another one :)

**Comment by krlvi** [comment]
This will be available with release `0.12.8` in a couple of days or the next nightly

**Comment by krlvi** [comment]
if anyone is curious to try the nightly with an RPM bundle, you can grab it from here - https://app.gitbutler.com/downloads

**Comment by sschuberth** [comment]
FYI @krlvi, on Fedora 40 (KDE spin) I get:

```
$ rpm -i ~/Downloads/git-butler-0.12.8-1.x86_64.rpm
error: Failed dependencies:
        libwebkit2gtk-4.0.so.37()(64bit) is needed by git-butler-0:0.12.8-1.x86_64
```

**Comment by krlvi** [comment]
hmm... gonna investigate some more, thanks for reporting

**Comment by samarth-nagar** [comment]
i see this issue isn't resolved and reopened,I am also an fedora user would appreciate if git-butler is made available on rpm

**Comment by nafg** [comment]
I installed the RPM on Fedora 40 successfully and it runs, but the window is blank and most commands don't do anything.

If I run it in the terminal I see logs like this:

```
❯ git-butler-nightly

** (git-butler-nightly:247063): WARNING **: 02:34:19.665: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
2024-07-11T06:34:19.666563Z  INFO crates/gitbutler-tauri/src/main.rs:99: starting app version=0.5.599 name=GitButler Nightly
Failed to create GBM buffer of size 1249x795: Invalid argument
2024-07-11T06:34:21.705944Z  INFO get_user: crates/gitbutler-tauri/src/users.rs:10: close time.busy=20.1µs time.idle=15.4µs
2024-07-11T06:34:21.710501Z  INFO list_projects: crates/gitbutler-tauri/src/projects.rs:41: close time.busy=13.8µs time.idle=12.9µs
```

![image](https://github.com/gitbutlerapp/gitbutler/assets/98384/a1a50ba1-a605-4c4b-a475-30592d06fc7a)

![image](https://github.com/gitbutlerapp/gitbutler/assets/98384/81e11ccc-95df-4138-9185-f156251b2891)

![image](https://github.com/gitbutlerapp/gitbutler/assets/98384/65142fa6-f593-43e6-b865-b0f471bf28fa)

**Comment by samarth-nagar** [comment]
Appreciated thanks alot

**Comment by ndom91** [comment]
@nafg the `GBM Buffer..` error message is sometimes due to your installed version `mesa`/openGL being out of date and/or mismatched with the versions of the libraries used to build the package. Is that the extent of your log output?

@samarth-nagar have you tried our `rpm` releases? See https://app.gitbutler.com/downloads

For everyone else, please double check that you've installed all the required dependencies, you can find more info [here](https://v2.tauri.app/distribute/rpm/), but in general you can view them by executing, for exxample:

```bash
rpm -qp --requires git-butler-nightly_0.5.682.rpm
```

Which will print out the system libraries it depends on. 

The most important packages are `gtk3` and `webkit2gtk`, make sure yuo've got those installed.

**Comment by ndom91** [comment]
Just wanted to come back and confirm that I was able to install the latest nightly rpm (`git-butler-nightly-0.5.682-1.x86_64.rpm`) in both:

- Fedora 39 
- Rocky Linux 9

Without issue. Fedora 39 required me installing the `webkit2gtk4.0-devel` package via `dnf`, but after that it ran without issue.

I did run into some issues with Fedora 40, however. After installing the `webkit2gtk4.0-devel` package there, I got the following error when trying to start `git-butler-nightly`:

```
/lib64/libwebkit2gtk-4.0.so.37: undefined symbol: gst_video_info_dma_drm_from_caps
```

In Fedora 39 it installed `webkit2gtk4.0-devel-2.44.3-2`, while in Fedora 40 it installed `webkit2gtk4.0-devel-2.44.1-2`.  

I have feelign this is very similar to the pinned issue on Tauri regarding Ubuntu 24.04 vs 22.04 webkit2gtk support [here](https://github.com/tauri-apps/tauri/issues/9662)

**Comment by sschuberth** [comment]
> In Fedora 39 it installed `webkit2gtk4.0-devel-2.44.3-2`, while in Fedora 40 it installed `webkit2gtk4.0-devel-2.44.1-2`.

Weird that an older version of Fedora installs a newer version of the library... anyway, if the GitButler RPM would properly declare a dependency on `webkit2gtk4.0-devel`, I guess that declaration could include the version, and fail in a more sane way if we do not get version 2.44.3 or compatible.

**Comment by ndom91** [comment]
Yeah I think the new version of Fedora / older version of webkit2gtk-4.0 is because 4.0 is actually a bit old, the newer version of Fedora (like the newewr version of Ubuntu) probably focuses on 4.1. Unfortuantely Tauri v1 doesn't support that atm.

Anyway, although the rpm / dnf output isn't great, there are a few ways to find out which dependencies a `*.rpm` has and which package provides those. For example:

![image](https://github.com/user-attachments/assets/6fd87074-8f93-4026-8f71-616de5d1e234)

![image](https://github.com/user-attachments/assets/21ab42da-efee-4ee8-991c-5f684702e3d4)

**Comment by ndom91** [comment]
Haha yeah I dont disagree, but isn't that the package managers job?

**Comment by sschuberth** [comment]
> isn't that the package managers job?

True, but the package manager can only resolve what has been declared. *If* the declared dependency is just *any* version of `webkit2gtk4.0-devel` instead of `webkit2gtk4.0-devel-2.44.3-2` then that's bug in the GitButler packaging, no?

Sorry if I'm getting something wrong here, I really have no idea how RPM packaging works, but my hunch is that this issue could be solved by adding some sort of version constraint to the dependency on `webkit2gtk4.0-devel`.

**Comment by ndom91** [comment]
> > isn't that the package managers job?
> 
> True, but the package manager can only resolve what has been declared. *If* the declared dependency is just *any* version of `webkit2gtk4.0-devel` instead of `webkit2gtk4.0-devel-2.44.3-2` then that's bug in the GitButler packaging, no?
> 
> Sorry if I'm getting something wrong here, I really have no idea how RPM packaging works, but my hunch is that this issue could be solved by adding some sort of version constraint to the dependency on `webkit2gtk4.0-devel`.

Yeah no, no worries. I think generally we're on the same page. Previously we'd just relied on the Tauri settings and bundling functionality as tauri's webview functionality is the thing which requires these dependencies and tauri is the one providing the bundling / packaging functionality. 

But it seems like there might be a gap in their support where we can make the experience a bit smoother for our users. 

To your point about the specific webkit2gtk version, good point - I'll check if I can extend the changes I linked previously to you to include a minimum version. 

Sidenote: I did some research and these `depends` options in the `tauri.conf` seem very rarely used. I did not see 1 example via github search where a project specified the webkit2gtk dependency in their `deb` or `rpm` `depends` options 🤔 I'm not sure if that means I'm missing something, or we've stumbled upon a new mechanism for ensuring a smoother install experience for folks haha

**Comment by krlvi** [comment]
@ndom91 do you think we are ready to close this issue, this time for good? ;)

**Comment by ndom91** [comment]
Haha yup, closing!

**Comment by sschuberth** [comment]
Still the same failure for me on Fedora 40, though:

```
sudo rpm -i ~/Downloads/git-butler-0.12.22-1.x86_64.rpm 
[sudo] password for sebastian: 
error: Failed dependencies:
        webkit2gtk4.0-devel is needed by git-butler-0:0.12.22-1.x86_64
        libwebkit2gtk-4.0.so.37()(64bit) is needed by git-butler-0:0.12.22-1.x86_64
```

```
sudo rpm -i ~/Downloads/git-butler-nightly-0.5.716-1.x86_64.rpm 
error: Failed dependencies:
        webkit2gtk4.0-devel is needed by git-butler-nightly-0:0.5.716-1.x86_64
        libwebkit2gtk-4.0.so.37()(64bit) is needed by git-butler-nightly-0:0.5.716-1.x86_64
```

BTW, why's the nightly version number lower than the stable version number?

**Comment by ndom91** [comment]
> Still the same failure for me on Fedora 40, though:
> 
> ```
> sudo rpm -i ~/Downloads/git-butler-0.12.22-1.x86_64.rpm 
> [sudo] password for sebastian: 
> error: Failed dependencies:
>         webkit2gtk4.0-devel is needed by git-butler-0:0.12.22-1.x86_64
>         libwebkit2gtk-4.0.so.37()(64bit) is needed by git-butler-0:0.12.22-1.x86_64
> ```
> 
> ```
> sudo rpm -i ~/Downloads/git-butler-nightly-0.5.716-1.x86_64.rpm 
> error: Failed dependencies:
>         webkit2gtk4.0-devel is needed by git-butler-nightly-0:0.5.716-1.x86_64
>         libwebkit2gtk-4.0.so.37()(64bit) is needed by git-butler-nightly-0:0.5.716-1.x86_64
> ```
> 
> BTW, why's the nightly version number lower than the stable version number?

You need to install webkit2gtk4.0-devel, for example: 

``` 
sudo dnf install webkit2gtk4.0-devel 
``` 

Then it should work. 

Also the two version numbers can be thought of as two totally seperate counts, they're not related at all

**Comment by ndom91** [comment]
Great thanks for the tip of `dnf` over `rpm`. I'm not super familiar with rhel-related distros

**Comment by guoci** [comment]
@nafg you can try setting a environment variable to resolve the blank window issue.
`WEBKIT_DISABLE_DMABUF_RENDERER=1 gitbutler-tauri`
The above worked for me.
Source:
https://www.reddit.com/r/tauri/comments/16tzsi8/tauri_desktop_app_not_rendering_but_web_does/

**Comment by Caleb-T-Owens** [comment]
I'm not familiar with webkit settings, but I'm wondering if this is a common issue for a reasonably large group of users and if it doesn't have any gross negative effects that ought to be some default environment variable that the app starts with (if that is possible).

**Comment by Byron** [comment]
This would be possible if it would start through a shim of sorts, a shell that prepares the launch of the actual binary. It's quite a common practice as well.

**Comment by ndom91** [comment]
The webkit flags are also in our docs debugging page now 😅 

I think it's an issue with incompatibility between webkit and certain installed versions of opengl and/or wayland. Haven't had time to get to the bottom of it, but it isn't common enough that I would say we should wrap the binaries in a script or something like that
