### ISSUE TITLE
Error message displayed in Gitbutler due to syntax error in `projects.json`

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2518]
Hey. It just happened again that my `projects.json` had an syntax error. Closed yesterday night my laptop with Gitbutler running. Today I opened the laptop and found that Gitbutler app displayed an error message. (forgot to take a screen). Checked the `projects.json` and at the end it had something like: 
```
...
    "project_data_last_fetch": {
      "error": {
        "timestamp": {
          "secs_since_epoch": 1706828585,
          "nanos_since_epoch": 216435000
        },
        "error": "failed to fetch"
      }
    }
  }
]iled to fetch"
      }
    }
  }
```

via: @palmartin

https://discord.com/channels/1060193121130000425/1073202153163857920/1202882531196665936

**Comment by krlvi** [comment]
This has been fixed since a number of releases back. I'm closing this
