### ISSUE TITLE
User action concurrency

### ISSUE THREAD

**Issue by roderik** [gitbutlerapp/gitbutler#2522]
wrt https://discord.com/channels/1060193121130000425/1073202153163857920/1203605030637412432

When i'm doing actions in the UI, everything happens sequentially, even tasks that should be independent of each other.

- Clicking create pull request -> spinner, click new branch because i want to keep working on the next thing, nothing happens until the PR is created (which is also kind of slow btw) 
- Same thing happens when dragging 1 file, and then dragging another

The experience is best described as 'doing one thing at the same time with some sort of single process queue of actions'.

**Comment by roderik** [comment]
https://github.com/gitbutlerapp/gitbutler/assets/16780/5f0792ff-14c0-4d2c-9be6-31b6b733c190

Made a video of the effect i'm describing

**Comment by Caleb-T-Owens** [comment]
@roderik, We've been working on improving the locking and concurrency of the application, in regards to calls to the rust end. Could you let us know if this still presents an issue to you.

Many thanks!

**Comment by roderik** [comment]
This was a super old preview version, fine with me to close it, it has not bothered me recently

**Comment by krlvi** [comment]
thank you so much for helping make GB better
