### ISSUE TITLE
Can't open submodule

### ISSUE THREAD

**Issue by mkroening** [gitbutlerapp/gitbutler#2541]
On macOS, I cannot open my repository that is a submodule (https://github.com/hermit-os/kernel inside https://github.com/hermit-os/hermit-rs).

For reproduction:

```
git clone --recursive git@github.com:hermit-os/hermit-rs.git
```

Then try to open `hermit-rs/kernel` in GitButler.

```
[...]
2024-02-05T13:07:48.611165Z ERROR add_project: gitbutler-app/src/projects/commands.rs:75: failed to add project error=failed to open repository

Caused by:
    path not found: /Users/mkroening/Downloads/hermit-rs/kernel/.git/objects path="/Users/mkroening/Downloads/hermit-rs/kernel"
[...]
```

The user interface only has a small toast notification, “Something went wrong.”

**Comment by schacon** [comment]
Good point. We haven't done any testing with submodules yet. It's on the list.
