### ISSUE TITLE
Taskbar icon not visible in i3 desktop

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2568]
i noticed the task bar icon (aka tray icon) in my i3 desktop is not visible at the bottom right. i confirmed can interact with it but its invisible

via: yassin0785

https://discord.com/channels/1060193121130000425/1060193121666863156/1204801724582465587

**Comment by krlvi** [comment]
resolved in https://github.com/gitbutlerapp/gitbutler/pull/2785
