### ISSUE TITLE
Performance issues when a repository has many, _many_ branches

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2578]
Discord discussion https://discord.com/channels/1060193121130000425/1073202153163857920/1205090107900559391

**Comment by clemens-tolboom** [comment]
It would be nice to add some (summary) text (how many branches, how long) instead of only a link I guess (search engine, non-discord user)

I see a spinner for a long time (45 seconds) on project with 41 branches and 58 changes ... when **reload** takes similar time.

**Comment by krlvi** [comment]
> It would be nice to add some (summary) text (how many branches, how long) instead of only a link I guess (search engine, non-discord user)
> 
> I see a spinner for a long time (45 seconds) on project with 41 branches and 58 changes ... when /right-click/pressing **reload** takes similar time.
> 
> * MacOS Version 17.2.1 / M2

You are right, we should make the app provide better feedback when it's doing something. Regarding this specific issue there was a bunch of progress in the latest release - https://github.com/gitbutlerapp/gitbutler/releases/tag/release%2F0.12.19

Closing for now
