### ISSUE TITLE
Profile picture doesn't get updated at all places

### ISSUE THREAD

**Issue by TilakMaddy** [gitbutlerapp/gitbutler#2589]
New profile picture doesn't reflect next to the commit messages in virtual branches

**Comment by schacon** [comment]
Hm, good point. 

So, we're pulling the commit images from Gravatar. Perhaps if we see your email address, we can use the uploaded GB one instead. You could only do it for yours through. I wonder if GitHub has a way to get an avatar from an email address...

**Comment by TilakMaddy** [comment]
Yeah, I also think that GB uploaded image should be the one preferred not Gravatar. Feel free to close this issue as and when you find it convenient!

**Comment by Caleb-T-Owens** [comment]
Action: Any time we see your email, instead of converting it to a gravatar URL, use the gitbutler profile picture.
