### ISSUE TITLE
Floating Git Butler icon

### ISSUE THREAD

**Issue by Moulick** [gitbutlerapp/gitbutler#2596]
There is a random floating icon of GitButler on the top-left of the screen covering the Apple logo and hence the menu

<img width="448" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/15780903/0efa4577-b54e-4baf-872e-e5213555904e">

**Comment by schacon** [comment]
It's so weird. I get it sometimes floating strangely on the other side of the notch on my laptop. I assume this is a Tauri thing, I'm not sure how we would have something special that messes up this menu placement, but we'll take a look.

**Comment by Moulick** [comment]
btw, there are two, one correct and one white

<img width="731" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/15780903/5376695a-338a-4827-a110-3d5ea9100e53">

**Comment by redomar** [comment]
It also doesn't work well with too many menu options, and it flickers when I move from screen to screen.
 <img width="1512" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/2476381/0750b5bd-707b-4cf9-9c1e-de46d7a95218">

**Comment by krlvi** [comment]
fixed this by removing the tray icon altogether 😅 https://github.com/gitbutlerapp/gitbutler/pull/2785

**Comment by schacon** [comment]
test

**Comment by schacon** [comment]
test from github
