### ISSUE TITLE
Duplicated files visible on drag and drop

### ISSUE THREAD

**Issue by BloodStainedCrow** [gitbutlerapp/gitbutler#2612]
I seem to have a ghost version of a couple files attached to my drag and drop:

![image](https://github.com/gitbutlerapp/gitbutler/assets/23032812/721c8a4e-e012-49d0-b82e-dd6bd0e90039)

![image](https://github.com/gitbutlerapp/gitbutler/assets/23032812/a9db9bd6-9ac7-4a7d-b4bd-b095dd33fa99)

![image](https://github.com/gitbutlerapp/gitbutler/assets/23032812/3f8fb527-ba7a-4080-9831-0f58888534aa)

**Comment by BloodStainedCrow** [comment]
This happens when I drag around any file, you cannot see my cursor in the screenshots, but I am holding the files

**Comment by BloodStainedCrow** [comment]
I also cannot move these files, now that they are quantum entangled.

**Comment by mtsgrd** [comment]
I just looked into this and discovered a bug. Any chance you have these other files selected in a different branch? I can probably submit a fix later today.

**Comment by mtsgrd** [comment]
@BloodStainedCrow are you still seeing this bug?

**Comment by LeoCaprile** [comment]
I think this may happen when you drag by the item icon, don't know wich OS @BloodStainedCrow is using but in macOS looks like this:


https://github.com/gitbutlerapp/gitbutler/assets/71847541/f4dc0475-093f-463c-9a27-40c3fd5cbec4

Maybe this is related to another bug, but that some weird behavior.

**Comment by LeoCaprile** [comment]
Okay, got it.
After doing the above, I get the same behaviour as @BloodStainedCrow

<img width="1728" alt="Captura de pantalla 2024-03-07 a la(s) 21 55 33" src="https://github.com/gitbutlerapp/gitbutler/assets/71847541/eb5f70f4-d76d-40bb-ab7c-4073d04b9d80">

gonna make a PR fixing this.

**Comment by LeoCaprile** [comment]
PR on #3076 solve this bug

**Comment by PavelLaptev** [comment]
Looks like this has been fixed. Let's reopen the issue if you still encounter this issue.
