### ISSUE TITLE
emoji fail to render

### ISSUE THREAD

**Issue by hayesall** [gitbutlerapp/gitbutler#2622]
Basically: my commits look like this:

```
8cdb046 (origin/main, main) ✏️ Fix typo: `D` -> `B`
62c7da0 ✨ Update spring schedule images
2b0c7a9 🔒 Upgrade `vite`
```

... but GitButler renders this:

![screenshot of GitButler 0.10.6, showing either a pencil icon or white boxes instead of emoji in the commit messages](https://github.com/gitbutlerapp/gitbutler/assets/11916674/e8c3898c-043b-41fa-b6b9-f0508a63b6a3)

It looks like this is a limitation of the `Spline Sans Mono` typeface:

https://github.com/gitbutlerapp/gitbutler/blob/a1cea76380e3ee98f1c41d01730d8c49a86b2900/gitbutler-ui/src/styles/fonts.css#L18

... which doesn't appear to handle some emoji: https://fonts.google.com/specimen/Spline+Sans+Mono?preview.text=%E2%9C%A8

---

<details>
<summary>metadata and version info</summary>

- GitButler: 0.10.6
- OS: Windows/WSL Ubuntu

</details>

**Comment by PavelLaptev** [comment]
@hayesall thank you for the report!
We're using `Spline Sans Mono` only to render some code lines, for the rest we use `Inter`. 
This is odd because the browser should try to pick up a font that can display emojies 🤔

Are you still facing the problem?

<img width="604" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/77bf63b5-d155-4829-b800-34d361201e20">

**Comment by Qix-** [comment]
Going to close as I cannot reproduce and we haven't heard back. Latest HEAD:

<img width="278" alt="grafik" src="https://github.com/gitbutlerapp/gitbutler/assets/885648/f615c00f-da9f-478d-9bff-8fdb3a99e187">

Let us know if this is still an issue!

**Comment by jeyj0** [comment]
I'm also facing an issue with emoji on version 0.15.1
![Image](https://github.com/user-attachments/assets/8dcb6e1a-63c1-4cb3-bc69-362c1e447342)

**Comment by PavelLaptev** [comment]
@jeyj0 thanks for reporting! Which emoji is it, and are you on macOS?

**Comment by jeyj0** [comment]
So far, I haven't seen any emoji render in GitButler. These are the ones I can test easily (none work): ✨⬇️📥🔬⚙️🔎🧪🚀🏷️🪝

They work neither in the file preview, nor in the commit editor, or the commit message. Basically, I haven't found a place where they _do_ work. They always render as in the screenshot from my previous comment.

Admittedly, my setup is probably quite unusual; I'm running the .deb GitButler on Ubuntu 24.04.2 LTS in a distrobox within Bluefin DX.

I actually fixed it now (to test my guess at the cause) by installing an emoji font within the distrobox. So it's easy to fix (just install an emoji font), but there will likely be more developers who'll have a setup like that, so you might want to consider including an emoji font yourself.

**Comment by PavelLaptev** [comment]
@jeyj0 thank you, I'll investigate this
