### ISSUE TITLE
Support Github Enterprise (GHE)

### ISSUE THREAD

**Issue by cmeans** [gitbutlerapp/gitbutler#2623]
To facilitate corporate adoption, please add Github Enterprise support.

**Comment by schacon** [comment]
We would love to do this. It's probably not difficult, as the APIs should remain the same. I think it's more a case of changing the base URL we use to be configurable rather than `github.com`. Perhaps a first step would be to read this from the upcoming config file changes.

**Comment by kunwarsahni01** [comment]
And updates on this?

**Comment by mtsgrd** [comment]
I'd like to help out if anyone can help me understand what's needed? I had a brief look, it seems we'll need to customise the api hostname both for the oauth initialization in the rust code, as well as for octokit.js in the typescript code.

**Comment by kunwarsahni01** [comment]
I don't know if it matters but maybe api versioning with different server versions? Probably not, I would assume it would just be making the hostname configurable.

**Comment by mtsgrd** [comment]
@kunwarsahni01 we use the oauth device flow, and I'm thinking that won't for an enterprise setup?

That call happens here:
https://github.com/gitbutlerapp/gitbutler/blob/c1cf5ebc5915307f069a2e1921d56d7b71237aee/crates/gitbutler-tauri/src/github.rs#L47-L48

The octokit.js base url we need to be able to modify lives here currently: https://github.com/gitbutlerapp/gitbutler/blob/c1cf5ebc5915307f069a2e1921d56d7b71237aee/apps/desktop/src/lib/forge/github/octokit.ts#L5-L21

**Comment by Kristijan** [comment]
I'm happy to assist with any testing you require as part of this.

**Comment by Byron** [comment]
As an update, by now we'd have to adjust the GitHub client to support a different base URL.

https://github.com/gitbutlerapp/gitbutler/blob/9b57282b462ad9272352b704313505208fef6963/apps/desktop/src/lib/forge/github/githubClient.ts#L59-L77

With that, it could hit the endpoint of enterprise instances and PRs can be created there as well, assuming folks authenticate with the "replace keychain entry with PAT" workaround.

Thus, it would use `https://<ghe-domain>/api` instead of `https://api.github.com`.

**Comment by krlvi** [comment]
Thank you to everybody who patiently waited for this feature. I am happy to share that it is now possible to configure an API integration with GitHub Enterprise. You can also now have multiple accounts and choose between them on per-project basis.

<img width="1352" height="823" alt="Image" src="https://github.com/user-attachments/assets/e9be6776-5bc9-4fe6-be23-b801815eb4b1" />

Please try it out and share your feedback or any issues that you encounter in whichever channel is most convenient :) 

Thanks @estib-vega for making this happen. <3

cc @aspleenic
