### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [gitbutlerapp/gitbutler#2627]
Hi,
Does the license switch to MIT 2 years after the release of GitButler or 2 years after each individual update (ie updates 2 years old are MIT)?
Thanks!

**Comment by namanlp** [comment]
Hi @fakerybakery 

From Discord Channel:

> ...it's rolling window from each commit
> ...2 years after any commit, that code becomes MIT

Hence, it becomes MIT for each individual update after 2 years.

Thank You

**Comment by fakerybakery** [comment]
Thx!

**Comment by fakerybakery** [comment]
Hi @namanlp, one question - what are GitButler's current services where usage might be classified as competing? If I don't offer GB as a SaaS is it OK to use it for commercial projects?
Thanks!

**Comment by namanlp** [comment]
Hi @fakerybakery , I have no idea on that. It is best to ask @schacon about that. Or maybe ping him on discord channel.
