### ISSUE TITLE
Show zoom options in "View" menu

### ISSUE THREAD

**Issue by mtsgrd** [gitbutlerapp/gitbutler#2637]
It's a reasonable expectation for most users. Relevant discord message by André [here](https://discord.com/channels/1060193121130000425/1073202153163857920/1207064029965713438).

![image](https://github.com/gitbutlerapp/gitbutler/assets/1300356/258283ff-1313-45da-8328-81499d2abf15)

**Comment by Antony-jeban** [comment]
Hi @mtsgrd, I have noticed that the zoom option is already getting displayed under the view menu for the version 0.12.25

SS for reference.
<img width="707" alt="Screenshot 2024-09-14 at 11 37 09 PM" src="https://github.com/user-attachments/assets/a0640c8a-9757-4ad8-9189-b24158c2a45f">

Only difference I am noticing in these two screenshots attached SS is having <kbd>⌘ =</kbd> where as your screenchot is having <kbd>⌘ +</kbd>. Should I need to work on updating that to say <kbd>⌘ +</kbd>?

**Comment by krlvi** [comment]
This is now implemented so Im closing this issue. Technically, the short key is indeed `Cmd =` since `+` would require holding shift and I think this is the intended approach.
