### ISSUE TITLE
allow to use the git cli command in background (git frontend mode)

### ISSUE THREAD

**Issue by c33s** [gitbutlerapp/gitbutler#2639]
as i am in a very strict work environment i would love to use gitbutler as frontend for git. just use the features like virtual branches local and then commit and push to the remote calling the git cli command.  a setting where i can switch between gitbutler doing all the git operations by itself and using git would be awesome. i really love what i have seen in the video and would be happy to use such a nice tool but enterprise environments can be very strict.

also this would fix some other issues like auth problems, lfs support, submodules, githooks, ...

**Comment by jokeyrhyme** [comment]
![Uploading image.png…]()

This is in version 0.10.28 , but it was probably introduced earlier

Seems to work for me (I need it to use the real `git` so that my USB security key works)

**Comment by c33s** [comment]
i haven't checked the new feature yet. hope i will find this or next week for it
