### ISSUE TITLE
stuck on "lets go" after adding a project if there is no network access (firewall)

### ISSUE THREAD

**Issue by c33s** [gitbutlerapp/gitbutler#2640]
in the firewall logs i see repeated accesses to gravatar. i would vote for allowing gitbutler to work without network access

![image](https://github.com/gitbutlerapp/gitbutler/assets/649209/6fae332a-d11d-4602-b670-7ee49263c78b)

**Comment by omitter** [comment]
I have blocked all gravatar connections on my pc. With this this setting, Gitbutler loads forever with
```
ERROR get_base_branch_data: gitbutler-app/src/assets.rs:121: failed to proxy gravatar url gravatar_url=https://www.gravatar.com/avatar/xxx?s=100&r=g&d=retro error=error sending request for url (https://www.gravatar.com/avatar/xxx?s=100&r=g&d=retro): error trying to connect: tcp connect error: connection timeout (os error 110)
```

It would be really nice if Gitbutler wouldn't have such hard dependencies on a rather unimportant feature. Also for privacy reasons, it's grossly negligent to send all private email addresses to an external service without even asking.

**Comment by pinguo-lixin** [comment]
> I have blocked all gravatar connections on my pc. With this this setting, Gitbutler loads forever with
> 
> ```
> ERROR get_base_branch_data: gitbutler-app/src/assets.rs:121: failed to proxy gravatar url gravatar_url=https://www.gravatar.com/avatar/xxx?s=100&r=g&d=retro error=error sending request for url (https://www.gravatar.com/avatar/xxx?s=100&r=g&d=retro): error trying to connect: tcp connect error: connection timeout (os error 110)
> ```
> 
> It would be really nice if Gitbutler wouldn't have such hard dependencies on a rather unimportant feature. Also for privacy reasons, it's grossly negligent to send all private email addresses to an external service without even asking.

Same here. Especially as a developer in China!

> 2024-03-07T02:44:32.820964Z ERROR get_base_branch_data: gitbutler-app/src/assets.rs:121: failed to proxy gravatar url gravatar_url=https://www.gravatar.com/avatar/94d221f4c77115aef643d3bdb2697639?s=100&r=g&d=retro error=error sending request for url (https://www.gravatar.com/avatar/94d221f4c77115aef643d3bdb2697639?s=100&r=g&d=retro): error trying to connect: tcp connect error: Operation timed out (os error 60)
> 
> Caused by:
>     0: error trying to connect: tcp connect error: Operation timed out (os error 60)
>     1: tcp connect error: Operation timed out (os error 60)
>     2: Operation timed out (os error 60) project_id="7bbac76b-10e6-4412-97ff-9b58245bc4e0"
> 2024-03-07T02:45:48.423685Z ERROR get_base_branch_data: gitbutler-app/src/assets.rs:121: failed to proxy gravatar url gravatar_url=https://www.gravatar.com/avatar/94d221f4c77115aef643d3bdb2697639?s=100&r=g&d=retro error=error sending request for url (https://www.gravatar.com/avatar/94d221f4c77115aef643d3bdb2697639?s=100&r=g&d=retro): error trying to connect: tcp connect error: Operation timed out (os error 60)
> 
> Caused by:
>     0: error trying to connect: tcp connect error: Operation timed out (os error 60)
>     1: tcp connect error: Operation timed out (os error 60)
>     2: Operation timed out (os error 60) project_id="7bbac76b-10e6-4412-97ff-9b58245bc4e0"

**Comment by Caleb-T-Owens** [comment]
Hi! Just tested this and it seems to be resolved.

Feel free to open a new issue if you're still having trouble with it 👍
