### ISSUE TITLE
Disable spellcheck in branch filter UI

### ISSUE THREAD

**Issue by osyrisrblx** [gitbutlerapp/gitbutler#2641]
Step 1: type "custom" in filter UI
<img width="218" alt="Screenshot 2024-02-13 at 4 09 48 PM" src="https://github.com/gitbutlerapp/gitbutler/assets/9200592/aa988389-2266-4b77-8284-01fedfa0b12a">

Step 2: attempt to click on the branch
<img width="315" alt="Screenshot 2024-02-13 at 4 11 25 PM" src="https://github.com/gitbutlerapp/gitbutler/assets/9200592/4cd9268b-ae95-4883-b60f-358fef2cd1de">

Spellcheck automatically switches it to "Custom", but branch filtering is case sensitive!

I can workaround this by hitting that little "x".. but this seems clunky.

**Comment by krlvi** [comment]
Closing this issue as fixed since version `0.10.10`. Feel free to open a new issue if you spot this re-occuring somewhere else
