### ISSUE TITLE
package without any AI plugin/code

### ISSUE THREAD

**Issue by c33s** [gitbutlerapp/gitbutler#2642]
provide a version without any AI "modules" packaged. enterprise environments can be very strict. phpstorm has currently the problem that the ai plugin cannot be completely removed which blocks the whole ide form being used in some enterprise environments. see the discussion there for more insight: https://youtrack.jetbrains.com/issue/LLM-1760/Can-not-remove-Jetbrains-AI-Assistant-plugin-completely

**Comment by krlvi** [comment]
Hey @c33s,
Since February the app has changed in the following ways relevant to this issue:
- You can configure GitButler to use a local LLM via (Ollama)
- All LLM features the app has have to be explicitly enabled on per-project basis and are always triggered by an explicit action.

Let me know if these changes fulfill your specific requirements

**Comment by krlvi** [comment]
Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.

**Comment by c33s** [comment]
@krlvi please reopen. as stated in the remote issue https://youtrack.jetbrains.com/issue/LLM-1760/Can-not-remove-Jetbrains-AI-Assistant-plugin-completely the ai part has to be optional (extra download). enterprise rules are quite strict. no ai code has to be in the program. so your ai part must be a plugin which is not bundled per default.

**Comment by Byron** [comment]
Thanks for letting us know, @c33s.
Previously it might not have been clear that the AI-related code would have to be shipped in a plugin to be entirely unavailable unless it's loaded.
Should this issue be re-opened for us to keep that in mind or re-closed as `not planned`?
