### ISSUE TITLE
Add "Discard local changes..." to contextual menu in Changes pane.

### ISSUE THREAD

**Issue by AndreAngelantoni** [gitbutlerapp/gitbutler#2644]
Feature request:
1. Click on file that has been changed.
2. Select "Discard local changes..." from the contextual menu.
3. Agree to confirmation dialog box.
4. Revert file to unmodified version.

Wording ("Discard local changes...") comes from Git Tower.

**Comment by nbrugger-tgm** [comment]
This would be very useful. Especially when you run into a situation with an illegal state (like a change being on 2 branches after moving it)

**Comment by Byron** [comment]
As of Version 0.11.3 (20240419.070253), there now a way to do that.

<img width="300" alt="Screenshot 2024-04-21 at 16 47 12" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/e9d274f3-2e0b-4454-b60c-dd1855c0e9b8">

Does that resolve this issue?

**Comment by nbrugger-tgm** [comment]
Yes, this is what I wanted (alto bulk would be nice)<

But imo this can be closed

**Comment by krlvi** [comment]
thanks for the feedback! closing now
