### ISSUE TITLE
Support updating vbranches when the respective remote has new commits

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2649]
from discord https://discord.com/channels/1060193121130000425/1060193121666863156/1207105951044214864

**Comment by davestimpert** [comment]
This seems to make it impractical to use GitButler if your team often collaborates on branches (unless I'm missing something. 
I'd love to see a solution to this!

**Comment by Caleb-T-Owens** [comment]
We now have the ability to "integrate upstream" changes. Feel free to open another issue if this doesn't resolve your problem 👍 .
