### ISSUE TITLE
feature request : Cloud Login link from app should support copy/paste

### ISSUE THREAD

**Issue by bkcsfi** [gitbutlerapp/gitbutler#2650]
After launching the application, when I click on Account and then "Sign Up or Log In", it would be very helpful if I could copy the link that's mentioned in the text "click here".

*If you were not redirected automatically, you can  click here*

I need to be able to copy the link so that I can paste it into a browser that is already running and authenticated to "work".

Unfortunately when I click it, Firefox launches with the profile selector. I am unable to choose the work profile because its already running and in-use.

Instead I have to choose a throw-away profile, let the browser start, copy the URL (hoping it doesn't redirect quickly), then paste the url into my "work browser" instance.

Its a pain..

**Comment by ndom91** [comment]
> @ndom91 @PavelLaptev  Perhaps we could have a special external link button which always can be right clicked to copy the URL? 
> 
> I've marked this as "good first issue" as a much simpler fix is to just add in a context menu.

Hmm yeah so for buttons I don't mind that. 

For links, i.e. anchor tags, what do you all think of having one of those "copy to clipboard" btns appear on hover?

**Comment by PavelLaptev** [comment]
Yes, I think I can add that

**Comment by PavelLaptev** [comment]
The PR is merged. Should be in the next release :-)

![image](https://github.com/user-attachments/assets/d4372965-82cb-48ea-957f-742b21c95b9c)

**Comment by bkcsfi** [comment]
great, thanks for looking into this!
