### ISSUE TITLE
Question: What is the difference between gitbutler and git worktree

### ISSUE THREAD

**Issue by William9923** [gitbutlerapp/gitbutler#2653]
Noob question here, but was wondering what is the difference between gitbutler and git worktree, and any pros on using gitbutler instead of worktree workflow ?

**Comment by xeor** [comment]
I was wondering the same, but it is clearer if you try out gitbutler. Curious why git worktree is not even mentioned tho, or even used as a backend for gitbutler

**Comment by JonneDatanen** [comment]
Somehow I think that `git worktree` would have been obvious backend choice which would have make the CLI-use also more clear. Now the created local branches are somewhat confusing

**Comment by schacon** [comment]
I wrote this up in some detail here: https://blog.gitbutler.com/git-worktrees/

Thanks!
