### ISSUE TITLE
UI: Gitbutler icon not dark mode safe

### ISSUE THREAD

**Issue by melroy89** [gitbutlerapp/gitbutler#2654]
I'm using 100% dark mode here and it seems that your app icon is not compatible with the dark ;). This is what I see in my status bar (XFCE):

![image](https://github.com/gitbutlerapp/gitbutler/assets/628926/cea20cc6-2801-42df-b0b6-03c5a67e63ba)

**Comment by krlvi** [comment]
Closing this since there is no more tray icon :)
