### ISSUE TITLE
Links in Account Section don't work

### ISSUE THREAD

**Issue by srihari9n** [gitbutlerapp/gitbutler#2656]
- Clicking on links and buttons do not do anything, I expected it to open something in browser. (Added recording)

https://github.com/gitbutlerapp/gitbutler/assets/101564310/f25d373b-0198-416c-8f7e-413e6baab5b6

**Comment by jniewt** [comment]
Same problem with AppImage on Fedora 39, v0.10.13

Can't log into cloud account (probably) because of this.

**Comment by itay-grudev** [comment]
For example, clicking on the `Log In or Sign Up` button produces the following logs:

![broken link](https://github.com/gitbutlerapp/gitbutler/assets/2123767/04a1a617-a324-4614-a448-facb88dd2db2)

```txt
024-03-17T13:03:08.570762Z  INFO delete_user: gitbutler-app/src/users/commands.rs:70: close time.busy=7.26µs time.idle=19.0µs
/usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so: undefined symbol: g_uri_is_valid
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so: undefined symbol: g_uri_is_valid
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
[2024-03-17][13:03:10][ERROR][webview] Unhandled exception: undefined undefined

** (git-butler:56102): WARNING **: 15:03:28.920: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by Caleb-T-Owens** [comment]
Hi! I just wanted to check in and ask if this was still an issue?

Thanks!

**Comment by krlvi** [comment]
Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.
