### ISSUE TITLE
Add global settings for commits generation

### ISSUE THREAD

**Issue by ojpro** [gitbutlerapp/gitbutler#2662]
Hey, it would be helpful if there are global settings instead of modifying per-project.
- commit structure
- commit emoji and extra concise
![image](https://github.com/gitbutlerapp/gitbutler/assets/108437129/244d0c35-baf2-41ab-bbb2-766d15a298ce)

**Comment by Caleb-T-Owens** [comment]
Thanks for writing in!

Long term we are keen to implement tiered settings so you can have a global default and then project specific changes. However, this is a current focus, and we'd prefer to avoid introducing lots of temporary specific global setting.
