### ISSUE TITLE
App stuck when opening large files like pnpm-lock.yml

### ISSUE THREAD

**Issue by ojpro** [gitbutlerapp/gitbutler#2664]
[Screencast from 02-14-2024 11:04:18 AM.webm](https://github.com/gitbutlerapp/gitbutler/assets/108437129/88c26b29-8ab2-4747-adf7-709a521c8285)

**Comment by nbrugger-tgm** [comment]
For me this caused a crash. The WebKitWebProcess process ate all the remaining memory until my system was exhausted and all apps crashed

**Comment by Timeraa** [comment]
Same issue here, it get's unusably slow, perhaps it should only render till the edge of the window and not all at once

**Comment by krlvi** [comment]
fixed in release 0.10.17

**Comment by krlvi** [comment]
Actually, before closing this, @ojpro, would you be able to test a recent version of the app? I mitigated this by not automatically rendering these files on click. 
There are some optimizations that we can do in the actual rendering, but I would like to track it in a separate ticket

**Comment by Timeraa** [comment]
<img width="488" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/29104008/27d8a17c-8f31-4346-baff-2b14e2ceacdd">
<img width="493" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/29104008/c420c1f3-daf9-4fa3-be60-45e9f34d87a3">

Seems to be fixed (First image is full file change, second is just small part)

**Comment by krlvi** [comment]
Good to know, in this case I am closing this issue. Feel free to open a new issue if you hit another performance issue
