### ISSUE TITLE
Support repositories with submodules in them

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2665]

**Comment by ericwern** [comment]
Any status on when this will be added? Love GitButler but using submodules in all my projects

**Comment by PierreLeGuen** [comment]
Same, not working

**Comment by pharapeti** [comment]
Any idea why GitButler is currently unable to support submodules?

**Comment by Geekdude** [comment]
See #2891. This issue disallowed opening repos with submodules due to a bug that would mess up the submodule.

This issue also seems to be a duplicate of #2541. Which mentions that submodule support is on the list.

**Comment by eightycc** [comment]
Same issue here. All of my personal projects plus the public projects I contribute to contain submodules.

**Comment by himchawla** [comment]
Waiting for this feature, submodules are heavily utilized in my repos.

**Comment by koppor** [comment]
In all cases, GitButler should not rejecting a repository if it has submodules. It should just ignore submodules and work if there were no submodules.

I don't care about changes in the sub modules, I just want to work on the main repository using git butler!

**Comment by tkuhlengel** [comment]
Even as an initial pass, it would be helpful if users could scope to a submodule and only make commits within that one submodule.  

In my use case, deleting files from a submodule would be problematic, so the outright rejection is much better than the alternative of damaging the repository or database. Much appreciated.

**Comment by limonkufu** [comment]
There at least should be an option to override this behaviour, accepting any risk it might have so that we can just work with the submodule. It might be a screen we need to accept, a config we need to  change somewhere. Is there an option like this?

**Comment by markjaquith** [comment]
@limonkufu

> There at least should be an option to override this behaviour, accepting any risk it might have so that we can just work with the submodule. It might be a screen we need to accept, a config we need to change somewhere. Is there an option like this?

Sort of. GitButler only appears to check for submodules when adding a repo, and it does so by checking for a `.gitmodules` files in the root of the repo.

Thus, if you `rm .gitmodules` and then add the repo, it will let you. And then you can just restore that file with `git checkout .gitmodules` (and GitButler will be none the wiser).

> [!warning]
> **You are on your own here.** I have no idea how GitButler messes up submodules. My assumption is that you should avoid touching submodules and submodule code *entirely* when using GitButler, but even that might be unsafe. Test how it works in a test repo. Don't yell at me if this goes wrong.

**Comment by ericclemmons** [comment]
For everyone else who finds this from Google, you may not realize this is an issue because the error is hidden when clicking:
![Screenshot 2024-04-25 at 12 16 31 PM](https://github.com/gitbutlerapp/gitbutler/assets/15182/2e484571-53ab-471f-89ce-0bda3d68b096)
![Screenshot 2024-04-25 at 12 16 38 PM](https://github.com/gitbutlerapp/gitbutler/assets/15182/7c35c96a-51f0-4ef9-bb0c-0392e3bf8b50)

**Comment by Byron** [comment]
Thanks for sharing! Please note that this is a regression in the latest stable release (Version 0.11.4 (20240423.110032), and it's fixed in [nightly](https://app.gitbutler.com/downloads).

**Comment by limonkufu** [comment]
I tried everything but it still gives me the same error.

I tried everything described here: https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule 

- `rm .gitmodules`
-  `git submodule deinit`
-  `git rm <submodule>`
-  `rm <submodule>`
-  `rm .git/module`

Could you advise how I can make it work by deleting an existing submodule? I didn't commit any of the changes though

**Comment by Byron** [comment]
Can you share the errors you see? When adding a project, it essentially only looks at `.gitmodules` and if present, rejects the repository. In a way, it would be unexpected if it would still think submodules are present without `.gitmodules`.

**Comment by limonkufu** [comment]
yeah sure.

I don't have any `.gitmodules` in the repo.

```
ls -all .gitmodules
ls: cannot access '.gitmodules': No such file or directory
```

Then, I try opening the repository with Gitbutler by using "Add new project" button. I get the following in console:

```
[Error] ipc->add_project: {"path":"/Users/u.yilmaz/dev/ska-cicd-automation"} (2)
Error: Repositories with git submodules are not supported
{code: "errors.projects", message: "Repositories with git submodules are not supported"}
	(anonymous function) (user.3f3fe2e4.js:4:240)
	(anonymous function) (ipc.21fc29f2.js:1:2241)
```

<img width="507" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/7647900/e8df1a89-a04e-4338-9bed-d29a70a5536e">

**Comment by Byron** [comment]
Do you still have it in the index? If that's the case, `git checkout .gitmodules` work work despite `ls .gitmodules` failing. If that's the case, now GitButler is smart enough to get the `.gitmodules` file from the index, which is also what Git does I believe. This can be put to the test of course, but `git submodule` should list something.

**Comment by limonkufu** [comment]
ah okay that was it. I didn't think removing from the index was also needed. Thanks 👍

**Comment by ericclemmons** [comment]
Would it be unreasonable to change this from an error to a warning and prompt to "Continue at your own risk" (or whatever the risk actually _is_?)

Or perhaps cross-linking this issue or discussion to up-doot for support.

**Comment by aviv-vladimirsedlar** [comment]
I would second @ericclemmons suggestion.

**Comment by Byron** [comment]
I think previously there was data-loss when the code operated on Git indices with submodules, hence it was quickly forbidden entirely.
However, I also see why submodule support is important and made sure it's on a ping on the radar of the devs.

**Comment by krlvi** [comment]
> Would it be unreasonable to change this from an error to a warning and prompt to "Continue at your own risk" (or whatever the risk actually _is_?)
> 
> Or perhaps cross-linking this issue or discussion to up-doot for support.

This is a very good point. A dirty "hack" you could do is to remove the `.gitmodules` file only while adding the repo (and then re-adding it). The app already tries to ignore submodules in it's normal operation but there is some condition under which it doesn't handle it correctly, and I havent discovered yet what that conditions is

**Comment by krlvi** [comment]
Hello! The latest release `0.12.6` now allows adding of repos with submodules. Here is a full changelog entry for that version - https://discord.com/channels/1060193121130000425/1183737922785116161/1255135073242583122

Let me know how it works for you! Feel free to ping me here or on discord.

@phifuh (and everybody else) - i am sorry for the shitty onboarding. I hope it works correctly for you now in the new release

**Comment by sschuberth** [comment]
> the shitty onboarding.

🤣

**Comment by jokeyrhyme** [comment]
It's pre-1.0
I'm sure most of us understand that this is a work-in-progress and are just excited and grateful to see all this work being performed out in the open <3

**Comment by Byron** [comment]
With #4174 merged, you should be able to use GitButler on submodules [with the latest nightly build](https://app.gitbutler.com/downloads) - please let us know how it goes here :).

**Comment by jokeyrhyme** [comment]
Okay, I was able to add https://github.com/pop-os/cosmic-epoch to GitButler in 0.12.6, and I just bumped all the submodules locally

```
nu ❯ git status
## gitbutler/integration
 M cosmic-applets
 M cosmic-applibrary
 M cosmic-bg
 M cosmic-comp
 M cosmic-edit
 M cosmic-files
 M cosmic-greeter
 M cosmic-icons
 M cosmic-launcher
 M cosmic-notifications
 M cosmic-osd
 M cosmic-panel
 M cosmic-randr
 M cosmic-screenshot
 M cosmic-session
 M cosmic-settings
 M cosmic-settings-daemon
 M cosmic-store
 M cosmic-term
 M cosmic-workspaces-epoch
 M xdg-desktop-portal-cosmic
```

But GitButler doesn't display or seem to detect this as a change that needs to be branched / committed, it just has the "you are up to date" message

Then I made a change to a non-submodule file, which GitButler does detect properly, but it still doesn't offer to version those submodule reference changes

So it does indeed load the repository and function with non-submodule changes now, yay

**Comment by Byron** [comment]
That's great to hear!

I also think that's the expected behaviour, as it ignores all submodule changes outright.

**Comment by krlvi** [comment]
Okay, at this point I will close this issue as completed. Thank you all for your patience with us. If you come across any issues related to submodules or anything else, GitHub issues are very much welcome and appreciated! 
(or pinging us on discord)
