### ISSUE TITLE
Gitbutler does not kill the process after closing window

### ISSUE THREAD

**Issue by mnecas** [gitbutlerapp/gitbutler#2667]
Using the AppImage binary `git-butler_0.10.7_amd64.AppImage`
OS: Fedora 39, Gnome 45.4

1. Start AppImage binary 
2. Close the window 
3. The binary is still running without any window 
4. Need to kill the process manually then it's possible to start it again

When running the binary directly it is not a huge issue as you can see that the process is running but with the gnome desktop, you need to find the process.

If you need any more logs/info please let me know.

**Comment by KroniK907** [comment]
Can confirm that this is also an issue for me: Found quite a few update windows this morning: https://i.imgur.com/LW4OI9Y.png

I had closed and opened git butler several times, and the processes had never been killed: https://i.imgur.com/82lkjvi.png

**Comment by KroniK907** [comment]
I can also confirm that this happens in WSL Ubuntu 22.04 using the .deb release, so this issue is not just isolated to the AppImage.

**Comment by namanlp** [comment]
Hi there, it is same as

https://github.com/gitbutlerapp/gitbutler/issues/2630

This one can be closed.

Thank You

**Comment by mnecas** [comment]
Thanks for info
