### ISSUE TITLE
Create Pull Request generates "not found errors"

### ISSUE THREAD

**Issue by phish108** [gitbutlerapp/gitbutler#2669]
When having a first commit on a virtual branch, then the only option that really works is `push to remote` the other two options `create pull request` and `create draft pull request` generates `not found` errors. 

besides, such errors should not fade so quickly, so one can create screen shots.

**Comment by mtsgrd** [comment]
Hey, thanks for reporting this! We need to provide better feedback on why the pr creation fails. This code is new and a bit rough around the edges still. I'll let you know once I've had a chance to investigate.

Also, about the error fading. Just yesterday I switched us over to a new style of toast message for when we fail to open external links. I should do something similar here!

![image](https://github.com/gitbutlerapp/gitbutler/assets/1300356/1215e1ba-82b3-4cfe-aef0-c7fc0aa0f1ce)

**Comment by phish108** [comment]
The problem exists because for some reason the OAuth token did not receive access to the repo's PR. Is it possible that the OAuth Scope is missing the PR capabilities?

**Comment by Qix-** [comment]
Hey @phish108, this fell through the cracks a bit. Are you still facing this issue? We haven't heard about it for a while from other users so I'm wondering if the latest version of GitButler solves this for you.

Let me know if it's still causing issues and I'll re-open!
