### ISSUE TITLE
Files in virtual branches are not syncronised

### ISSUE THREAD

**Issue by phish108** [gitbutlerapp/gitbutler#2671]
Any change to a file will end up in the first virtual branch, not the one that the file has been previously dragged to. 

This has the strange side effect that some files remain present under changes in one virtual branch, if they have been committed in another virtual branch already. 

I would expect that once I dragged a file into a virtual branch, it stays put and does not show up in the other virtual branches. 

I would also expect that if I drag a file into a virtual branch, in which it has been committed already, it would be simply swallowed. However, this would be obsolete, if the files are properly tracked inside their virtual branches.

**Comment by Byron** [comment]
When trying this, both when dragging a file to a virtual branch and then changing it, and also committing it to another virtual-branch and then changing it, it would stick to the virtual branch I dragged it into.

After committing, it shows that the file is locked into the respective virtual branch as well, and new hunks can't be moved to other branches anymore.

<img width="856" alt="Screenshot 2024-04-21 at 16 15 51" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/6f2d6664-7faf-4aaf-bcff-6879ae188a1f">

Is what was initially described here still an issue, or is there another way to reproduce it?

**Comment by krlvi** [comment]
The UX around branches has been improved quite a bit since February. I am closing this for now since we haven't heard back. You are welcome to open a new issue if anything comes up!
