### ISSUE TITLE
feature: selecting/dragging multiple files or folders using CTRL

### ISSUE THREAD

**Issue by nbrugger-tgm** [gitbutlerapp/gitbutler#2673]
Normaly when multi select exists it works the way:
`CTRL`: select the files you click
`SHIFT`: select the files between where you selected and the previous selectio
```
- item1 (selected)
- item2
- item 3
```
If i click item 3 with 
- `CTRL`: i would expect that the selection is: item1 and item3
- `SHIFT`: I would expect that the selection is: item1, item2 and item3

This is just a minor inconvenience in UX that would align it with "common UI/UX" patterns

**Comment by mtsgrd** [comment]
Hey thanks for the feedback, I fully agree. It's just been a matter of priority, I think we're working as fast as we can. 😄 

On this topic still, I noticed you can currently `SHIFT` select files from different branches, and dragging them sort of groups them together as expected.. but, you can't actually drop all of them into something. But also, it might not be something we even want to support.

Perhaps the most logical solution would be to maintain selection states/groups for lanes independently, so only sibling files will be dragged?

**Comment by nbrugger-tgm** [comment]
Hi yes i only was talking about one list/branch.
So that the list in one branch follows the explained patterns, currently `SHIFT` acts as I would `CTRL` expect to behave

**Comment by Caleb-T-Owens** [comment]
Hi! This should now behave as expected. Feel free to open a new issue if that is not the case.
