### ISSUE TITLE
Double-clicking on the window for branch renaming, close this window, and collapse the related virtual-branch

### ISSUE THREAD

**Issue by Legrems** [gitbutlerapp/gitbutler#2677]
It' s counted toward a double-click on the header of the column  (where the branch name is)

**Comment by krlvi** [comment]
Hey @Legrems, I think this should be fixed now, the UI of the lanes has changed quite a bit since Feb. Let me know if this works for you now as expected.

**Comment by krlvi** [comment]
Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.
