### ISSUE TITLE
Displaying of diffs: highlight the actual changed part of the line

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2679]
discord discussions: https://discord.com/channels/1060193121130000425/1060193121666863156/1207354349731323934

**Comment by CHE1RON** [comment]
This is the only thing stopping me from using Gitbutler permanently right now tbh 😅

**Comment by Caleb-T-Owens** [comment]
Hi @CHE1RON ! This is now resolved 
![image](https://github.com/user-attachments/assets/d494f766-6e81-4216-b284-5dca48ebfaa5)
