### ISSUE TITLE
No error message provided when update fails [AppImage]

### ISSUE THREAD

**Issue by KroniK907** [gitbutlerapp/gitbutler#2682]
### Description
When launching an out of date version of the GitButler AppImage, an update window will pop up asking if you would like to update. When clicking yes, If the AppImage is stored in a location where the current user does not have permissions to update the AppImage the update will silently fail and provide no feedback.

### My Environment
OS: WSL2 Fedora remix running Fedora 39 
Gnome: 45.2

**Comment by Byron** [comment]
It seems like it would be a good start if the updater would merely become an info-box that makes it easy to get to the website to download the latest app-image.

**Comment by Caleb-T-Owens** [comment]
This should no longer be the case. Feel free to reopen if this is not the case 👍
