### ISSUE TITLE
Vscode reports File path does not exists [WSL]

### ISSUE THREAD

**Issue by JiroRauwers** [gitbutlerapp/gitbutler#2683]
Hey I know windows is not supported, but I HAD to try this awesome tool, and I'm running it on arch via wsl, the open in VScode button is not able to open as the file path is not right.

The visual code does open, it just don't recognize the path, I guess it is still trying to use the main windows vscode, instead of opening via the vsserver on the arch.

![image](https://github.com/gitbutlerapp/gitbutler/assets/14048545/73c0977d-48fc-4437-9e98-a31de2d84441)

I don't expect it to be fixed since is a 'windows' error. But thought it should be reported. Great tool, keep it up

**Comment by Qix-** [comment]
Hey there, Windows is actually now a first-class citizen of the GitButler release cycle. I'm going to close this for now as we're aware the WSL side of things is still not great, it will require a fair amount of work from us to make a bridge for it, and there are already a few other issues surrounding WSL that are tracking this a bit better.

Unless you actually need to work with WSL repositories from the Windows side, using the Windows build should be a much better experience :)

Going to close this for now - thanks for the report!
