### ISSUE TITLE
Tried to delete changes, entire branch got deleted instead!

### ISSUE THREAD

**Issue by ericclemmons** [gitbutlerapp/gitbutler#2692]
So, I just lost a few days of work & not sure how to get them back 😭 

I added a dependency that I didn't need to `package.json`. Normally I would `git checkout package.json` to delete/unstage those changes.

I clicked "Delete" and the entire branch is gone now.  Everything.

**Comment by DaniSancas** [comment]
I don't know how GitButler works (or why that happens), but probably your changes can be brought back.

Example: http://stackoverflow.com/questions/3640764/ddg#3640806

I hope you get your work back.

P.S: I was interested in the app, but after seeing this I'm becoming cautious about it 😅

**Comment by ericclemmons** [comment]
2 things I've learned:

1. Thanks to your link @DaniSancas, running `git fsck --full --no-reflogs --unreachable --lost-found | grep commit | cut -d\  -f3 | xargs -n 1 git log -n 1 --pretty=oneline > .git/lost-found.txt` let me find my last good commit, and I could `git reset --hard ${commit}` and didn't lose any work!
2. You can `ls -al .git/refs/gitbutler` for the vbranches (see https://twitter.com/krlvi/status/1758063415430406220), but it seemed my branch was gone from there too 👀
