### ISSUE TITLE
Support keyboard navigation when browsing changes

### ISSUE THREAD

**Issue by steffandroid** [gitbutlerapp/gitbutler#2694]
I commonly use the up and down arrows on my keyboard to iterate through the list of changed files in other Git GUI apps (e.g. GitHub Desktop), so would really like this to be added in GitButler.

Currently, the arrow keys scroll the whole workspace, but I don't find this to be particularly useful.

This is with macOS, not sure if it behaves differently on other platforms.

**Comment by steffandroid** [comment]
The arrows keys now iterate through the files, but in a seemingly arbitrary order rather than the displayed order.

**Comment by PavelLaptev** [comment]
@steffandroid thank you for the report!
Do you still encounter the issue? If yes, could you please write the version you're currently on and which OS are you using.
It would be ideal if you can also capture a video of this bug. Thanks 🙂

**Comment by steffandroid** [comment]
@PavelLaptev pleased to see this is no longer an issue – closing.
