### ISSUE TITLE
Double click on branch name during rename change window size instead of selecting text

### ISSUE THREAD

**Issue by stekman08** [gitbutlerapp/gitbutler#2699]
Virtual branch -> Set branch name -> double click in text area to select all text 

Expected behavior is now that the text in the textbox will be selected, but instead the window size is changed

**Comment by Byron** [comment]
As of GitButler Version 0.11.3 (20240419.070253) I was unable to reproduce this issue, assuming that the following is indeed the Window described here.

<img width="476" alt="Screenshot 2024-04-21 at 18 55 20" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/6000e21f-22cd-4c35-aa33-4b8227ff8f94">

Could you validate that this works for you as well? Thank you.

**Comment by Caleb-T-Owens** [comment]
Hi! I believe this has now been resolved due to UI updates. Feel free to open an issue if the problem still persists for you.
