### ISSUE TITLE
For fetch / push use ports configured in ~/.ssh/config

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2700]
This applies for setups where the remote has non-22 port setup for ssh

**Comment by Byron** [comment]
By now it's possible to use the Git executable for authentication. The setting is available in the project settings of existing projects are can be set when adding new ones.

<img width="605" alt="Screenshot 2024-04-21 at 18 51 12" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/95984390-26d3-4cf5-9042-6ec022b0c758">

Does this work for you?

**Comment by Qix-** [comment]
Indeed, going to close this for now - if possible, switch to the Git executable auth mechanism which should honor all of your Git config.

Let me know if this isn't the case for some reason! Thanks for the report :)
