### ISSUE TITLE
Improve Branch Search and Case Sensitivity in Branch View

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2709]
For branches that have PRs, in the branch view, I can't search for their branch names. I can see the branch name if I click on them, bit its quite cumbersome. It would be neat if it still showed their names below the PR titles, and if I could still search for them.

The search box also seems to be case-sensitive, which would be fine, if it wasn't for the fact that macOS auto correct is coming in and capitalising the first letter of what I type in 😆

https://discord.com/channels/1060193121130000425/1073202153163857920/1207643377890369537

**Comment by krlvi** [comment]
fixed in https://github.com/gitbutlerapp/gitbutler/pull/2732
