### ISSUE TITLE
Doesn't pick up on deleted / moved file

### ISSUE THREAD

**Issue by TheKnarf** [gitbutlerapp/gitbutler#2711]
When moving a file GitButler only seems to pickup the new file, not the deletion of its old location (or it simply doesn't show it in the gui?).

So when dragging that file over to a virtual branch it creates a couple of problems:

- The file is still deleted in my main branch

- The "Gennerate message" button creates a commit message thinking I added a file instead of simply moving it

- The new branch now adds the file so instead of moving it its just twice up in my repo

**Comment by coder2000** [comment]
I have the same issue with my repo.
![Screenshot from 2024-02-19 12-58-29](https://github.com/gitbutlerapp/gitbutler/assets/27944/73b65c2c-b15b-4aa3-91e6-69e22b019ebf)
![Screenshot from 2024-02-19 12-58-50](https://github.com/gitbutlerapp/gitbutler/assets/27944/33cfa959-7e84-428a-aa3a-6742d354349c)
