### ISSUE TITLE
When using folder view you can't drag folders over

### ISSUE THREAD

**Issue by TheKnarf** [gitbutlerapp/gitbutler#2712]
It seems that can only move single files, but not entire folders, over into a virtual branch.
It would be useful if I could drag an entire folder at once.

**Comment by krlvi** [comment]
i like this idea a lot :)

**Comment by PavelLaptev** [comment]
@TheKnarf are you talking about "Tree view"?

![image](https://github.com/gitbutlerapp/gitbutler/assets/18498712/f13e4a05-31ef-4364-904f-f536d3859cdb)

**Comment by TheKnarf** [comment]
> @TheKnarf are you talking about "Tree view"?

Yes

**Comment by PavelLaptev** [comment]
@TheKnarf Got it! Thanks for the issue.
We removed the tree view for now because we're updating the design of lanes and how we show file changes. So, this issue isn't relevant anymore. However, if we decide to bring back the tree view later, we'll implement the behavior you described.
