### ISSUE TITLE
"Generate message" have no concept of what my PR is actually about

### ISSUE THREAD

**Issue by TheKnarf** [gitbutlerapp/gitbutler#2713]
It doesn't seem to understand or have any concept about what the PR is actually about, as such the messages are often useless.

Even when I set the branch name manually that does not seem to affect the gennerated message.

Ex. I had a PR where I worked on updating the "docker-compose" files, I named the branch using GitButler "docker-compose-update". But the changes also included some cleanup of npm dependencies.

The resulting generated message was `📦 chore: update dependencies` and a lot of line about which packages I added, removed and updated. But nothing about the fact that I updated all of my docker compose files and fixed some Dockerfiles. If the auto generated messages are going to be of any use there needs to be some way of nudging it towards what is most important of the PR (ex. with branch name). The message should not just be a list of files changed. Anyone can see that from the content of the diff.

Maybe there could be a way of writing 1-2 lines about what the PR is about, and have it automatically embellish it with details.

**Comment by krlvi** [comment]
Hey, thanks for reporting this. It seems to me like the language model gets confused and starts hallucinating. There are 2 things that we'd like to do to improve this:
- make the prompt user-customizable (such that you can give it your own instructions etc) - tracking in  https://github.com/gitbutlerapp/gitbutler/issues/2624
- make the LLM endpoint customizable - this way a user can pick a more powerful model or a local one - tracking in https://github.com/gitbutlerapp/gitbutler/issues/2660

If you don't mind I will close this, feel free to add any thought in #2624 or open a new issue if something comes up
