### ISSUE TITLE
bug: can't push or create pr

### ISSUE THREAD

**Issue by kcoderhtml** [gitbutlerapp/gitbutler#2724]
Whenever I try to push to remote it fails silently and when I try to make a pr instead it errors with `branch push failed`.
<img width="1272" alt="55449" src="https://github.com/gitbutlerapp/gitbutler/assets/92754843/7d15be9a-c9f2-4f46-89a9-c2af0df129c9">
I don't know where the log file is, but if I find it I will attach it here.

**Comment by FaithfulDev** [comment]
@kcoderhtml On Ubuntu (WSL) I can see some logs here: `\home\<username>\.config\com.gitbutler.app\logs`

**Comment by kcoderhtml** [comment]
Thanks! I'm on a mac and just found them at: `/Users/{username}/Library/Logs/com.gitbutler.app/`

Weirdly after switching back to a git branch and then GitButler warning me about it and switching back to GitButler it works now?
