### ISSUE TITLE
bug: quotes are changing from " to « by themselves

### ISSUE THREAD

**Issue by nikolaistarostin** [gitbutlerapp/gitbutler#2728]
I am trying to type quotes (") in commit message, but the keep changing to different quotes («»)

I have ABC (English) and Russian keyboards enabled on my laptop (MacBook Pro, macOS 14.1.1), and I am typing using ABC keyboard.

Here is a video with an example.
https://github.com/gitbutlerapp/gitbutler/assets/48692605/e53aef8e-ada3-4a26-b072-2dc209c4622b

**Comment by 03juan** [comment]
Is it possible you have smart quotes enabled for double quotes in your keyboard input sources settings?

Refs:
https://support.apple.com/en-gb/guide/mac-help/mchl84525d76/14.0/mac/14.0
https://support.apple.com/en-gb/guide/mac-help/mh35735/14.0/mac/14.0

**Comment by krlvi** [comment]
I think we need to do `autocomplete='off' spellcheck='false' autocorrect='off'` on inputs

**Comment by krlvi** [comment]
This should be fixed by https://github.com/gitbutlerapp/gitbutler/pull/2737
I'm going to make a release tomorrow morning
