### ISSUE TITLE
The "looks like you have switched away from gitbutler/integration" screen should have an option to delete the project

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2735]
Similar to the error screens

**Comment by Byron** [comment]
<img width="639" alt="Screenshot 2024-04-21 at 17 03 47" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/372ecfef-610f-4159-a0a6-39091d7e5cb6">

This has been implemented by now.
