### ISSUE TITLE
AppImage doesn't work when `libthai` isn't installed

### ISSUE THREAD

**Issue by cindrmon** [gitbutlerapp/gitbutler#2740]
I'm using Funtoo GNU/Linux when i wanted to try out gitbutler. However, when I downloaded the AppImage and tried running it, it doesn't work, and running it in the terminal shows that it is looking for `libthai.so`, in which I cannot install on my system since it is not available. 

Also apparently, it has been evident that Tauri apps when run as an AppImage on systems similar to mine (according to [https://github.com/OpenShot/openshot-qt/issues/5060](https://github.com/OpenShot/openshot-qt/issues/5060)) won't run because of the same dependency issue. I'm hoping that upon release you may also look into adding `libthai` as an optional dependency for GNU/Linux users who don't happen to have, or cannot install `libthai` on their system.

**Comment by honnip** [comment]
This should be resolved in tauri. https://github.com/tauri-apps/tauri/issues/4930

**Comment by Byron** [comment]
Meantime, GitButler 0.11 is available and I wonder if the `tauri` fixes trickled through. Could you try to reproduce the issue with the latest version?

**Comment by Qix-** [comment]
Going to close this as this is more of an issue with Tauri - it doesn't seem to be the case that we can contol anything dependency-related with AppImage packaging from our end.
