### ISSUE TITLE
Consumes too much memory. Other apps work just fine.

### ISSUE THREAD

**Issue by sakthig** [gitbutlerapp/gitbutler#2741]
Unable to use gitbutler on my large repo., Keeps saying busy. Eventually consumes too much memory and starts slowing down the system. VScode, Sublime merge, Cli all work fine.

<img width="840" alt="Screenshot 2024-02-16 at 9 07 07 AM" src="https://github.com/gitbutlerapp/gitbutler/assets/101381/bf57b70f-ed3d-4762-83d4-2925a20a2106">

**Comment by tharrison4815** [comment]
This must be a memory leak surely? I have had the app open all day and mine is using very little resources. Are you using Apple silicon or Intel?

<img width="966" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/54081901/ca9020a0-afd6-464e-8f30-4287e03babbd">

<img width="654" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/54081901/b3f53d67-8892-4d00-845d-a38d2650f76e">

**Comment by sakthig** [comment]
I am using apple silicon ( m1 pro ) 16gb.

**Comment by brendo-m** [comment]
I also saw this on an m1 pro but quite a bit worse

<img width="429" alt="Screenshot 2024-02-16 at 1 36 38 PM" src="https://github.com/gitbutlerapp/gitbutler/assets/13846234/be48e2f4-ba47-4578-8b90-9872ff27ebdb">

**Comment by tharrison4815** [comment]
Hum ok I guess it's not related to the architecture then as I have an M1
Pro and I am using the Apple silicon version with no issues.

**Comment by codebykenny** [comment]
![Kenny- 2024-02-18 at 08 48 14](https://github.com/gitbutlerapp/gitbutler/assets/6720728/0fe2ae34-8a3b-4fec-9da0-c3cccf6a6824)

Apple M1 Max

**Comment by krlvi** [comment]
We have fixed quite a few performance issues & bugs since February (mostly communicated over discord at the time)
@sakthig, @tharrison4815, @codebykenny, @brendo-m - has any of you encountered this issue in a recent release? Thank you for being patient with us 🙏 
The apps must be much faster now too

**Comment by krlvi** [comment]
Closing this one since we havent heard back from the author. Feel free to create a new issue if this is still an issue. Thank you.
