### ISSUE TITLE
Unable to Rename Virtual Branch

### ISSUE THREAD

**Issue by aphronyx** [gitbutlerapp/gitbutler#2742]
https://github.com/gitbutlerapp/gitbutler/assets/64679454/e8e02339-0a46-4721-af92-6c146f98c788

**Comment by askielboe** [comment]
Are you by any chance pressing Enter when finished editing the name? Could you try not pressing Enter, but clicking outside the branch name text field instead?

There is currently a bug where pressing Enter to change a branch name doesn't work, see https://github.com/gitbutlerapp/gitbutler/pull/2688.

**Comment by aphronyx** [comment]
i thought #2743 referred to the feature 'Set branch name'. srry for duplicating the issue.
i'll test again when 0.10.10 is released, thx
