### ISSUE TITLE
Constant CPU usage while idle (ubuntu 22.04)

### ISSUE THREAD

**Issue by esolitos** [gitbutlerapp/gitbutler#2744]
### Problem

It seems that even when IDLE the app has a 10~20% cpu core constant usage, single open instance with a very small git repository.

I have not dig into what it is doing, but it is definitely happening constantly. :)  

### System Info

Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

CPU: [Intel Core i7-11800H](https://ark.intel.com/content/www/us/en/ark/products/213803/intel-core-i7-11800h-processor-24m-cache-up-to-4-60-ghz.html)

### Screenshots

![image](https://github.com/gitbutlerapp/gitbutler/assets/401819/55e50240-3efa-4853-b086-3fed160c5614)

**Comment by patternseek** [comment]
I'm seeing the same except that it's 95% with a large repo with a lot of legacy branches.

**Comment by krlvi** [comment]
Thank you for reporting this. There are definitely some inefficiencies that we became aware of, and im working on fixing them one by one. 
Which app version did you experience this in? The past two releases (0.10.10 [changelog in discord](https://discord.com/channels/1060193121130000425/1183737922785116161/1208139397946544179) and 0.10.11 [changelog in discord](https://discord.com/channels/1060193121130000425/1183737922785116161/1208770044071510016) contain a few performance optimizations that might be relevant)

There are still some outstanding issues though, especially with repositories with many remote branches, as well as incorrect handling of LFS. If you dont mind, i will update this thread when I have a patch specifically related to handling of many branches.

**Comment by esolitos** [comment]
> Which app version did you experience this in? 

I was running 0.10.7, now upgraded to 0.10.12 and I am seeing pretty much the same situation.

FYI: I have purposely selected a small repo with very few branches to test this software and I only have a single project connected, so I should be pretty much in the bare minimum of resources usage.

**Comment by krlvi** [comment]
(accidental button press) ☝️ 

@esolitos if you have time, would you be able to try out the latest build? There are 2 optimizations that I made recently - one which makes vbranch operations more efficient, and also separately there was an issue where recomputing of state was triggered from changes to gitignored files (and as it turnes out, some editors/ IDEs like to write a bunch).

🙇

**Comment by esolitos** [comment]
Hi @krlvi, first of all thanks for looking into this!

I'm sorry to report that even with the most recent version I still see a constant ~10% CPU usage.

Let me know if you need any detail to help you understand the source of this issue.

**Comment by KroniK907** [comment]
Can confirm similar results. Here is the top command showing what it looks like with gitbutler running (the WebKitWebProcess is the browser window for gitbutler).
![WindowsTerminal_2024-02-29_16-29-50](https://github.com/gitbutlerapp/gitbutler/assets/4690564/f4294308-1f40-420f-9354-3815e1cf0c38)

Here is what it looks like with gitbutler closed but a chromium browser open on the gitbutler homepage for context:
![WindowsTerminal_2024-02-29_16-27-44](https://github.com/gitbutlerapp/gitbutler/assets/4690564/26cbe6a9-79c4-439c-8c87-747b1ea211e0)

It seems like most of the idle usage is happening in the webkit process not the backend.

**Comment by KroniK907** [comment]
Just for the heck of it I removed ALL of my repos from gitbutler and fully relaunched it, and this is what the usage looked like on the welcome setup screen:
![WindowsTerminal_2024-02-29_17-06-25](https://github.com/gitbutlerapp/gitbutler/assets/4690564/4122619b-e29b-48ad-8610-0e434e29864a)

**Comment by esolitos** [comment]
Just updated to 0.10.22 and I must say that this looks 100% resolved. :)

I'll go ahead and close this, thanks for the amazing work done!
