### ISSUE TITLE
Incorrect project settings displayed when navigating from main menu

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2746]
Another strange thing:  I have multiple projects and I open the last one in the list.  When I go to main menu, click _Project_ and then _Project Settings_ the view moves away from the opened project and the Project Settings for the first project in the projects list is displayed.   I expected to see the settings for the currently opened project.

https://discord.com/channels/1060193121130000425/1073202153163857920/1207974447638650920

**Comment by Byron** [comment]
I believe this is fixed as of Version 0.11.3 (20240419.070253). Could you check if this is still an issue for you?

**Comment by Caleb-T-Owens** [comment]
Hi! I believe this should be resolved
