### ISSUE TITLE
Display images

### ISSUE THREAD

**Issue by JohnAtl** [gitbutlerapp/gitbutler#2752]
Rather than 'Binary content not shown', an image preview would be nice.

**Comment by krlvi** [comment]
Makes total sense! Thanks, this is probably to a difficult one to implement either

**Comment by koppor** [comment]
Isn't this app TypeSript / Svlete based? Thus, outputs HTML to kind of a browser? Then `<img>` can be used. OK, maybe serving the binary from the "backend" is hard. However, the text also gets displayed in the UI somehow. -- Maybe the "naive" answers at https://stackoverflow.com/q/56895865/873282 help somehow?
