### ISSUE TITLE
Commit signing appear to no longer work

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2763]

**Comment by Caleb-T-Owens** [comment]
I've just tried this out, the first time I switched the switch, no value was added to my .gitconfig, but the second time I turned it off and on, it worked

**Comment by Caleb-T-Owens** [comment]
I'm wondering if because the code for getting the value in the settings pannel looks like:
```ts

	git_get_config({ key: 'gitbutler.signCommits' }).then((value) => {
		signCommits = value ? value === 'true' : true;
	});
```
its accidentally defaulting to "true" rather than "false"

**Comment by krlvi** [comment]
yeah you are right! this must be the very definition of a "have you tried switching it off and then on again" 😅
