### ISSUE TITLE
Handle different workflow

### ISSUE THREAD

**Issue by Seluj78** [gitbutlerapp/gitbutler#2767]
Hi !

First of all, thank you very much for gitbutler ! It's really interesting!

My usual workflow when coding is

- checkout the `develop` branch and update it with a `git pull`
- Create a new branch
- do my work there
- commit and push
- do the PR and update as necessary this branch

While this works great using the git CLI, I can't seem to make it work nicely with gitbutler. Trying to apply existing branches, commiting to them and then checking them out manually will produce weird bugs like duplicates ...

I'd love some help on how to properly use gitbutler, especially since I'm the only one using it in my company 👀

**Comment by krlvi** [comment]
Hi @Seluj78! A current limitation of the app is that you can't switch the target branch (Trunk) of the project after adding the repo. I understand this is definitely something needed for workflows such as gitflow, or when using multiple remotes at the same time. We are tracking the progress for this in this card: https://github.com/gitbutlerapp/gitbutler/issues/2507

It may not fully solve your situation now, but you could try re-adding the project and setting your target/base to be `develop` , that way you will be able to create PRs towards it. Let me know if this helps

**Comment by Seluj78** [comment]
Hi,

After posting this issue, I went and read the docs (which I should've done first 👀 ) and I saw an explanation. I'm happy to hear you're working towards it and I can't wait to see what gitbutler will be in the future !

**Comment by Seluj78** [comment]
PS: I've switched the base to be `develop` and it still causes issues, so a "better" gitflow support is definitely a plus for me :)
