### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by Keloran** [gitbutlerapp/gitbutler#2769]
Having the ability to either chose a dark mode theme

e.g. Dracula or Catppuccin

but the ability to add one to a folder, and then chose it from the interface would be better

**Comment by prince-patel23** [comment]
@ngalaiko ,can you assign me this issue so i can work on it.

**Comment by krlvi** [comment]
Hello @Keloran @prince-patel23, the app currently does have a dark mode (can be found in the user settings):
<img width="778" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/4030927/d110512d-f776-4c8f-84e8-4a29bacf850f">

In the future we may support configuring your theme with inside a json file, but that's something we'd like to tackle a bit later on
