### ISSUE TITLE
Better user error message when an added repository has no commits in it

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2778]

**Comment by Caleb-T-Owens** [comment]
This is related to https://github.com/gitbutlerapp/gitbutler/issues/2725

**Comment by Pranav2612000** [comment]
Hey @krlvi 
I'll like to work on this issue.

**Comment by Pranav2612000** [comment]
I was able to set up and get the repo working ( Would love to point that it was very easy to set up and get started ).
I've dug into the code and found out that the `repo.head()` func used in `symbolic_head` method returns a `GIT_EUNBORNBRANCH` error when head points to non-existing branch ( Ref: https://libgit2.org/libgit2/#HEAD/group/repository/git_repository_head ). This is also consistent with the error code we see - `-9` as the error code for `GIT_EUNBORNBRANCH` is `-9` as well. ( Ref: https://github.com/libgit2/libgit2/blob/c2247bf267c8f03a6cb11edc87522a3164a44e38/include/git2/errors.h#L38 )

**Comment by Pranav2612000** [comment]
From a product perspective, I'm not sure what's the best way to resolve this problem. As a user, I would love to proceed ahead with an empty git repository, but I'm not sure if that is technically feasible, and something we want at the moment.

For now, I'll update the error message to be something on the lines of `Cannot load a git repository with 0 commits` ( Or whatever you think is the best copy ).

I'll have a PR up soon. Let me know if you want this to be done some other way and I'll be glad to help.

**Comment by Caleb-T-Owens** [comment]
Imo, It would be nice if before we try loading the project, if we tried calling to get the symbolic head directly in the code, so we can controllably catch the error (without relying on the panic message) and offer to the user to make an initial commit and add a remote

**Comment by Pranav2612000** [comment]
Yeah. Makes sense. Should we wait for what others think?

Also the improvements you suggested can also apply to some other error messages that we throw. Should we handle all of them in the scope of this issue ( and PR ). Or should we make it a bigger project of improving the onboarding experience?
