### ISSUE TITLE
Support using 1password managed ssh keys

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2779]
discord discussion https://discord.com/channels/1060193121130000425/1208456893383577671/1208510948516696155

**Comment by jsvensson** [comment]
Came to make just this issue. For reference, this is the relevant(?) part of my git config to use 1Password as the SSH agent.

```
[user]
	signingkey = ssh-ed25519 [redacted]

[gpg]
	format = ssh

[gpg "ssh"]
	program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[commit]
	gpgsign = true
```

**Comment by bryanrossUK** [comment]
Just adding my support for this!  In additional to all the folks on Discord that have mentioned 1Password, I too would love to see support for their ssh-agent.  More info at https://developer.1password.com/docs/ssh/agent for anyone that's looking.

**Comment by ShravanSunder** [comment]
+1 for allowing ssh agents please

**Comment by mtsgrd** [comment]
We're experimenting with using the git binary for fetch and push, it feels likelu it would unlock some of the above. #3222 #3227

**Comment by mackermans** [comment]
Can confirm that 1password now correctly prompts for approval when selecting the "Use a Git executable" option! 🚀 

(Tested on v0.10.27)

<img width="595" alt="Screenshot 2024-03-24 at 19 20 44" src="https://github.com/gitbutlerapp/gitbutler/assets/4571935/b2abb4cb-cef6-4fdd-9cde-3f470f2f246c">

**Comment by jsvensson** [comment]
+1 on that! This was the major blocker for me, preventing me from actually giving GitButler a fair shake. Looking forward to using it now!

**Comment by Byron** [comment]
That was such a nice read, thanks for sharing!

Managed SSH keys seem to be working thanks to using the Git binary, so I am closing this issue as resolved. Please feel free to open new issues for other areas that might still need improvement, or reopen if this was the wrong call.
