### ISSUE TITLE
Failing to push/create branch

### ISSUE THREAD

**Issue by anup-a** [gitbutlerapp/gitbutler#2790]
Whenever I try to push my branch, it throws the error with a message - "Something went wrong".

Also, is there a way to see the logs? I was struggling to locate log file on my mac.

![image](https://github.com/gitbutlerapp/gitbutler/assets/29516633/f61886aa-bb7a-43c5-b077-257a5db796f9)

**Comment by anup-a** [comment]
Update: It worked after adding Remote Integration with Github. But I'm not sure if that is a required step, maybe I missed something.

**Comment by krlvi** [comment]
Hey there! I am glad you got it working. Generally this type of error (on fetching or pushing) generally means that git authentication did not work.

A few things that you can try is, in the project settings 
<img width="327" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/4030927/80515625-e570-4ea8-a455-3fa29284252f">

try enabling "Ignore host certificate checks". 
If this alone does not solve the issue, try out the other authentication options that are available. 
<img width="819" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/4030927/68baca6c-c6e9-4fdb-a707-400ebd09265e">

If none of this helps, feel free to ping me or somebody else from the team on [discord](https://discord.com/invite/MmFkmaJ42D) and we will be happy to help out.

**Comment by ndan** [comment]
In my case I was missing organization permission

* Go to Github settings -> Applications -> Authorized OAuth Apps -> GitButler client -> Organization access
* Click "Grand" next to the organization

**Comment by Byron** [comment]
By now the application does a good job at communicating the error and offering help:

<img width="521" alt="Screenshot 2024-04-21 at 22 02 35" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/edbe030b-04f0-47a4-b935-519a39bbac4f">

Based on this, I am closing the issue but invite you to keep commenting if this keeps cropping up or changes shape.
