### ISSUE TITLE
Consider using commit message for PR title and description in case of a single commit

### ISSUE THREAD

**Issue by eyalch** [gitbutlerapp/gitbutler#2795]
When creating a PR directly in GitHub (or via the GitHub CLI) for a branch with a _single_ commit, the default values of the PR title and description is the commit message—first paragraph for the title and the rest for the description.

This behavior is quite convenient.

Please consider implementing the same behavior when creating a PR via GitButler.

After a quick glance at the code, I came up with the following:

```diff
diff --git a/gitbutler-ui/src/lib/branches/service.ts b/gitbutler-ui/src/lib/branches/service.ts
--- gitbutler-ui/src/lib/branches/service.ts
+++ gitbutler-ui/src/lib/branches/service.ts
@@ -67,13 +67,25 @@
 		}
 
 		const createPrSpan = sentryTxn.startChild({ op: 'pr_api_create' });
 
+		let title = newBranch.name;
+		let body = newBranch.notes;
+
+		// In case of a single commit, use the commit summary and description for the title and
+		// description of the PR
+		if (newBranch.commits.length === 1) {
+			const paragraphs = newBranch.commits[0].description.split("\n\n");
+
+			title = paragraphs[0];
+			body = paragraphs.slice(1).join("\n\n");
+		}
+
 		try {
 			const resp = await this.githubService.createPullRequest(
 				baseBranch,
-				newBranch.name,
-				newBranch.notes,
+				title,
+				body,
 				newBranch.id,
 				newBranch.upstreamName,
 				draft
 			);
```

Please note that I haven't tested this. Let me know if you think this is a good idea and whether it's the correct approach.

**Comment by krlvi** [comment]
hey @eyalch, i love this idea! feel free to submit it as a PR and I will merge it in for the next release :)

**Comment by Pranav2612000** [comment]
Hey @eyalch ! Are you working on this? If not, I'll love to pick this up.

**Comment by eyalch** [comment]
@Pranav2612000 TBH, I was a little busy in the past few days, so I didn't get to it.

Feel free to pick it up!

**Comment by Pranav2612000** [comment]
Cool. Thank you @eyalch 
PR coming right up.
