### ISSUE TITLE
when Create PR there is no response

### ISSUE THREAD

**Issue by colinn66** [gitbutlerapp/gitbutler#2797]
when I click the create pull request button，There is no response，and the whole app hangs
![image](https://github.com/gitbutlerapp/gitbutler/assets/107197811/cc2b6496-53f9-4be9-83b4-35fa2d18c636)
I‘v updated to  V0.10.11，and still not work。

**Comment by krlvi** [comment]
Hey there! Is this an organization repository? It's very possible that this is related to org restriction on oauth applications. 
The app currently doesn't do a very good job of propagating this error (tracking in https://github.com/gitbutlerapp/gitbutler/issues/2780) 

One way to solve this would be to [authorize the oauth](https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization) app for the organization. Alternatively, you could create your own oauth app and set GitButler to use that one (requires compiling the app from source, perhaps this is something we can support better in the future).

Let me know if this helps out

**Comment by ekwoka** [comment]
@krlvi I am having this same issue and it is not a org repo, and it is authorized with oauth to my personal account

**Comment by colinn66** [comment]
@krlvi Thank you for your message.
This is not  an organization repository.
I can push to remote, but can't create PR.When I create the PR on github, I can merge it in GitButler.
So ,I feel there maybe have some bugs.
![image](https://github.com/gitbutlerapp/gitbutler/assets/107197811/31c73b45-4fd7-4c44-b537-e35284738b03)

**Comment by PavelLaptev** [comment]
@colinn66 hi 🙂 do you still have the issue?
