### ISSUE TITLE
Fails to detect system preference for appearance

### ISSUE THREAD

**Issue by moritztim** [gitbutlerapp/gitbutler#2803]
In user settings > "Appearance" > "Interface theme", selecting "System preference" always defaults to light mode instead of going dark, which is the preference I have set. Most other apps go into dark mode, I did have trouble with github desktop tho, maybe that's related: https://github.com/shiftkey/desktop/issues/932
GNOME, GDM, Arch Linux

**Comment by Byron** [comment]
When trying to reproduce the issue on MacOS with Version 0.11.3 (20240419.070253), it seemed to work as expected.
Is the issue still present on your platform using the latest version? Thanks for letting me know.

**Comment by jokeyrhyme** [comment]
It's probably related to this: https://github.com/tauri-apps/tauri/issues/9427

**Comment by chris-torruella** [comment]
@moritz-t-w hello! Looking at [this response](url) seems like this is a solved issue.
Anyway I invite you to try our new app themes as part of V11. Hope you enjoy them! Cheers

**Comment by jokeyrhyme** [comment]
@chris-torruella doesn't GitButler use tauri, not electron?

**Comment by chris-torruella** [comment]
Hello folks, excuse me, I mixed threads as you point out @jokeyrhyme 
We will be coming back to you for any installments in this one
