### ISSUE TITLE
Application crash on startup when trying to list projects

### ISSUE THREAD

**Issue by niceFont** [gitbutlerapp/gitbutler#2807]
Hello, I am currently facing an issue when trying to open the application after I restarted my computer.
It says that it fails trying to list my projects. I am running the latest version on Pop!_OS 22.04 LTS.

![image](https://github.com/gitbutlerapp/gitbutler/assets/21206440/450574c1-b6b2-4ba8-8c45-a89dc15ed280)

**Comment by alabhyajindal** [comment]
Hi! Did you run into this issue again? How are you launching the application?

Do you have some steps I can use to reproduce the crash?

**Comment by niceFont** [comment]
I was not able to reproduce it unfortunately. For some reason my `projects.json` was suddenly empty, maybe something caused it to fail while updating. 
I fixed it by just deleting everything from `.local/share/com.gitbutler.app` and reinstalling.

**Comment by Byron** [comment]
Thanks for reporting!

Currently the application [writes this file directly](https://github.com/gitbutlerapp/gitbutler/blob/72291ce4cb039f8675ec143a0ad672936a183ce1/crates/gitbutler-core/src/storage.rs#L38-L44), which can leave it half-written or empty for that matter if the app is killed in just the right time.

A solution would be to write a new file, and move it into place when done as this would make the write atomic.
