### ISSUE TITLE
Switching back to gitbutler/integration should return the developer to the state where they left it

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2820]

**Comment by mtsgrd** [comment]
I thought this issue was fixed. Would you mind adding a bit more context @krlvi?

**Comment by ngalaiko** [comment]
https://github.com/gitbutlerapp/gitbutler/pull/3044

**Comment by schacon** [comment]
Closing for #3048, where I'll write up a better solution
