### ISSUE TITLE
Refactor moving commits in the front end

### ISSUE THREAD

**Issue by mtsgrd** [gitbutlerapp/gitbutler#2828]
@ngalaiko wrote in https://github.com/gitbutlerapp/gitbutler/pull/2750
> ...this will need some frontend inputs, perhaps refactoring. we have to have a way to verify that moving commit is only possible for:
> 
> a head commit (that is done)
> that does not have any hunks locked to self <- this should be implemented
> another unknown for me from a design perspective is where to display dropzone for the commit. now it's rendered on top of the files list, but maybe is there are local commits present, we should render it inside of the local commits box instead?
> 
> in general, it looks like since the lane was split into boxes with files, local commits, remote commits, etc. some drop zones render in a wrong place (like for example cherry picking drop zone)

**Comment by krlvi** [comment]
@mtsgrd is this issue still relevant?
