### ISSUE TITLE
Virtual branch ref names do not update when changing the virtual branch name

### ISSUE THREAD

**Issue by mrenouf** [gitbutlerapp/gitbutler#2836]
When I create a virtual branch, unless I set the branch name before interacting with the branch at all, the gitbutler refnames used never change. 

Due to workflow restrictions, I need to push from the virtual branch to another virtual remote ref (Gerrit). Having all my virtual branches named "Virtual-branch-1" 2, 3, 4 is very difficult.

**Comment by mrenouf** [comment]
The other bug is that the displayed virtual branch name doesn't match the the refname used.

 I know these are more of an internal implementation detail, but in light of other situations (like recovering lost state), having the refnames match would be give me a bit more comfort as well.

**Comment by Byron** [comment]
Thanks for reporting!

By now, it seems all this has changed as is visible in the screenshot below. Manually named ref-names seem to work just like automatically named ones.

<img width="630" alt="Screenshot 2024-04-21 at 21 02 59" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/fcf1855d-457f-4605-9150-c01e69fbb9fb">

Is there something else that I am not seeing? Thanks for your feedback.

**Comment by krlvi** [comment]
Closing this because we have not heard from the original author and we believe this issue has been fixed in recent releases
