### ISSUE TITLE
Add support for pushing to a different remote branch than pulling (Code Review)

### ISSUE THREAD

**Issue by mrenouf** [gitbutlerapp/gitbutler#2839]
For workflows involving code review, we push changes to a virtual remote branch. The changes are effectively creating a new remote commit each time, taken as a snapshot and included as a revision in the code review.

Since each push is a new change (and commit sha, which might have a new parent... eg. amended or rebased), the changes are linked up by metadata in the commit message.

In gerrit, if you:

    git pull remote main
 
you'd push like:

    git push remote refs/gitbutler/Virtual-Branch-1:/refs/for/main

So all that is needed for this to work smoothly with Gitbutler is adding an optional push target (maybe called "review branch" or something?) .

**Comment by torarnv** [comment]
This is relevant for me as well

**Comment by torarnv** [comment]
This might be possible to solve with a custom push transport and helper?
