### ISSUE TITLE
Suggestion: Double click on branches to Apply the branch/pr

### ISSUE THREAD

**Issue by uffou** [gitbutlerapp/gitbutler#2849]
As a user, I expect to be able to apply the branch by double-clicking on a branch in the bottom left where branches and PRs are listed.

**Comment by krlvi** [comment]
I am not sure about double clicking (as it could be surprising / confusing), but perhaps a right-click menu could have things like apply/delete etc. What do you think, @PavelLaptev ?

**Comment by PavelLaptev** [comment]
I suggest using right-click for this functionality. We don't currently use double-click anywhere in the app, and I would avoid adding it until we decide where and how to implement this pattern consistently.

**Comment by PavelLaptev** [comment]
I'll close this issue for now until it’s raised again.
