### ISSUE TITLE
Auto detect authentication method broken for organisation repos

### ISSUE THREAD

**Issue by SohamGhugare** [gitbutlerapp/gitbutler#2875]
The auto detect method seems to throw an error for organisation repos (especially the ones I'm owner in). The error message says
```
Failed to push branch: Project remote authentication failed
```

switching to some other mode like ssh, works fine!

**Comment by SohamGhugare** [comment]
I highly suspect if this is related to the organisation's OAuth Restriction Policy? However the error message doesn't mention anything like that.

**Comment by Byron** [comment]
As a workaround, by now there is the alternative `Git executable` method to push and fetch remote repositories. If Git can do it, so now can GitButler.

<img width="623" alt="Screenshot 2024-04-22 at 18 46 41" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/6d31b60d-09ed-42ff-bcf5-769f26cb24a1">

Does that work for you?

(*It's likely that auto-detection also works now as it will try to use the Git executable and succeed*)

**Comment by SohamGhugare** [comment]
Yep, auto detect works fine in the newer versions. However there's another issue now, since they added an explicit screen for choosing your method of authentication, whenever I choose a repo which has a remote linked to an organization, there's a slight chance that it will show `Error: Timed Out` and then persist until I redo the whole procedure.

**Comment by SohamGhugare** [comment]
Do note that this only happens with organization repos, I haven't faced this issue with any of my private or non-organizational repos yet.

**Comment by krlvi** [comment]
Hey, thanks for getting back with this updated feedback. Since the main issue for this is resolved, I will now close this. Feel free to open a new github issue if you hit anything else that is a problem
