### ISSUE TITLE
[Bug] Unsupported CSS props on older browser versions

### ISSUE THREAD

**Issue by lbittner-pdftron** [gitbutlerapp/gitbutler#2878]
On GitButler 0.10.14 (Apple Silicon), there seems to be some buttons visible that are supposed to be hidden.

![image](https://github.com/gitbutlerapp/gitbutler/assets/30271920/489549f9-0d52-472c-9799-33e875ad73be).

Additionally, I cannot drag and drop files between virtual branches, which makes the product unusable. Not sure if this is related to those buttons. Let me know if you would prefer a different issue for this bug.

![GitButler_Dragging](https://github.com/gitbutlerapp/gitbutler/assets/30271920/d273930d-1d46-4b81-833c-19f158432f55)

I'm very excited to be able to use this product and recommend it to my team!

**Comment by Jollywatt** [comment]
Also seeing this on GitButler 0.10.16 for Intel macOS 10.15.7 and 10.15.6.

**Comment by Jollywatt** [comment]
Just adding to this, I am experiencing this on macOS 10.15.6 and 10.15.7. The interface almost works, but certain buttons and dragging components don't work.

<img width="1186" alt="Screen Shot 2024-04-16 at 11 40 12 AM" src="https://github.com/gitbutlerapp/gitbutler/assets/24970860/9fd3be5f-a658-4ae3-b928-962958e2af2f">

**Comment by PavelLaptev** [comment]
@Jollywatt thanks for the screenshot. Oh my god, some styles are indeed broken.
I think I know the reason. Looks like this version of Safari `15.6.1` simply don't support CSS props we're using, like e.g. `color-mix` function that was included only in `16.6.1`.
I'll check which props we can replace and update to work with more versions, but this probably will take some time. Let's keep this open until we have any updates or decisions on this.

**Comment by krlvi** [comment]
Hey @lbittner-pdftron, @Jollywatt - i think we have made quite a few fixes in the UI department over the past couple of months, is this still an issue with the more recent releases of the app?

**Comment by ndom91** [comment]
These issues seem to stem from the older version of Mac OS you're using. Unfortunately we only support Mac OS 13.0+ (12.6 _might_ work) at the moment.

Basically you'll need Safari 16.0 at minimum, see support chart here: https://tauri.app/v1/references/webview-versions/#webkit-versions-in-safari

**Comment by krlvi** [comment]
Closing this one since we havent heard back in a while. Feel free to open a new issue if anything else arises
