### ISSUE TITLE
Dont use gitbutler if you've submodules. Breaks everything.

### ISSUE THREAD

**Issue by PierreLeGuen** [gitbutlerapp/gitbutler#2891]

**Comment by krlvi** [comment]
hey, thanks for reporting this, im sorry for the trouble. I am gonna test this out, and can at minimum make the tool reject repos with submodules during the initial setup

**Comment by PierreLeGuen** [comment]
Thanks that would be great, it really messed up my submodule. Resulting in the deletion of its content, thankfully I didn't have any local changes.
