### ISSUE TITLE
Discard new file should delete it

### ISSUE THREAD

**Issue by schacon** [gitbutlerapp/gitbutler#2894]
When discarding a new file, the file contents are cleared but the file is not deleted.

**Comment by Pranav2612000** [comment]
Makes sense @schacon .
I'll like to work on it.

**Comment by Pranav2612000** [comment]
On a side note, should the tooltip text say `Discard Changes` instead of `Discard file` for existing files? `Discard file` should only be used for newly created files. Thoughts?

**Comment by mtsgrd** [comment]
> should the tooltip text say Discard Changes instead of Discard file

Yes, and that's the same language used in vs code regardless if new file or old. Fixed here: #2993

**Comment by schacon** [comment]
This should be fixed in https://github.com/gitbutlerapp/gitbutler/pull/2946
