### ISSUE TITLE
Improve error messaging when repo directory is deleted

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2898]
https://discord.com/channels/1060193121130000425/1206670506271707156/1210892156047458344

hazrpg wrote:
>I've got a new bug for you - if the directory for a repo is deleted you get a generic error. Obviously the error is clear enough but its not user-friendly. It might be worth handling this.
>
>This could be a discussion though, because: should it just say that the repo is missing/deleted/gone; Or should it handle it and remove it automatically but give you a heads up about it.
>
>![image](https://github.com/gitbutlerapp/gitbutler/assets/1300356/f0b796e0-83ba-481d-a8a7-688a72f9c305)

**Comment by krlvi** [comment]
fixed
