### ISSUE TITLE
Build with stable Rust

### ISSUE THREAD

**Issue by jirutka** [gitbutlerapp/gitbutler#2921]
Is it possible to build gitbutler with stable Rust, i.e. without nightly features?

**Comment by Qix-** [comment]
Not really, no - we have explicitly turned on unstable, and we're gauging which unstable features to bring in that we're willing to babysit as they stabilize.

Is there an issue you're facing with the unstable toolchain?

**Comment by jirutka** [comment]
This basically disqualifies gitbutler from being packaged in Linux distributions. Alpine Linux in my case, but this is basically true of all of the distros.

**Comment by Qix-** [comment]
Is there documentation for that? That surprises me given that a lot of things are on the unstable branch and Rust has carefully designed the unstable features mechanism to assist with the evolution and caretaking of those features.

**Comment by Qix-** [comment]
Going to close this for now - it's not really something I'm interested in supporting as we use a number of unstable features and know that it requires some potential maintenance upkeep. I also don't really understand why it's a problem for any particular distribution and haven't heard back in a while.

Thanks for the report, however!

**Comment by jirutka** [comment]
> Is there documentation for that?

We don’t have it in a written form in Alpine Linux. The rule is that all rust packages in the main and community repos must be built using our packaged rustc, which is obviously stable rustc. The use of rustup is prohibited.

> That surprises me given that a lot of things are on the unstable branch and Rust has carefully designed the unstable features mechanism to assist with the evolution and caretaking of those features.

Does it really surprise you that distros don’t build packages with **unstable** (nightly) compilers?

**Comment by Qix-** [comment]
I think I've said my piece here. We have unstable features enabled in some places and that isn't changing anytime soon. Happy to revisit this when those features are stabilized.

Thanks for weighing in.
