### ISSUE TITLE
Broken Instagram link in README

### ISSUE THREAD

**Issue by alabhyajindal** [gitbutlerapp/gitbutler#2922]
The [Instagram link](https://www.instagram.com/gitbutlerapp) in the README is broken.

![image](https://uploads.linear.app/68aff581-b3ce-490e-a760-537f27ff0cad/c9abc33d-03ed-4c0d-bd0d-c4e148723203/fcccde63-d657-42e4-ab0b-5d1222a49d1b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY4YWZmNTgxLWIzY2UtNDkwZS1hNzYwLTUzN2YyN2ZmMGNhZC9jOWFiYzMzZC0wM2VkLTRjMGQtYmQwZC1jNGUxNDg3MjMyMDMvZmNjY2RlNjMtZDY1Ny00MmU0LWFiMGItNWQxMjIyYTQ5ZDFiIiwiaWF0IjoxNzA5MTEyMDIxLCJleHAiOjMzMjc5NjcyMDIxfQ.tnuSQS_NQOH_80a580azidpLlIcLO51RIAPlCuGdLlU)

**Comment by mtsgrd** [comment]
Thanks for reporting this! Fixed by #2960.
