### ISSUE TITLE
Support multiple remotes

### ISSUE THREAD

**Issue by aablsk** [gitbutlerapp/gitbutler#2923]
I'd love to be able to use Gitbutler with multiple remotes. Especially when contributing to open source repositories, being able to decide where to push updates and easily being able to decide where to get updates from is crucial to my workflow.

**Comment by krlvi** [comment]
Since Scott's PR https://github.com/gitbutlerapp/gitbutler/pull/3677 this is now supported. Perhaps the UX of it is something we can iterate on, but im gonna close this issue as completed for now. Please keep the feedback coming and feel free to create other github issues with suggestions or bugs
