### ISSUE TITLE
Button for setting up GitHub integration disappears

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2927]
![image](https://github.com/gitbutlerapp/gitbutler/assets/4030927/f2a302fe-fe91-48bf-aa89-955bbf6f61a4)

seeing some visual bugs where hovering buttons/inputs (like the "Authenticate" button in the screenshot above) makes the input disappear. this is on the apple silicon install.

https://discord.com/channels/1060193121130000425/1073202153163857920/1211738607849705524

**Comment by mtsgrd** [comment]
@PavelLaptev could you have a look to see if you spot anything wrong with this button?

**Comment by PavelLaptev** [comment]
@mtsgrd sure

**Comment by PavelLaptev** [comment]
Should be fixed.
