### ISSUE TITLE
Document the differences to `git worktree`

### ISSUE THREAD

**Issue by oliv3r** [gitbutlerapp/gitbutler#2935]
What a great product. It's really nice to see a new and modern GUI client for Linux.

I am wondering however, or rather, what is missing in the README, is how gitbutler is different from `git worktree`, other then adding a nice GUI and some nice ways of working to it? Doesn't `git worktree` do exactly the same? Maybe have a nice comparison table in the main readme, helping users figure out what gitbutler is. E.g.

| feature | git-cli | gitk | git ...|
|------------|----------|-------|--------|
| virtual branch | git worktree | N/A | N/A |

P.S. I'm even more curious now as to why a whole new technical solution was developed (*GitButler keeps track of uncommitted changes in a layer on top of Git.*). How does this differ from `git worktree`'s is something that could deserve some lines too, which makes (*How do GB's virtual branches differ from Git branches*) sound a bit weird, as it seems to ignore the fact that `git worktree`'s exist (unless they are fundamentally different, not just a different technical solution of course).

@schacon Thanks for your fun to watch FOSDEM24 presentation, but could it be your nerd-state has lingered and that this is a feature you where unaware of? :stuck_out_tongue_closed_eyes: 
Regardless, I loved your talk and have incorporated new things into my [gitconfig](https://gitlab.com/olliver/dotfiles/-/blob/master/.config/git/config?ref_type=heads) thanks to you!

**Comment by schacon** [comment]
Hey @oliv3r. They are fundamentally different.

Worktrees allow you to essentially have multiple checkouts of a project as a minor convenience. It is not much different from just cloning a repository multiple times and checking out different branches on each clone. There is no interaction between the branches or checkouts.

GitButler lets you work on multiple branches at the same time _in the same working directory_, which is a very different concept. Not only is it in many cases a faster workflow, it's also much easier to use an editor (opening different editor instances for each worktree is not always a nice experience), and it also ensures that your branches will merge cleanly, which worktrees don't do.

**Comment by oliv3r** [comment]
> Hey @oliv3r. They are fundamentally different.
> 
> Worktrees allow you to essentially have multiple checkouts of a project as a minor convenience. It is not much different from just cloning a repository multiple times and checking out different branches on each clone. There is no interaction between the branches or checkouts.

Hmm, that's not how they work afaik. You checkout multiple _branches_ to different locations. What I tend to do, for serious projects I organize myself when not lazy, is clone a bare repo, and check out master as a worktree. Then when working on stuff, instead of `git branch` I use `git worktree --branch`.

```
project
├── .git (bare clone! of the repo)
├── master (worktree of master)
└── feature1 (worktree of branch feature1)
```

because these are branches, and not clones, the storage requirements are minimal. Further more, I can easily cherry-pick between worktree's (as they are just branches of course).

Unstaged/Uncommitted files, are just copies of files naturally, so can be just copy/pasted.

> 
> GitButler lets you work on multiple branches at the same time _in the same working directory_, which is a very different concept.

Granted this is, a _in my personal opinion_, a minor difference really, and whether you organize yourself on the filesystem or in a GUI is small. What I do see as a great improvement, I can do `git add --patch (but only graphically of course) and select to which branch/worktree to commit things too.

This does make certain workflows easier, as it avoids `git commit 'feature1`, oh this stuff should really be its own branch, `git commit feature2`, and then cherry-pick feature2 onto a new branch, add worktree, drop feature2 from branch1. (or, have a dev branch, do all your commits, and cherry-pick into individual branches). 

BUT! When organizing things, especially (in parallel on the CLI), worktrees are 'better' as they give a filesystem overview, of your virtual tree's.

I think 'under wraps' git butler could work and use worktrees and still achieve the _same_ effect, having the best of **both** worlds simultaneously :)

> Not only is it in many cases a faster workflow, it's also much easier to use an editor (opening different editor instances for each worktree is not always a nice experience),

I suppose it depends on how you are used to working. If you keep hacking on the same branch, and want to split things off into separate pushes/branches, possibly. But you also have to deal with merges that can go bad, because of inter dependencies.

> and it also ensures that your branches will merge cleanly, which worktrees don't do.

This is a bold statement :p I'll have to experience this part, as if patches start to depend on each other, there's no way you can guarantee this?


Still, I think my issue is still valid, these 'fundamental' differences should be documented on the main page. Because as an outsider, I look at the project, think 'meh, it's just a GUI around worktrees' (which imo it should be as I mentioned above :p)

**Comment by oliv3r** [comment]
> I want to help with this, but it seems like we both understand how both tools work and so I'm not sure what the request is. I can put a "how is this different from worktrees"

Well I think this mostly relates to unawareness. I've introduced worktree's several times, and after people understanding, they where flabergasted and supprised how easy and awesome they where.

I think this goes right with your presentation :) 'Did you know ...' and 'jaw drop'

As for taking up README space, I understand it's also a conflict of (business) interest. Potential users might avoid your product if they learn worktree's solve their problem. So not wanting to compare your product to others is a fair choice of course, it is your business after all.

>  but honestly there aren't that many people who use them as a percentage of git users, so I don't think it's worth taking up README space with a relative edge case.

What data do you base this statement on? GitHub could not possibly know this, as this is a purely local feature. I'll admit, not many people know about this feature I'm sure. Sadly, you already had your talk; would have made a great addition :D

I personally, find it an amazing feature and a huge boost to productivity when working with several branches. But I guess you would know too, as you (virtually) base your product around the same concept :)

> > I think 'under wraps' git butler could work and use worktrees and still achieve the _same_ effect, having the best of **both** worlds simultaneously :)
> 
> This is not true for how GitButler works in my opinion. You can find the differences relatively unimportant to you, but these approaches are fairly objectively different approaches. Having a single working directory where you can modify multiple applied branches at the same time is a very different solution to branch work than having one checkout per branch.

I suppose, I guess I don't know your workflow where you often have to deal with this. I work on multiple FOSS projects from time to time (often for private and work reasons), Linux, OpenWRT, U-Boot, busbox and have to switch between many branches many of times. Work on a feature here, find out this should be its own MR etc, having to switch to someone else's branch to test/review something. I found worktree's invaluable because I also needed to actually compile stuff, sometimes make some suggestive edits (which then of course go into a text field in a MR). And while one or even two worktree's are being compiled, I'm looking at a third worktree. I suppose gitbutler doesn't really let you do that, because it's 'all virtual and only in the client'. 

But I understand that this is derailing the discussion significantly, and I should have attended FOSDEM and talked this over some beers :p

> > and it also ensures that your branches will merge cleanly, which worktrees don't do.
> 
> This is not a bold statement, it's just a fact. We're taking work that is in a single directory and then extracting parts of it logically into multiple branches (yes, similar in a way to `add -p`). But since they exist in a single working directory before the extraction, that _guarantees_ that if you later merge those extracted branches together, the logical result will necessarily be the initial state of the working directory. In essence, you start with the merge product and then extract the branch trees. They will by definition always merge cleanly with each other.

I've had branches (single branches) where I had 200 commits, where I was like 'ok commits 4 - 6 and 9 would need to go into MR1, and commits 11 - 45 are their own MR2, etc etc. I'd pulled them out into their own branches, so that I could offer them as merge requests individually, which required rebases to ensure they'd apply cleanly to master. Those changes would only ever get merged back together via multiple upstream merge requests. In these cases, there's always very often merge conflicts etc. I'll give it a try sometime (i've already installed it :p) to see if it works.

I am really trying to understand and appreciate git-butler, as I think the high-level idea of it makes a lot of sense. I'm just not sure if it applies to any of my workflows.

> Furthermore, patches don't matter. You can commit whatever hunks you want, but during a merge it will only do a 3-way tree merge, meaning your branch heads and the base. There is no such thing as patch dependencies that can mess things up. Even if you rebased them, you could do it from either branch in either order and there is no way for there to be conflicts (again, because you started from what is logically a merge result).

I'm curious indeed to try this out!
>
> Worktrees don't know about each other from a practical standpoint (yes, there is a shared odb, so you can cherry pick or whatever) so you can very easily change the same part of the same file in two worktrees and create future merge conflicts that you're unaware of. GitButler cannot do this. You can't edit the same part of a file and commit conflicting changes to two applied virtual branches.

That's a nice advantage for sure!


> Anyhow, I feel like we're going to end up in a bit of an "agree to disagree" state. What I will do (and have been planning for a few weeks now) is write up a `git worktree` blog post and compare/contrast a bit there, but I don't think it's enough of a widely used tool to take up README space with it.

I think that's a fair compromise. I don't think we are in a 'agree to disagree' state at all :) just exploring and elaborating design choices.

I just find it nice, if projects list alternatives and explain how their product is superior :)

> 
> I'll close this, but I'll update it when the blog post is out.
> 
> Thanks!

I think that's a good idea, and I really realy like/appreciate the idea of a blog post!

**Comment by oliv3r** [comment]
@schacon thanks for the blog post. I think it was useful and featured on hackernews :)
