### ISSUE TITLE
Default context menu hides the other on Fedora/AppImage

### ISSUE THREAD

**Issue by lens0021** [gitbutlerapp/gitbutler#2948]
In the following video, you can see that "Discard" button is not shown after the click.

[Screencast from 2024-02-29 23-06-58.webm](https://github.com/gitbutlerapp/gitbutler/assets/28209361/551f1f7a-882a-4634-9378-a9b5fa5f0ee0)

**Comment by mtsgrd** [comment]
Thanks for reporting this! Will be in the next release.
