### ISSUE TITLE
Add the ability to "copy path to file" and "open in VSCode" on file right click

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#2950]

**Comment by Pranav2612000** [comment]
Does this look good?
PR coming right up

<img width="488" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/20909078/ccd54592-f3fc-40c4-96c2-8a8e22c3906a">

**Comment by Hainesy** [comment]
I'm using Cursor rather than VSCode. Can we make this configurable?
