### ISSUE TITLE
Right click on changed file opens up two menus.

### ISSUE THREAD

**Issue by fgLouro** [gitbutlerapp/gitbutler#2953]
When right clicking on a file with changes to discard it, another menu opens up on top of it. 

<img width="173" alt="Screenshot 2024-02-29 at 22 48 35" src="https://github.com/gitbutlerapp/gitbutler/assets/3598613/7178cea1-21a7-42d4-870a-13ef3c707524">

**Comment by mtsgrd** [comment]
Thanks for reporting this. 🙏
