### ISSUE TITLE
Git push failed with 'no elements in sequence' message

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2955]
> Taking the app for a spin and trying to do a push for a virtual branch with some trivial changes I get a "Git push failed" withe the error "no elements in sequence" 🤔
>
> That said, the push did made it to the Github repo.

via: jfmontesdeoca

[https://discord.com/channels/1060193121130000425/1073202153163857920/1212891220200652860](https://discord.com/channels/1060193121130000425/1073202153163857920/1212891220200652860)

![image](https://uploads.linear.app/68aff581-b3ce-490e-a760-537f27ff0cad/4662df85-ffd8-4b40-9c71-da7b39a984b3/f3807687-ca4b-49e4-b6d3-878244d9cd3b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzY4YWZmNTgxLWIzY2UtNDkwZS1hNzYwLTUzN2YyN2ZmMGNhZC80NjYyZGY4NS1mZmQ4LTRiNDAtOWM3MS1kYTdiMzlhOTg0YjMvZjM4MDc2ODctY2E0Yi00OWU0LWI2ZDMtODc4MjQ0ZDljZDNiIiwiaWF0IjoxNzA5ODkzMzYwLCJleHAiOjMzMjgwNDUzMzYwfQ.KDiP6sYkt7B7terJhUVi65Rn9rZwSOsKdcXwlWI4P9E)

**Comment by Byron** [comment]
Is this still an issue for you in the latest Version 0.11.3 (20240419.070253)? Thanks for your help.

**Comment by mtsgrd** [comment]
Closing this since this is an `rxjs` issue and we have completely removed that.
