### ISSUE TITLE
Allow folders in lanes' tree view to be draggable between lanes

### ISSUE THREAD

**Issue by Qix-** [gitbutlerapp/gitbutler#2967]
Title. Right now the tree view within lanes doesn't support dragging between vbranches.
<img width="381" alt="grafik" src="https://github.com/gitbutlerapp/gitbutler/assets/885648/0c570bfe-95cb-450f-b246-4be5ca0d6433">

**Comment by PavelLaptev** [comment]
Since we drop the tree view, I'll close this ticket. The files design will be a bit different from what we have now.
