### ISSUE TITLE
Auto-generated branch names capitalized inconsistently when creating a draft PR

### ISSUE THREAD

**Issue by gitbutler-client** [gitbutlerapp/gitbutler#2979]
> Got a branch, auto named Update something, and the auto names branch name i see is update-something. When i press create draft pr, the branch on Github is "Update-something". It looks like it auto re-generates the branch name but does not lowercase it
>
>via: @r0derik

https://discord.com/channels/1060193121130000425/1073202153163857920/1213123542019743774

**Comment by Byron** [comment]
I think this is certainly fixed by now, there have been a lot of changes in that regard.
