### ISSUE TITLE
Can't re select my base branch

### ISSUE THREAD

**Issue by PeterChen1997** [gitbutlerapp/gitbutler#3003]
Our dev branch need to be the base branch. That's more practical. Now I cannot change the select. And I can't reImport the repo...

**Comment by LeoCaprile** [comment]
You're right, you can't reselect your main target trunk, that could be a good feature.

**Comment by LeoCaprile** [comment]
There's already an open issue on this feature request, see #2507.

**Comment by PeterChen1997** [comment]
Oh, that's great.
