### ISSUE TITLE
get Windows certs and stuff

### ISSUE THREAD

**Issue by schacon** [gitbutlerapp/gitbutler#3007]
To get real Windows builds working

**Comment by Byron** [comment]
Closing, as Windows builds are [now available](https://gitbutler.com) 🎉.


<img width="672" alt="Screenshot 2024-04-22 at 20 39 21" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/62d8b8fd-7a97-4e66-9f53-6d4376b8cc8d">
