### ISSUE TITLE
Custom theming support

### ISSUE THREAD

**Issue by PavelLaptev** [gitbutlerapp/gitbutler#3009]
Right now, GitButler supports only two themes — **dark** and **light**.
It would be nice to support custom themes, e.g. support more presets or allow making fully custom via config.

<img width="609" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/6f0dd78b-f9a8-4539-aec4-ae7aa8429a33">

**Comment by Qix-** [comment]
If we implement #2932 then this should be a pretty trivial shuttling of information between that and the frontend. @PavelLaptev what do you think about having a third "Appearance" selection (from the screenshot in the OP) that is shown if you have a `[theme]` section in the config file?

We could have a `base` field that indicates if the CSS var overrides are based on the dark/light theme, and then the rest of the fields would be CSS vars we whitelist, shuttle that down to the frontend via a function/event (we can fswatch it for changes, too). Then the frontend just calls `whatever.style.setProperty(`--${varName}`, varValue)`.

**Comment by PavelLaptev** [comment]
@Qix- yes, that's should work 🙂
