### ISSUE TITLE
Gitbutler shows "Force push to remote" for local commits that have already been pushed to remote

### ISSUE THREAD

**Issue by ahmedmahmud** [gitbutlerapp/gitbutler#3020]
I created a virtual branch using gitbutler adding and pushing all my changes through gitbutler, the next day now it shows all my changes in the "Local" tab and at the bottom of Local saying "Force push to remote" when my remote branch has all these changes in Local?
<img width="502" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/19238998/3c611c82-35a4-4f42-a662-7ecd6add2a54">
<img width="493" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/19238998/985268dc-d3af-45d6-9027-f1dc1f9f07da">
<img width="620" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/19238998/3d71e4c4-0ed8-428d-811a-d0b2fd30b133">
I'm not sure in what case this happened? I'm the only one on the `dashboard` branch in question though `main` was pushed to and I had a PR open from `dashboard` to `main` if that helps at all. This happened once before as well in which case I did the force push to remote

**Comment by eabrouwer3** [comment]
I had a similar issue. Found out it was because gitbutler keeps your work in sync with `main` all the time anyways. So because I hit the "Update Branch" button on my PR, the changes were in both the local and remote copies. So a force push wasn't actually an issue.

**Comment by ahmedmahmud** [comment]
Ah so it was a me issue, I wasn't using it fully right then. Thanks for the info :)
