### ISSUE TITLE
 File preview issue when dragging in tree mode

### ISSUE THREAD

**Issue by PavelLaptev** [gitbutlerapp/gitbutler#3029]
When dragging in the list mode, I see the file preview, but in tree mode, it shows the 'workspace' button from the sidebar.

https://github.com/gitbutlerapp/gitbutler/assets/18498712/cf5fd115-34fa-437a-b090-611a60e27f9b

**Comment by mtsgrd** [comment]
Thanks, fix incoming.

**Comment by PavelLaptev** [comment]
@mtsgrd thank you! 🙂
