### ISSUE TITLE
Create a toast informing the developer when a project skips processing a large file

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#3033]
Related to to [https://github.com/gitbutlerapp/gitbutler/issues/2956](https://github.com/gitbutlerapp/gitbutler/issues/2956)

**Comment by mtsgrd** [comment]
Thanks. Could you double check why the `skipped_files` property is snake cased rather than camel? Looks to me like other responses have casing converted.
<img width="297" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/1300356/43f71061-ad6d-4872-9460-6a8c8e5f4f3d">

**Comment by krlvi** [comment]
> Thanks. Could you double check why the `skipped_files` property is snake cased rather than camel? Looks to me like other responses have casing converted.
> 
> <img alt="image" width="297" src="https://private-user-images.githubusercontent.com/1300356/310301849-43f71061-ad6d-4872-9460-6a8c8e5f4f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjYyNjcsIm5iZiI6MTcxMDE2NTk2NywicGF0aCI6Ii8xMzAwMzU2LzMxMDMwMTg0OS00M2Y3MTA2MS1hZDZkLTQ4NzItOTQ2MC02YThjOGU1ZjRmM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMTQwNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFkMzViNWM2ZjI2ZGMzY2RlZjQwNjVjZWY4MTY4MDU1MjlkZjBhYzMwZWJjYTM0Mzg0ZjY2ZjI1N2RmMjcwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FpDCZKgxbXmqPSPBTNdyOXbFugoQvejRTHKKWQX13ZQ">

there was a missing #[serde(rename_all = "camelCase")], should be fixed now
