### ISSUE TITLE
Improve dev ex for forked repos

### ISSUE THREAD

**Issue by wesharper** [gitbutlerapp/gitbutler#3061]
I am a regular contributor to a handful of open source packages. However, I'm not an official maintainer. Because of this, I need to create a fork and contribute PRs to the source repos from my fork.

Ideally, I could set my trunk to `upstream/main` and still push to `origin/main`. However, when my trunk is set to upstream, I get authentication errors when I push.

Another preferred approach would be to add a separate sync feature that automatically syncs the `upstream/main` branch with my trunk similar to the github UI.

Unfortunately, I can't use either approach, so my current workflow is to set the trunk to `origin/main` and manually sync either using the github UI or the command line. It's not the biggest deal, but it would be nice if gitbutler could recognize that there are remotes named `origin` and `upstream` and provide either sensible defaults or configurable behavior for managing and syncing remotes.

**Comment by Byron** [comment]
Thanks for sharing! 

*(#2923 also talks about this as supporting multiple remotes)*
