### ISSUE TITLE
Support gitattributes

### ISSUE THREAD

**Issue by schacon** [gitbutlerapp/gitbutler#3065]
For example, in order to see a diff of a [bun lockfile](https://bun.sh/docs/install/lockfile), we need a diff driver.

**Comment by navtoj** [comment]
Why is this feature not planned?

**Comment by Byron** [comment]
When the `gitoxide` label is visible, it's implicitly planned, but I added the `planned` label as well for clarity. For context, `planned` means it's definitely something that will be worked on eventually.
