### ISSUE TITLE
Branch Filter checkboxes broken in latest version (MacOS)

### ISSUE THREAD

**Issue by mltsy** [gitbutlerapp/gitbutler#3080]
The branch filter checkboxes (pictured below) have stopped checking and unchecking in the latest update.  Now when I click them, they briefly uncheck then check again when I release the mouse button.  If I click then drag the mouse away so there's no mouseUp event, they stay toggled.

<img width="333" alt="Screenshot 2024-03-08 at 3 18 28 PM" src="https://github.com/gitbutlerapp/gitbutler/assets/248385/589a7eca-9472-4801-a961-3eba76f19624">

**Comment by mtsgrd** [comment]
Hey sorry about that, I broke that by accident. Fix has landed but not yet release: https://github.com/gitbutlerapp/gitbutler/pull/3073

**Comment by mltsy** [comment]
It's fixed! 😄  Thank you.
