### ISSUE TITLE
Show file size for binary content

### ISSUE THREAD

**Issue by mtsgrd** [gitbutlerapp/gitbutler#3093]
It feels like we could show more information about binary files in this UI. Any thoughts?
<img width="1370" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/1300356/5eaf2589-2ae6-4bca-b3e4-6d328b56d96f">

**Comment by hrshkshri** [comment]
Hey @Byron , @mtsgrd  let me know if i can take this 

Thanks

**Comment by Byron** [comment]
Thanks for offering, go for it :)!

I recommend bringing a draft PR up early so it can be linked to this issue, while allowing for early feedback or Q&A directly on the code.
