### ISSUE TITLE
Feature: Stacked vbranches

### ISSUE THREAD

**Issue by Caleb-T-Owens** [gitbutlerapp/gitbutler#3104]
Just opening this to track the potential feature of stacked vbranches

From Kiril: What i'd like for the tool to do is to have the ability to express lanes/vbranches that are dependent on other lanes (stacked). But there's still some work to get it there

**Comment by mtsgrd** [comment]
Closing as duplicate of #3031.

**Comment by krlvi** [comment]
i think this is indeed a dupe of https://github.com/gitbutlerapp/gitbutler/issues/3031, gonna close it
