### ISSUE TITLE
Feature request: make the branch name 100% width

### ISSUE THREAD

**Issue by benjick** [gitbutlerapp/gitbutler#3105]
<img width="381" alt="Screenshot 2024-03-11 at 13 03 56" src="https://github.com/gitbutlerapp/gitbutler/assets/430872/aa1b3696-49ec-420a-ac40-9d94e57e9fd1">

The smallest thing, but it would be nice if this clickable area with the input went 100% of the width, I keep clicking outside of it

**Comment by mtsgrd** [comment]
@PavelLaptev what was the original reason for this? I have a vague feeling we wanted to make the draggable area larger, but now we've restricted that to the handle on the right.

**Comment by PavelLaptev** [comment]
The initial idea was to limit the editable input area based on text size to avoid accidental clicks on empty spaces. Let me check how I can improve this one 🙂
