### ISSUE TITLE
GB can create a branch called '-1' that will cause all github actions to fail

### ISSUE THREAD

**Issue by NigelBreslaw** [gitbutlerapp/gitbutler#3114]
I've seen this twice now, but don't know how to reproduce it. Under certain conditions Gitbutler is auto naming the branch to '-1'. This is a valid branch name for a PR. But github actions will start to fail that the standard 'checkout' action is incompatible with that branch name.

**Comment by Qix-** [comment]
If the cause is what I think it is, this should be fixed. Can you double check?

**Comment by NigelBreslaw** [comment]
I've not seen this since you mentioned it's fixed. Feel free to close this issue.

**Comment by Qix-** [comment]
Sounds good, let me know here if it shows up again. :)
