### ISSUE TITLE
Need proxy

### ISSUE THREAD

**Issue by rea1shane** [gitbutlerapp/gitbutler#3119]
I use a proxy client to access GitHub, but gitbulter doesn't seem to be using the system proxy.

<img width="564" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/93363751/55ab7026-130f-4dfd-b290-29a8112ea010">

**Comment by mtsgrd** [comment]
We use libgit2 and unfortunately this is a know issue: https://github.com/libgit2/libgit2/issues/5650#issuecomment-1627580077

I believe we're hoping to move over to [gitoxide](https://github.com/Byron/gitoxide) in the future, but we haven't established a timeline yet.

**Comment by krlvi** [comment]
Hey @rea1shane! The latest release of the app (0.10.27+) supports a fork-exec flow for fetching & pushing and I think that will work for your use case. Try it out whenever you have time and let me know it if helps. Here's how to set it up:
<img width="1001" alt="Screenshot 2024-03-23 at 22 10 17" src="https://github.com/gitbutlerapp/gitbutler/assets/4030927/1321f2c2-3c11-4dae-90bb-1b5b6f044116">

**Comment by Byron** [comment]
Indeed, `gitoxide` does support HTTP proxies if these are configured in Git and the `curl` backend (the default) is used. Meanwhile, I also think that the `Use a Git executable` option should pick up the settings naturally.

**Comment by krlvi** [comment]
Hey @rea1shane, did using the git executable flow help in your case?

**Comment by rea1shane** [comment]
> Hey @rea1shane, did using the git executable flow help in your case?

Hi Kiril, I haven't use this app recently. It seems can resolve my issue. If you tested it works and others don't having same issue, you can close it. Thanks for your works.

**Comment by krlvi** [comment]
Thank you for getting back, and reporting. I am closing this issue now, feel free to open a new one if you come across anything else that is a problem
