### ISSUE TITLE
Window show up at the corner after an update restart on mac 

### ISSUE THREAD

**Issue by NEOLEE98** [gitbutlerapp/gitbutler#3120]
Macos 14.4
Triple Monitor setup, external monitor as main monitor
After the update restart, the window shows only a corner at the corner of the internal display
![Screenshot 2024-02-23 at 9 18 03 AM](https://github.com/gitbutlerapp/gitbutler/assets/8736968/99b3c2bf-6ade-4e04-b741-b305a509daeb)

**Comment by mtsgrd** [comment]
Hmm, iiuc this isn't something we've configured. Any chance you could have a look in the Tauri project to see if this is a known issue? I'd love to see a thread on their side about this, I've also run into issues with the window location not being remembered correctly.

**Comment by NEOLEE98** [comment]
Seems fixed after past few update
