### ISSUE TITLE
Merge/rebase button not working

### ISSUE THREAD

**Issue by KroniK907** [gitbutlerapp/gitbutler#3124]
Have had at least 2 reports of the merge button no longer working.

https://discord.com/channels/1060193121130000425/1206670506271707156/1217142679989911615

https://discord.com/channels/1060193121130000425/1206670506271707156/1217078312145256508

**Comment by krlvi** [comment]
Hey, sorry for the breakage. I must admit, this slipped between the cracks. Taking a look now, I think we should have a patch by tomorrow
