### ISSUE TITLE
AppImage will not launch on my fedoraremix WSL instance

### ISSUE THREAD

**Issue by KroniK907** [gitbutlerapp/gitbutler#3127]
Version 0.10.23 will not launch on my fedoraremix WSL instance and gives me the following error when trying to launch:

```
(git-butler:23444): Gtk-WARNING **: 09:39:08.569: cannot open display: :0
```

However it will launch just fine on my ubuntu WSL instance.

Other apps launch without issue on my fedoraremix instance.

**Comment by mtsgrd** [comment]
Did it work with earlier versions or is this version the first one you try on the feoraremix instance?

**Comment by KroniK907** [comment]
It was working last week without issue but its now broken for any appimage apps. I tried a different appimpage app built with tauri and it does the same thing. However firefox launches just fine, and building the dev works fine too.

**Comment by KroniK907** [comment]
scratch that, after a reboot firefox isnt working either. Looks like my WSL instance is borked.
