### ISSUE TITLE
Tiny layout shifts on hover

### ISSUE THREAD

**Issue by neznayer** [gitbutlerapp/gitbutler#3163]
There are a bunch of small layout shifts on hover on buttons and cards:

https://github.com/gitbutlerapp/gitbutler/assets/55772081/33fbc7dc-6013-4bb2-90d5-c070222b741e

**Comment by neznayer** [comment]
I could take a look on that one!

**Comment by PavelLaptev** [comment]
@neznayer thanks for the report. Looks like missing styles or CSS vars. But I'm wondaring why it's happens

Can you inspect if there are any missing styles or vars on hover?

https://github.com/gitbutlerapp/gitbutler/assets/18498712/5dfa4a7a-5705-4ece-82c6-d4b9c95762ca

**Comment by neznayer** [comment]
> @neznayer thanks for the report. Looks like missing styles or CSS vars. But I'm wondaring why it's happens
> 
> 
> 
> Can you inspect if there are any missing styles or vars on hover?
> 
> 
> 
> https://github.com/gitbutlerapp/gitbutler/assets/18498712/5dfa4a7a-5705-4ece-82c6-d4b9c95762ca
> 
> 
> 
> 

I'll take a look!

**Comment by neznayer** [comment]
> @neznayer thanks for the report. Looks like missing styles or CSS vars. But I'm wondaring why it's happens
> 
> Can you inspect if there are any missing styles or vars on hover?
> 
>  Screen.Recording.2024-03-18.at.16.38.08.mov

I've took a look. 
It seems that `color-mix()` which is used for hovered borders colors, is not supported on my Safari version (16.1). Which is not super old as I believe, MacOS Ventura 13.0.1.

**Comment by PavelLaptev** [comment]
> > @neznayer thanks for the report. Looks like missing styles or CSS vars. But I'm wondaring why it's happens
> > Can you inspect if there are any missing styles or vars on hover?
> > Screen.Recording.2024-03-18.at.16.38.08.mov
> 
> I've took a look. It seems that `color-mix()` which is used for hovered borders colors, is not supported on my Safari version (16.1). Which is not super old as I believe, my os is MacOS Ventura 13.0.1.

@neznayer gotcha, thanks! I removed `color-mix` from the app. There is left only one place left, and I also planning to remove next release. As a temporary solution, I replaced this with OKLCH https://caniuse.com/mdn-css_types_color_oklch

Let me know if you come across this bug again, and I'll reopen this issue.
