### ISSUE TITLE
"Project" -> "Project Settings" switches active project

### ISSUE THREAD

**Issue by sanados** [gitbutlerapp/gitbutler#3184]
## context
When opening GitButler and selecting a different project (than it opened with) and then you click on "Project" -> "Project Settings" it selects the project it was opening when it was started. 

_The project settings link in the bottom bar is working._

## reproduce
[gitbutlerBug.webm](https://github.com/gitbutlerapp/gitbutler/assets/7146844/36209428-582f-481e-9a7d-ea69e95949f9)

**Comment by mtsgrd** [comment]
Thanks for reporting, I will have a look the issue.
