### ISSUE TITLE
SSH private key passphrase stored in plaintext

### ISSUE THREAD

**Issue by DamianZaremba** [gitbutlerapp/gitbutler#3187]
Version: 0.10.24 (20240312.205643)

Similar to #3186 where the passphrase is exposed in logging, after some further poking it appears to also be stored in plain text on disk.

```
$ cat /Users/damian/Library/Application\ Support/com.gitbutler.app/projects.json
[
  {
    "id": "85f8c687-e977-4826-8af5-f716e8520edf",
    "title": "csoffice",
    "description": null,
    "path": "/Users/damian/Projects/xxxx/csoffice",
    "preferred_key": {
      "local": {
        "private_key_path": "~/.ssh/id_ed25519",
        "passphrase": "ssh key passphrase in plain text"
      }
    },
    "ok_with_force_push": true,
    "api": null,
    "gitbutler_data_last_fetch": null,
    "gitbutler_code_push_state": null,
    "project_data_last_fetch": null,
    "omit_certificate_check": null,
    "use_diff_context": true
  }
]
```

This is not really ideal from a security point of view, again support of `ssh-agent` per #2902 would be the ideal solution here.

**Comment by Qix-** [comment]
Hey, thanks for bringing this to our attention. This obviously isn't correct and shouldn't have ever been the case. I've moved this to my top priority and will address it first thing tomorrow morning with the team.

**Comment by krlvi** [comment]
Thank you for reporting this @DamianZaremba. I apologise for this — it is my fault. I did not consider the different threat models that exist on a local desktop environment.

We are fixing this straight away, with the first step of removing the persisting of passphrases — https://github.com/gitbutlerapp/gitbutler/pull/3213 and https://github.com/gitbutlerapp/gitbutler/pull/3214, now merged.

Next up — we are adding a just-in-time prompting for credential, which we aim to release today as well. We will update this thread with the progress on it.

**Comment by Qix-** [comment]
Ref #3222

**Comment by mtsgrd** [comment]
Using git executable for push/pull and being prompted for credentials is working on master now, should be in a release within a day or so.

**Comment by ryanm101** [comment]
While I think it's great that you have taken this seriously.. I think you could have just done the new fix rather than removing the old behaviour first without it, as now i cannot push at all using a key with a passphrase.

**Comment by krlvi** [comment]
> While I think it's great that you have taken this seriously.. I think you could have just done the new fix rather than removing the old behaviour first without it, as now i cannot push at all using a key with a passphrase.

I am sorry for this disruption. We have a working implementation using fork-exec on main, doing some final testing & fixes with the aim to make release later today. As a workaround in the meantime, if you wish to get the previous app version, here are downloads links:
```
OSX arm: https://releases.gitbutler.com/releases/release/0.10.24-718/macos/aarch64/GitButler_0.10.24_aarch64.dmg
OSX intel: https://releases.gitbutler.com/releases/release/0.10.24-718/macos/x86_64/GitButler_0.10.24_x64.dmg
Linux deb: https://releases.gitbutler.com/releases/release/0.10.24-718/linux/x86_64/git-butler_0.10.24_amd64.deb
Linux appimage: https://releases.gitbutler.com/releases/release/0.10.24-718/linux/x86_64/git-butler_0.10.24_amd64.AppImage.tar.gz
```

**Comment by ryanm101** [comment]
Thanks, I had the .24 binary lying about so rolled back. 

Secondly I would like to say great work on this I'm really loving this way of working it fits my work style much better than native git branching, so thank you for doing it. 

Thirdly Bitbucket support would be amazing

**Comment by krlvi** [comment]
Thank you all for your patience! We just made a release `0.10.26` which contains a new flow for pushing and fetching using the git executable on the PATH. To enable that, you can select it from the project settings:
<img width="578" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/4030927/a4c97bcb-ac87-4fa8-9550-fa36c7789e1e">

If the git executable requests credentials, GitButler will prompt for them just-in-time, and will not log or persist them.
While all the other auth options use `libgit2`'s transport, this one uses git (ssh) and therefore will respect any ssh config that is in place.

@DamianZaremba, when you have time, would you be able to test the newest release (`0.10.26`) and verify that:
- After starting the application and opening at least one project, any and all referenced to `"passphrase"` are removed from `/Users/damian/Library/Application\ Support/com.gitbutler.app/projects.json`
- You can configure and use the Git executable flow for fetch and pull

We have tested this on a number of machines on our end but of course I'd like to be sure that this works for you too.

@ryanm101 Thank you for the kind words! If you have as well, feel free to try out the new release and let me know how this goes for you.  I made a separate gh issue https://github.com/gitbutlerapp/gitbutler/issues/3252 for Bitbutcket support.

**Comment by DamianZaremba** [comment]
@krlvi I just tried 0.10.27 and this seems to have done what you described.

This is probably expected behaviour since this issue was around pushing rather than signing, but just to note along the lines of #3311 the commit signing is done using the key configured in settings rather than from the git config, which is what I would naturally expect given the git executable is being used.

Relevant part of `~/.gitconfig`;
```
[gpg]
  format = ssh
[commit]
  gpgsign = true
```

From my side this and #3186 can be closed as completed, unless you have something outstanding for them.

Thanks for the quick response/fix for this issue :)

**Comment by krlvi** [comment]
Thanks once again for reporting and verifying the fix @DamianZaremba. I am closing this as completed and will make a separate ticket for the signing.
