### ISSUE TITLE
The app unable to load branches when switching between projects

### ISSUE THREAD

**Issue by PavelLaptev** [gitbutlerapp/gitbutler#3205]
**Issue:**
On the sidebar there are branches virtual and remote.
For the initial project that was loaded with the app all good, I can click on different branches.
But when I switch to another project, I see the list of the branches but when I click on any the app display it as `not exist` (see video)

<img width="251" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/2a115bfd-7bd3-4de0-80a9-2c1dd9654e7d">

https://github.com/gitbutlerapp/gitbutler/assets/18498712/c665af17-c5eb-46b1-82ce-4ac63744a5f7

**Comment by mtsgrd** [comment]
I'm on it.

**Comment by mtsgrd** [comment]
Fixed here https://github.com/gitbutlerapp/gitbutler/pull/3215
