### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by sidarth-23** [gitbutlerapp/gitbutler#3258]
Version 0.10.26

Drap and drop of files between branches was working fine till 0.10.25. But now I am having to set the default branch for every file to register it to the correct branch. Switching the files is buggy

**Comment by rohitpaulk** [comment]
Running into problems with drag & drop too - some files can be dragged but not others (haven't found a pattern yet). 

@sidarth-23 what's the "set the default branch" workaround you mentioned? Is it to remove the change, change the default branch and then add the change back?

**Comment by sidarth-23** [comment]
> Running into problems with drag & drop too, I'm on 0.10.27 - some files can be dragged but not others (haven't found a pattern yet). 
> 
> @sidarth-23 what's the "set the default branch" workaround you mentioned? Is it to remove the change, change the default branch and then add the change back? 

Yep. That's exactly how I do it when it glitches out

**Comment by mrtcntn** [comment]
I was having the same issue today and got 0.10.28 update. Everything seems fine now.

**Comment by rohitpaulk** [comment]
Same here! Haven't noticed this on 0.10.28 yet.

**Comment by Byron** [comment]
I am glad it seems to work now. Closing based on that, but please feel free to keep commenting or to reopen as needed. *(the current version of GitButler is 0.11.3)*
