### ISSUE TITLE
'Create pull request' should use PR template from Github if present

### ISSUE THREAD

**Issue by Hainesy** [gitbutlerapp/gitbutler#3313]
When creating a pull request, GitButler doesn't use the Github PR template.

**Comment by koppor** [comment]
Background information on PR templates is available at: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository - Unfortunately, there is no screenshot of the user-experience.

What I would expect from gitbutler that it offers "Create PR using a description". On click, there is a popup asking for the description. That is pre-filled with the template. The user can then change it. Either click on button "Create" or the button "Cancel" (to cancel it). -- If possible, the current contents of the text field should be kept if the user comes back to that dialog (for the same virutal branch) at a later point in time after Canceling.

**Comment by ndom91** [comment]
Hey folks, I've put up a [PR](https://github.com/gitbutlerapp/gitbutler/pull/4736) adding this feature. 

I'm merging it now, so it'll be available tomorrow in the [nightly builds](https://app.gitbutler.com/downloads) at the latest.

We'd be happy about any feedback!

**Comment by koppor** [comment]
Does not work in 0.12.21

Path `.github/PULL_REQUEST_TEMPLATE.md` not recognized.

Repository: https://github.com/adr/e-adr

**Comment by ndom91** [comment]
@koppor did you receive any particular error messages? I've been using this with our repository here the last few days and ours is at `.github/PULL_REQUEST_TEMPLATE.md` as well

**Comment by lucastraba** [comment]
I also have this problem. I started using it a week ago, so I don't know if it never worked in my case or it stopped working in a previous version.

![CleanShot 2024-09-10 at 11 27 55](https://github.com/user-attachments/assets/46c15f3b-1505-4287-95c0-693a7ff6d0f6)
![CleanShot 2024-09-10 at 11 27 37](https://github.com/user-attachments/assets/e4e7510c-ab88-4642-a120-1a064a55fd1a)
![CleanShot 2024-09-10 at 11 26 42](https://github.com/user-attachments/assets/033d9912-3d86-4de3-8604-fbc235bea36c)
![CleanShot 2024-09-10 at 11 27 19](https://github.com/user-attachments/assets/93861762-9558-4b1e-976f-dc3c85f306a2)

**Comment by ndom91** [comment]
Hmm interesting. I've been using it successfully for the last few nightlies in our repository, but there's clearly something still wrong. 

I'm actually getting ready to ship a refactor of this feature to offer a dropdown of available pr templates, instead of asking for a path in a text input, [here](). 

I'll post back here once it's available to get your feedback 👌

**Comment by lucastraba** [comment]
@ndom91 Sorry, sorry, sorry, this was 100% my fault. My Org wasn't giving the full OAuth permissions, so GitButler was not able to get it. I granted the permissions and now it works.

Sorry for the confusion!

**Comment by koppor** [comment]
Works in 0.13.0. Follow-up: https://github.com/gitbutlerapp/gitbutler/issues/5096
