### ISSUE TITLE
Broken UI when git folder no longer exists

### ISSUE THREAD

**Issue by nolith** [gitbutlerapp/gitbutler#3330]
Version: Version 0.10.27 (20240321.223823)

Hello, I was testing something with a a repo in `/tmp/`, once I rebooted my mac, gitbutler was failing to find the repo and resulted in a completely broken UI.

<img width="1187" alt="Screenshot 2024-03-26 at 09 08 31" src="https://github.com/gitbutlerapp/gitbutler/assets/78752/a8473f06-b77d-41c2-a5ab-fedb406dd26f">

## Workaround

From the top bar go "Projetc" -> "Project settings", scroll to the bottom and click "Delete project".

**Comment by Byron** [comment]
Thanks for reporting!

I believe as of the latest Version 0.11.3 (20240419.070253) this is fixed - the UI will not get stuck anymore and make it easy to remove the project.
Closing because of it, but please reopen or comment here if this still isn't working for you.
