### ISSUE TITLE
Unexpected behavior of virtual branches that are re-applied after pushing

### ISSUE THREAD

**Issue by wesharper** [gitbutlerapp/gitbutler#3345]
I like to push things semi-regularly just to make sure I have a backup of my work and because I'm really going all-in on GitButler and I have definitely borked some stuff locally trying to do too much.

In the process of pushing, unapplying, re-applying, swapping, etc. I've encountered this issue a handful of times:
![image](https://github.com/gitbutlerapp/gitbutler/assets/13283469/caef1957-2f68-4ab8-adc3-ace3cb74d22f)

A bunch of commits exist locally AND on the remote branch. They are, for all intents and purposes, the exact same commits, but with separate timestamps. If I merge the upstream, I get a bunch of duplicate commits in the history. If I force push, it updates the timestamps for everything.

**Comment by Byron** [comment]
Thanks for reporting!
I'd hope this will get fixed naturally as #3121 gets implemented.

**Comment by vorou** [comment]
hey, is there any workaround for this in the meantime? can I modify my flow somehow so that I don't end up in that state? I don't get why it happens only sometimes (but often)

**Comment by wesharper** [comment]
The new UI definitely makes things more clear. Although I haven't encountered this exact scenario with the new UI active. Will report back if I see improvements/issues.

**Comment by mtsgrd** [comment]
Feel free to re-open this issue if something comes up! Closing for now as it has been addressed in the recent commit list improvements. 🙏
