### ISSUE TITLE
Dark screen with "Something went wrong..." whenever I launch GitButler.

### ISSUE THREAD

**Issue by cowboycodr** [gitbutlerapp/gitbutler#3362]
# Description
No error message pops up. I've tried uninstalling and re-installing (via deleting the application in my applications folder) and nothing has changed.

This happened earlier today when I switched to a different branch which had conflicts with my current environment. I didn't want to deal with the issue in that exact moment, so I closed my Mac, and later returned to this screen.

So far I've not found any way to fix it. As for recreating it, I guess apply a remote branch that conflicts with your current environment (?). 

Any help would be appreciated.

# Image
<img width="841" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/59800761/42649922-fd28-41fa-a5ad-348cfbd1843d">

**Comment by cowboycodr** [comment]
I think it would also be helpful to note that I have restarted my Mac M2 multiple times. Additionally, as I previously mentioned, uninstalled and reinstalled.

I did this via the applications folder, and just left clicked, then move to trash. Is there another way I should be doing this? Just as a quick fix in the meantime.

**Comment by mtsgrd** [comment]
Hey, I'm keen to help and understand what went wrong here so we can prevent it from happening again. Meanwhile, try deleting the [project files](https://docs.gitbutler.com/development/debugging#data-files) located here:  `~/Library/Application\ Support/com.gitbutler.app`

**Comment by mtsgrd** [comment]
@cowboycodr could you confirm if this is still an issue? At the very least there would now be a new error screen displaying the underlying error message.
