### ISSUE TITLE
Repo that had submodules does not work even without them

### ISSUE THREAD

**Issue by nick-delirium** [gitbutlerapp/gitbutler#3363]
In short, our repo had a submodule for some long time (and git butler worked fine all those time), but after some update (I suspect 0.10.27), creating a virtual branch leads to UI freezing completely. 

I removed submodules
<img width="467" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/23126999/cd0aad0f-22de-4acc-9a79-8b13ce1c8e20">

Completely from main branch, then removed butler completely (including app support folder and butler integration branch) and installed it again, but it still insists that it can't open my repo due to mysteries submodules present.

<img width="402" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/23126999/acb296e7-6b74-4c11-a2de-7321067e428f">

Apple silicon, app ver. 0.10.28

**Comment by jokeyrhyme** [comment]
You probably have an old .gitmodules files that you can manually delete

**Comment by nick-delirium** [comment]
@jokeyrhyme indeed I had empty modules file... Well, I suppose the tool itself should not just check for the file existence, but for any contents inside (or at least submodule output?). Removing the file helps, thank you for suggestion :)

**Comment by schacon** [comment]
For the sake of simplicity, I'm going to close this in favor of https://github.com/gitbutlerapp/gitbutler/issues/2665, since that will clearly take care of this too.
