### ISSUE TITLE
When i login in with my google account it direct a page error

### ISSUE THREAD

**Issue by linhaosunny** [gitbutlerapp/gitbutler#3403]
When i login in with my google account it direct a page error, it said Error csrf_detected

**Comment by Byron** [comment]
Thanks for reporting! Is this still an issue for you as of the latest version 0.11.3? If so, could you record the screen or describe how the app is responding? I'd be interested in seeing what the application does if the authentication flow fails, and if that could be improved to be less confusing.

**Comment by Qix-** [comment]
Going to go ahead and close as we haven't heard back and I've personally logged in via Google to test today and everything worked fine.

If this is still an issue for you, please provide some logs and we can reopen it :)
