### ISSUE TITLE
Releases missing notes.

### ISSUE THREAD

**Issue by ryanm101** [gitbutlerapp/gitbutler#3417]
The tags (on github) for release do not include the diff until the most recent release from the last release tag. 

Notes on .29 should be a diff between [release/0.10.28](https://github.com/gitbutlerapp/gitbutler/releases/tag/release%2F0.10.28)..[release/0.10.29](https://github.com/gitbutlerapp/gitbutler/releases/tag/release%2F0.10.29)

instead .29 release notes are just the previous nightly's notes and the other notes from the other nightly's since .28 are not listed.

**Comment by krlvi** [comment]
Hey, thanks for highlighting this. This is more of a process issue than one specific to this release. 

Right now, after testing and validation, I manually compile an easy to read change log from the commits between the two tags and add it to our updater system (this is how the app updater shows a changelog). 

Subsequently I post the same list of changes on discord in the[ #releases channel ](https://discord.com/channels/1060193121130000425/1183737922785116161/1225010084250128416).

Let me see if i can update the releases page on github

**Comment by krlvi** [comment]
i think perhaps the best thing would be if we published releases on github actually...
