### ISSUE TITLE
Work in progress changes & commits get (optionally) imported during project add

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#3420]
We used to have the functionality where during the process of adding a repo, if there was work in progress, it was added as a virtual branch, which no longer works.

Lets bring it back in an optional way. If a developer has selected `origin/main` as their target and they are currently on `foo` with 2 commits and 3 uncommitted changes, present that and ask the developer if they wish to have that added as a virtual branch.

**Comment by Byron** [comment]
Probably related to #3048.
