### ISSUE TITLE
Commits, that have been amended, are not signed with user signature

### ISSUE THREAD

**Issue by jhnns** [gitbutlerapp/gitbutler#3449]
I noticed that commits, that have been amended, are not signed with my signature. I'm not sure if the commits *are* signed, but maybe with a wrong signature. In any case, GitHub shows "Unverified". For regular commits, "Verified" is displayed as expected.

PS: I really enjoy using GitButler so far. Keep up the good work :)

**Comment by Qix-** [comment]
Hey, thanks for reporting. Our signing story right now is a little tattered, I'll be focusing a bit more on this in the coming week(s). Sorry you're facing this.

For the time being, a little bit of a nasty hack to work around this is to check out the virtual branch directly via `refs/gitbutler/<virtual-branch-slug>` and doing a rebase.

**Comment by schacon** [comment]
Related to: https://github.com/gitbutlerapp/gitbutler/issues/3147
