### ISSUE TITLE
Typos and improvement of the file selection

### ISSUE THREAD

**Issue by 2Friendly4You** [gitbutlerapp/gitbutler#3474]
Found two things on "Windows Nightly 0.5.400"

I'm not sure, if it should say OpenAI API, if I select Anthropic? Is that right?
<img width="446" alt="Screenshot 2024-04-08 204117" src="https://github.com/gitbutlerapp/gitbutler/assets/83555863/5fbf4f42-da08-4407-a0b6-8556a2c5b6db">

And one small, unimportant thing:
When selecting a profile picture for the personal profile, it would be practical if the file selection only displayed the supported picture types and not all file types.

**Comment by PavelLaptev** [comment]
@2Friendly4You you're absolutely right 🙂 I fixed the typo and also a few CSS glitches on this page, thank you!

I've looked into the problem with the accept attribute for file uploads. We've been using it, but it seems it doesn't work properly in Tauri. Here is the related issue https://github.com/tauri-apps/tauri/issues/9158. For now, we have to handle this manually. I hope they can fix this soon.
