### ISSUE TITLE
MSI Release - Windows Defender Threat Found

### ISSUE THREAD

**Issue by Polemus** [gitbutlerapp/gitbutler#3484]
I was super stoked to see the MSI Release, unfortunately it says a threat was found.

I'm running windows 11
Downling using Version 123.0.2420.81 (Official build) (64-bit)

![image](https://github.com/gitbutlerapp/gitbutler/assets/112549/9733e4c0-500c-4ee8-9459-e9c4112b3732)

**Comment by Qix-** [comment]
Hi, are you downloading the stable release or the nightly?

**Comment by Polemus** [comment]
> Hi, thanks for reporting :) are you downloading the stable release or the nightly?
> 
> The nightlies are currently unsigned, I'll be setting up signing for them within the week (or next). If it's the stable release, those are signed and (assuming the _Microsoft powers that be_ allow for it) should not trip Windows Defender.

I am downloading it directly from https://gitbutler.com/ the "Windows MSI" link

**Comment by Qix-** [comment]
*sigh*

Great. That's not a good thing. Sorry you're hitting this.

For now the only workaround is to go into windows defender and add an exception for it. Hopefully this gets fixed over time as their heuristics system learns it's not a virus. We've done as much as we can on our side to make Windows Defender happy, unfortunately.

There should be an entry in the Windows Defender panel that shows what was quarantined and to have it listed as an exception. Let me know if that isn't the case.

**Comment by Qix-** [comment]
Curious, can you try downloading it with a non-Edge browser?

**Comment by Polemus** [comment]
> Curious, can you try downloading it with a non-Edge browser?

Latest Chrome does the same.

When looking at virus and threat protection for windows defender, this pops up for a second or 2:

![image](https://github.com/gitbutlerapp/gitbutler/assets/112549/32b83112-f91a-41dc-9767-015fbfef9226)

After which it goes away and shows:

![image](https://github.com/gitbutlerapp/gitbutler/assets/112549/1185d71d-447a-4c52-b51a-d1d66a018be3)

**Comment by Qix-** [comment]
Yeah it's definitely a false positive. Does the actions menu allow you to exclude it?

**Comment by Polemus** [comment]
Yes, i can allow it.

**Comment by schacon** [comment]
Shouldn't this be mitigated with the code signing thing?

**Comment by Qix-** [comment]
It should, yes 🙃

**Comment by Qix-** [comment]
We'll have to start submitting releases to Microsoft via their "upload a sample" UI to get around this, it seems.

I've also put in a support request for them to look into this. Don't hold your breath on that though, Microsoft is famous for not caring about this stuff.

**Comment by schacon** [comment]
OK, this release has had it's detection removed.

![CleanShot 2024-04-11 at 08 28 45@2x](https://github.com/gitbutlerapp/gitbutler/assets/70/976a2674-e873-45ee-acc9-b6a1818bac6a)

Hopefully I don't need to do this for every single release.
