### ISSUE TITLE
Bug: Opening in VSCode doesn't open project

### ISSUE THREAD

**Issue by l-melon** [gitbutlerapp/gitbutler#3503]
### Bug Description:
When attempting to open a project in Visual Studio Code (VSCode) through Gitbutler on Windows, the project does not open as expected. Instead, VSCode launches without the project loaded.
![image](https://github.com/gitbutlerapp/gitbutler/assets/71011125/86b61be9-59e7-4002-9c19-42681f676d9d)

**Comment by mtsgrd** [comment]
Hey, thanks for reporting. Closing as duplicate of #3489, fixed here but not yet released: #3498
