### ISSUE TITLE
Cannot build crates on Windows

### ISSUE THREAD

**Issue by alfawal** [gitbutlerapp/gitbutler#3505]
I cannot build using `cargo build`.

The rust compiler version might be the problem.

OS: Windows 11
Rustc version: `rustc 1.79.0-nightly (88c2f4f5f 2024-04-02)`
Cargo version: `cargo 1.79.0-nightly (a59aba136 2024-03-28)`

Output:
```bash
$ cargo build
warning: skipping duplicate package `app` found at `C:\Users\alfawal\.cargo\git\checkouts\tauri-plugin-context-menu-2c3100763c3e1052\d8dcbcb\examples\vanilla\src-tauri`
   Compiling openssl-sys v0.9.102
   Compiling webview2-com v0.19.1
   Compiling sha2 v0.10.8
   Compiling overload v0.1.1
   Compiling sentry-core v0.32.2
   Compiling http-body v1.0.0
   Compiling nu-ansi-term v0.46.0
   Compiling globset v0.4.14
   Compiling libz-sys v1.1.16
   Compiling windows-sys v0.42.0
   Compiling tauri v1.6.1
   Compiling wry v0.24.7
   Compiling tauri-runtime v0.14.2
   Compiling inout v0.1.3
   Compiling futures-executor v0.3.30
   Compiling dirs-sys-next v0.1.2
   Compiling windows-core v0.52.0
   Compiling winapi v0.2.8
   Compiling dirs-next v2.0.0
   Compiling toml_edit v0.19.15
   Compiling serialize-to-javascript v0.1.1
   Compiling futures v0.3.30
   Compiling windows v0.52.0
   Compiling tauri-runtime-wry v0.14.5
error: failed to run custom build command for `openssl-sys v0.9.102`

Caused by:
  process didn't exit successfully: `C:\Users\alfawal\Documents\git\gitbutler\target\debug\build\openssl-sys-c54a1c21a635df2f\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:/Users/alfawal/Documents/git/gitbutler/target/debug/build/openssl-sys-070fc2a83d882856/out/openssl-build/install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at C:\Users\alfawal\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-300.2.3+3.2.1\src\lib.rs:611:9:



  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=C:/Users/alfawal/Documents/git/gitbutler/target/debug/build/openssl-sys-070fc2a83d882856/out/openssl-build/install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"
      Failed to execute: program not found



  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by alfawal** [comment]
Even if the rust compiler version isn't related to this issue, the required rust version must be specified in the manifest (`Cargo.toml` file).

https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

**Comment by Byron** [comment]
This looks like the OpenSSL build script is failing as `perl` isn't available. 

While it would be possible to use a different HTTP backend in curl, it's unclear how that would work through `git2`. At the latest when `gitoxide` integration lands, it would be possible to build everything without requiring most of the C tooling thanks to a pure Rust build, but it's quite far out still.

Meanwhile, to resolve this, one would have to make sure all the tools are available in the path, like `perl` in this case, and probably more.

**Comment by Byron** [comment]
And finally, if you happen to be on ARM Windows via a Parallels VM on an ARM MacBook, the winning command-line is:

```sh
pnpm tauri dev --features windows --target x86_64-pc-windows-msvc
```

Without specifying the target, the openssl build script *might* think it's on a Unix'y platform and expects `perl` to produce unix paths, which strawberry perl does not.

This made me think it would be best to completely get rid of OpenSSL in favor of Rust alternatives, but even with `gitoxide` most (probably all) SSH implementations still depend on it. 

Building OpenSSL (or running its toolchain) still takes a long time though, let's see if it finishes.

**Comment by Byron** [comment]
It does take a long time, but once over the `perl` and ARM hump, it does work. It's very slow, but I am not entirely surprised given the `ARM MacOS -> ARM Windows -> x86_64 Windows` emulation chain.

<img width="1311" alt="Screenshot 2024-04-26 at 09 19 18" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/8e3012c3-2432-4cc5-9ebc-19b613b26d65">

**Comment by Qix-** [comment]
Hi - sorry if it wasn't obvious but we do have Windows build instructions. Perl indeed needs to be installed due to our dependency on openssl which is a bit dated when it comes to their build configs.

https://github.com/gitbutlerapp/gitbutler/blob/master/DEVELOPMENT.md#building-on-windows

Going to close for now because this isn't an issue with our configs, as much as I'd love for there to be something actionable here (as it is a huge headache, both locally and in CI).
