### ISSUE TITLE
Older local commits keep their "Undo" buttons.

### ISSUE THREAD

**Issue by daniilS** [gitbutlerapp/gitbutler#3525]
When creating a local commit while the "Local" panel is open, the previous local commits keep their "Undo" buttons until the "Local" panel is closed and reopened. Clicking any of these buttons instead undoes the most recent commit.

Conversely, undoing a local commit doesn't add an "Undo" button to the previous local commit until the "Local" panel is closed and reopened.

Example:
![image](https://github.com/gitbutlerapp/gitbutler/assets/6144189/06c9eaea-6472-4c23-897f-3dc18e11c9c1)

**Comment by Qix-** [comment]
@schacon op:tonkatsu will ultimately fix this regardless of it being a bug currently, correct?

**Comment by krlvi** [comment]
Hey @daniilS - this should be now double fixed. We made the button show only on correct commits, and the app now supports undoing any commits in the stack. If you dont mind I will close this issue as resolved. If you feel I may have missed something, feel free to ping or create a new one.
