### ISSUE TITLE
[windows] bug after update to 0.11.2, unable to push

### ISSUE THREAD

**Issue by chip-davis** [gitbutlerapp/gitbutler#3540]
Hello,

After updating to the latest version I am unable to push to my repository. I get the error
```
Git push failed
Your branch cannot be pushed due to an unforeseen problem.

Please check our  on fetching and pushing for ways to resolve the problem.

backend error: failed to execute git command: The system cannot find the file specified. (os error 2)
```
I tried uninstalling and reinstalling but this did not fix the issue. I uninstalled 0.11.2 and reinstalled 0.11.1 and the issue was resolved.
Love GitButler by the way, just wanted to let you guys know!

**Comment by krlvi** [comment]
thanks for reporting! seems to be a windows specific issue. we are looking at this

**Comment by chip-davis** [comment]
Other details:
Windows 11
GitHub was the remote
Repo I was working on I was already using 0.11.1 with.
There were no staged or unstaged changes within the repo when I updated to 0.11.2.
I tried undoing commits and pushing one at a time but that did nothing.
I tried to open a PR without pushing to remote first with the dropdown but that also gave the same error.

**Comment by chip-davis** [comment]
Update:
Through Discord conversations, CrowdStrike AV is the culprit

**Comment by chip-davis** [comment]
Issue has been resolved!
