### ISSUE TITLE
Visual indication when collapsed lane has uncommitted changes

### ISSUE THREAD

**Issue by daniilS** [gitbutlerapp/gitbutler#3555]
I tend to collapse a vbranch lane if I'm not currently intending to make any changes to it. It would be nice to have some visual indication showing if there are any uncommitted changes in a collapsed lane, which usually means I accidentally modified some code that conflicts with a change in a collapsed lane, as I may not otherwise notice a hunk missing from the default vbranch.

**Comment by PavelLaptev** [comment]
@daniilS what do you think if we indicate like this?

<img width="1273" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/6f648a9f-3f24-4739-b7a3-79a0181e546c">

**Comment by daniilS** [comment]
@PavelLaptev Looks good to me! Perhaps "uncommitted changes" would be better so as not to imply that the banch itself has a committed/uncommited state, but can keep it as is if that'd make the label too long.

**Comment by PavelLaptev** [comment]
@daniilS Right. I agreed with you about possible naming confusion.
Let's do it like this — show number of changes and also show the tooltip on hover

https://github.com/gitbutlerapp/gitbutler/assets/18498712/a5e42659-6c72-438d-a998-d61cf5e5851c

**Comment by daniilS** [comment]
@PavelLaptev LGTM!

**Comment by PavelLaptev** [comment]
@daniilS cool 🙂 merged! Should be available next release
