### ISSUE TITLE
Prevent clipping of error text in toast message

### ISSUE THREAD

**Issue by mtsgrd** [gitbutlerapp/gitbutler#3556]
@PavelLaptev any chance you could help with this? It's often not a big deal, but at worst it could hide some critical detail from the user.

<img width="544" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/1300356/75ffc40b-4170-45c6-893a-cb207dd503e2">

**Comment by PavelLaptev** [comment]
@mtsgrd sure
