### ISSUE TITLE
Incorrect authentication failed message

### ISSUE THREAD

**Issue by Fryuni** [gitbutlerapp/gitbutler#3565]
When configuring the GitHub integration after clicking on check status, the authentication succeeds but a message pops up at the bottom saying it failed:
![image](https://github.com/gitbutlerapp/gitbutler/assets/11063910/08567b3a-a94e-4e80-a624-7076eed4c75f)

**Comment by Qix-** [comment]
Hi there, which platform are you using? And are you on nightly or stable?

Thanks for reporting!

**Comment by Fryuni** [comment]
Intel Mac using version 0.11.5

**Comment by Qix-** [comment]
Thanks, no that's currently considered our stable version (we're still in beta product-wide). I'll take a look into this in the coming week or so. Is it blocking you from continuing on with the setup process at all?

**Comment by Fryuni** [comment]
Not blocking anything, the auth works. It just says it didn't work.

**Comment by mtsgrd** [comment]
Sorry about the delay, just landed a fix.
