### ISSUE TITLE
Respect Git configuration related to signing when creating commits

### ISSUE THREAD

**Issue by Byron** [gitbutlerapp/gitbutler#3586]
Currently, GPG based signature configuration is not respected by default, even though users would expect commits to be created just like Git would.

For instance, creating a commit in a virtual branch and pushing that will cause the commit to be unsigned, even if the user configured commit signatures, i.e.:

```git-config
[user]
  name = User
  email = user@example.com
  signingkey = 4D90A8D52B4321F7
[commit]
  gpgsign = true
```

Right now there is an option (default off) to sign with a locally generated key…

<img width="787" alt="Screenshot 2024-04-23 at 11 56 04" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/f1aed70b-eed7-42d9-be99-6dcf79c45540">

…but using that wouldn't imply that it is trusted by other parties.

### Sources of Confusion

* The "Use Git executable" authentication method actually affects how to fetch and push, with `auth*` being implied. Users may think that this rather means to use Git for all (or most) operations so that their settings would be respected no matter what.
<img width="591" alt="Screenshot 2024-04-23 at 13 13 26" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/ae1eaa2c-2bfe-4703-88b9-6db9c522d94b">

### Related Issues

* #3449 
* #3147 
* #3243

**Comment by jrushlow** [comment]
Just some constructive feedback: the inability to sign commits based on my existing git config is a blocker for me. I can see a huge benefit in using GitButler while maintaining say `symfony/maker-bundle` || `symfony/symfony` - a repo in which I jump around between branches alot. But, my development flow is complicated enough, I do not want to have to add another "piece to the puzzle" in order to use additional tooling. E.g. maintain another gpg key for signing commits when I already have a perfectly good one. 

Anywho - Look forward to seeing GitButler grow, and hopefully being able to use it in my day to day in the near future...

**Comment by MikeJCusack** [comment]
The initial comment mentions about GPG based signing, but for me I would like to have my keys in 1Password be used for signing, as is the case without using GitButler. Using GitButler's key is usable by adding that key to Github/Gitlab, but it would be nice to be able to use 1Password keys for both authentication and signing.

**Comment by jrushlow** [comment]
@MikeJCusack I could be wrong, but I believe that when this issue gets implemented, that would work out of the box for you -assuming that when you do a `git commit` on the CLI, your commit is signed as expected. 

It's my understanding that when your `.gitconfig` `commit.gpgsign: true` - under the hood git will use the key set in `user.signingkey` else fall back to `gpg` defaults. 

I wouldn't be surprised if the 1password cli tool ultimately imports the gpg key into your local gpg keyring to make things appear seamless on the os level. e.g. 1password is not replacing your local gpg as a signing agent / key store

**Comment by MikeJCusack** [comment]
I'm using ssh commit signing, but otherwise this is my understanding as well. Just wanted to make sure this fix would be addressing both gpg and ssh signing.

**Comment by Qix-** [comment]
Yes this is a known issue, I've been meaning to add signing support to the fork/exec end of things. Assuming I can get rust-analyzer working again in `gitbutler-core` I'll address this within the week.

**Comment by Byron** [comment]
I think this may also be fixed by now.
