### ISSUE TITLE
[ui] ability to show current GitButler version

### ISSUE THREAD

**Issue by jrushlow** [gitbutlerapp/gitbutler#3590]
On linux, `v0.11.4_amd64.deb` - There is no way to see what version of GitButler I'm currently using in the UI. Having an "About" dialog/modal accessible via "File" or "Window"? that shows the current version would be helpful. 

e.g. do I need to go download the latest git butler? Hm.. let's go see what version I have. Wait a minute.... :smile:

**Comment by Byron** [comment]
Thank you! A very similar issue is #2845 , but I don't think this is a duplicate as here it is suggested to integrate with the OS menu, fulfilling expectations of the platform.

For completeness, on MacOS, this does already exist, but I don't know why this doesn't propagate to Linux.

<img width="418" alt="Screenshot 2024-04-23 at 19 02 15" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/be16fd0c-dad3-4553-8170-b3af5d440b8f">

**Comment by jrushlow** [comment]
@Byron - If I'm not mistaken, the `GitButler` menu depicted in the screen shot above, is a "macos native" menu. e.g. the menu / dropdown is built into MacOS and somehow the context (`About GitButler`) is added to that menu. Suspecting at compile / build time - but I could be completely wrong in that regard.

On Linux (PopOS / Debian): 
![image](https://github.com/gitbutlerapp/gitbutler/assets/40327885/08f64881-2e16-4785-a7a9-7db396d50ed8)

**Comment by slingshotvfx** [comment]
This is an issue in Windows as well
![image](https://github.com/gitbutlerapp/gitbutler/assets/146885925/19732326-439c-46e4-bcbe-2b3ef7a92b28)

**Comment by PavelLaptev** [comment]
@jrushlow, could you check if it works for you and resolves the issue? In the latest release 0.5.464, we've added the current app version to the 'Help' menu.

<img width="379" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/072d7d61-f280-459a-a65d-045cbbdd7b15">

**Comment by jrushlow** [comment]
Can confirm that the issue is resolved on Debian based distro's 
![image](https://github.com/gitbutlerapp/gitbutler/assets/40327885/af27c7b3-4acc-4c52-a053-20e6bc2576db)

And the menu appears on MacOs
![image](https://github.com/gitbutlerapp/gitbutler/assets/40327885/89d98269-5097-4e49-878d-497462a22919)


Unfortunately, I do not have Windows to confirm the version is displayed in the menu there as well. Though I would says its safe to assume that it does. @slingshotvfx 

Thank you!

**Comment by slingshotvfx** [comment]
Confirmed there is now a help menu on windows with the version number.  Looks great!

**Comment by PavelLaptev** [comment]
@slingshotvfx cool! Thank you ☺️
