### ISSUE TITLE
Error-Popups don't show anymore

### ISSUE THREAD

**Issue by Byron** [gitbutlerapp/gitbutler#3591]
As of Version 0.11.4 (20240423.110032), error popups don't show anymore. The last known working version is Version 0.11.3.

### Reproduction

* add a newly initialized git repository as project

This now fails without any effect being visible in the UI. The logs will show the error though, and in debug mode, the console will show it too.

<img width="603" alt="Screenshot 2024-04-23 at 19 07 53" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/9a2aed4c-eceb-4269-ba60-105eff8b963a">

**Comment by Byron** [comment]
Bisection revealed that the issue was introduced in this commit: 5c9ce25cd009c1f2493f0cf81a86b69061be573a . Interestingly, there is no error in the console or anything like that.

**Comment by mtsgrd** [comment]
@PavelLaptev can you take a look?

**Comment by PavelLaptev** [comment]
@mtsgrd sure. I'll take a look

**Comment by PavelLaptev** [comment]
@Byron @mtsgrd this PR https://github.com/gitbutlerapp/gitbutler/pull/3599 should solve the issue. There was the wrong condition check
from Rust we receive errors like just `error` and not `error.message`
