### ISSUE TITLE
It doesn't work without a branch named main.

### ISSUE THREAD

**Issue by syxc** [gitbutlerapp/gitbutler#3594]
It doesn't work without a branch named `main`.

My default branch name is `master`.

```
Error: not found: cannot locate remote-tracking branch 'origin/main'; class=Reference (4); code=NotFound (-3)
```

**Comment by Byron** [comment]
Thanks for reporting!

I can reproduce this, trying to add the `GitButler` repository.

<img width="930" alt="Screenshot 2024-04-24 at 10 57 54" src="https://github.com/gitbutlerapp/gitbutler/assets/63622/53ce60ce-f513-434d-a4e6-416eb720b225">

**Comment by syxc** [comment]
> Thanks for reporting!
> 
> I can reproduce this, trying to add the `GitButler` repository.
> 
> <img alt="Screenshot 2024-04-24 at 10 57 54" width="930" src="https://private-user-images.githubusercontent.com/63622/325152350-53ce60ce-f513-434d-a4e6-416eb720b225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDk3MjksIm5iZiI6MTcxMzk0OTQyOSwicGF0aCI6Ii82MzYyMi8zMjUxNTIzNTAtNTNjZTYwY2UtZjUxMy00MzRkLWE0ZTYtNDE2ZWI3MjBiMjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA5MDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzM2ZTkzMmFlMmRhNGYyMTZhNmEwZDhkNDU2MGE0ODFiOGFmOTVmYjBhNTY1NDc4ZGQwNWJmYTcwYjFmYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wZ-Pu9DYMHpqZRdVn-0Gb-LbjCrHJ_qvELsVhTjI2GE">

<img width="579" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/315633/0081beb7-22eb-434e-98b8-babbdae5f21e">


GitButler Version: `0.11.4 (20240423.110032)`

**Comment by Byron** [comment]
The issue was introduced here as found with a bisect from `HEAD~70..HEAD`: 2c5465639c2173a02207f0a97cf4eca61e15f2b0

**Comment by krlvi** [comment]
For some reason i am unable to reproduce it. Digging more into it now...

**Comment by Byron** [comment]
With a freshly cloned repo, I also couldn't reproduce it. But my local clone was showing it out of the box, I sent you the download link on discord.
