### ISSUE TITLE
Dark Mode shows white background for "GitHub features enabled" section on project setup page

### ISSUE THREAD

**Issue by AnaelBonnafous** [gitbutlerapp/gitbutler#3611]
![image](https://github.com/gitbutlerapp/gitbutler/assets/71386173/d708ad86-fe09-4767-b58c-559b5d72eb37)
![image](https://github.com/gitbutlerapp/gitbutler/assets/71386173/eccadb28-a442-4015-9c57-257c354f1330)

Windows 11 GitButler 0.11.4 x64

**Comment by PavelLaptev** [comment]
@AnaelBonnafous thank you for the report. I'll fix it asap

**Comment by PavelLaptev** [comment]
@AnaelBonnafous should be fixed with the latest release `0.11.5`
Could you please check if the issue still exists for you? Looks like there were a broken CSS variable

**Comment by AnaelBonnafous** [comment]
I just updated to `0.11.5` and it's indeed fixed 👍 thanks !

![image](https://github.com/gitbutlerapp/gitbutler/assets/71386173/214cc22f-0e57-4350-b101-d50b3704f8a7)

**Comment by PavelLaptev** [comment]
@AnaelBonnafous Cool! Thank you for reporting and checking this 🙏
