### ISSUE TITLE
Drag images or other files to app window unexpected behaviour

### ISSUE THREAD

**Issue by venCjin** [gitbutlerapp/gitbutler#3617]
Hey, so I was checking if I can drag image to app to set my profile pic, and got surprised because app opened it as a web browser. 

Behavior is little bit different on mac and windows platforms:
- on win files are opend in separate windows,
  ![image](https://github.com/gitbutlerapp/gitbutler/assets/9089366/02316b9a-24a0-4bd6-b7cd-51de044b29de)
- on mac files are opend in app window (and if I want to get back to app I have to right-click on empty space to get back option in menu, also if dragged multiple things one by one, then have to back multiple times - normal browser back through history),
  ![image](https://github.com/gitbutlerapp/gitbutler/assets/9089366/e7119a9e-75dd-49e7-93d8-145922a8e61b)
so I guess they are opend the same way as `Developer Tools`.

Tested on images, text files, web links (opens web page - as expected at this point 😄).

**Comment by PavelLaptev** [comment]
Thanks for the report, @venCjin! The fix will be included in the next release.
