### ISSUE TITLE
Please add support for VSCodium and allow for external editors

### ISSUE THREAD

**Issue by dangreene0** [gitbutlerapp/gitbutler#3646]
I am simply requesting for the ability to select other code editors besides VSCode.

Thanks.

**Comment by krlvi** [comment]
Hey @dangreene0 
Thanks to this pr https://github.com/gitbutlerapp/gitbutler/pull/3958 by **[TheGB0077](https://github.com/TheGB0077)** the app should now be able to open in vscodium. For other editors we would need to do some more work.
Could you test out the latest release and see if it works for you?

**Comment by dangreene0** [comment]
**Confirmed** to work on Linux Mint 21.3, however it says `VSCode` in GitButler but will still prompt to open `VSCodium` in the OS. This is probably unintentional but is worth noting.

**Comment by Byron** [comment]
Thanks for sharing! Admittedly, I never thought of changing the label as well, and the current solution definitely doesn't attempt that. If memory serves, it's handled in the backend as well so I don't know how easy it would be to do that.

From a UX perspective, I think it's less confusing to show what would be opened. However, I also think that when we go there, we should also disable the menu item if no vscode/vscodium are available at all, as we'd have to be proactively checking for available editors then.
