### ISSUE TITLE
Can't install on ubuntu 24.04

### ISSUE THREAD

**Issue by jibon0070** [gitbutlerapp/gitbutler#3675]
when we try to run command
```
sudo dpkg -i git-butler_0.11.5_amd64.deb
```

It throws an error saying

```
dpkg: dependency problems prevent configuration of git-butler:
 git-butler depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.
```

but in ubuntu 24.04 it's not possible to use libwebkit2gtk-4.0-37;
in ubuntu 24.04 libwebkit2gtk-4.1-0 installed by default

please help we are addicted to both ubuntu 24.04 and gitbutler

**Comment by Qix-** [comment]
Hey there, sorry you're hitting this. I'm not sure what the workaround for this is at the present moment; we don't control those dependencies, those are all handled by the [Tauri project](https://github.com/tauri-apps/tauri).

It looks like tauri-apps/tauri#9662 is reporting it already. Sorry you're hitting it!

I'll subscribe there myself, and if there's any action we can take with e.g. our confs or something I'll do so and push out a fix pronto.

Thanks for the issue :)

**Comment by jibon0070** [comment]
Found a work around

add `deb http://gb.archive.ubuntu.com/ubuntu jammy main` line to `/etc/apt/sources.list` file. then
```sudo apt update```
```sudo apt install libwebkit2gtk-4.0-37```
finally
```sudo dpkg -i git-butler_0.11.7_amd64.deb```

**Comment by kaustubhthakur02** [comment]
What is the Stable Version for ubuntu 20, getting this error 
sudo dpkg -i GitButler_0.14.4_amd64.deb 
Selecting previously unselected package git-butler.
(Reading database ... 241676 files and directories currently installed.)
Preparing to unpack GitButler_0.14.4_amd64.deb ...
Unpacking git-butler (0.14.4) ...
dpkg: dependency problems prevent configuration of git-butler:
 git-butler depends on libwebkit2gtk-4.1-0; however:
  Package libwebkit2gtk-4.1-0 is not installed.
 git-butler depends on libwebkit2gtk-4.1-0; however:
  Package libwebkit2gtk-4.1-0 is not installed.

dpkg: error processing package git-butler (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 git-butler

**Comment by Caleb-T-Owens** [comment]
Hi @kaustubhthakur02, Installing the deb on versions of Ubuntu less than 24 is no longer supported. I believe the AppImage may still work, and we've got a FlatPack in the works which should behave the best out of all of them (@ndom91 can advise more).

You should also be able to build the project from source if the AppImage fails.

Sorry for any inconvenience caused.

**Comment by ndom91** [comment]
You can find an experimental version of the first-party flatpak (built with 0.14.4) here: https://github.com/ndom91/gitbutler-flathub/actions/runs/12334361653

We'd be happy about any feedback!
