### ISSUE TITLE
Infinite loading when adding a project with "Git executable"

### ISSUE THREAD

**Issue by PavelLaptev** [gitbutlerapp/gitbutler#3679]
When I add a project with the 'Git executable' option (enabled by default), I encounter an infinite loading state. However, if I reload the page, I can see that the project was actually added. This issue occurs on the development build.
Interestingly, it doesn't happen if I add the project with the 'Auto detect' option instead.

See video below:

https://github.com/gitbutlerapp/gitbutler/assets/18498712/7abdc25f-a545-4044-a584-ef4e6be8e901

https://github.com/gitbutlerapp/gitbutler/assets/18498712/badc61c2-8eed-456d-afe9-4378c9591d57

**Comment by Qix-** [comment]
Does this happen with any other of the auth methods?

**Comment by estib-vega** [comment]
Can't reproduce in version 0.12.23

**Comment by krlvi** [comment]
i believe this is solved. lets close and create a new one if this becomes a problem again
