### ISSUE TITLE
Projects are not sorted alphabetically

### ISSUE THREAD

**Issue by Nexx4** [gitbutlerapp/gitbutler#3698]
At the moment the projects are not sorted by default and probably listed based on the creation date.
Once you have a few items on the list, it would be useful to sort them **alphabetically**, especially if you need to rename them.

![image](https://github.com/gitbutlerapp/gitbutler/assets/2477989/11ed0e48-5059-46ee-9736-e7c1e58c0653)

**Comment by Qix-** [comment]
Thanks for reporting! Fixed :)
