### ISSUE TITLE
“Let's go” stuck spinning

### ISSUE THREAD

**Issue by dlejay** [gitbutlerapp/gitbutler#3713]
First installation of Gitbutler, after all checks are passed and the "let's go" button is clicked, it gets stuck spinning.

<img width="563" alt="Screenshot 2024-05-06 at 21 35 42" src="https://github.com/gitbutlerapp/gitbutler/assets/39823850/dd50a269-12c6-495c-aece-ddfa109f5b71">

I am on an M1 macOS running Sonoma 14.4.1
Latest Gitbutler version.

**Comment by Qix-** [comment]
Hey there! Thanks for reporting. Does this also happen when you select `Use a Git Executable`?

**Comment by Qix-** [comment]
Might be related to #3679

**Comment by dlejay** [comment]
More feedback about my experience so far:
* Gitbutler thinks my '~/.ssh/id_ed25519' key does not work
* The “stuck spinner” eventually resigns
* Then I get a “stuck workspace” for ages
* Then this morning, the workspace is no longer stuck but Gitbutler reports more than 28000 changes on my main branch !
* After quitting and restarting Gitbulter, I go back to the “stuck spinning workspace”

**Comment by krlvi** [comment]
Hi @dlejay. Wondering, is this still an issue for you? I have a strong suspicion that it has been resolved as part of fixing other things. If not, I will close this issue

**Comment by krlvi** [comment]
Closing this since I believe this is fixed and haven't heard back. Feel free to open a new issue if this still presents a problem
