### ISSUE TITLE
Selecting a Base branch is difficult if there are MANY branches.

### ISSUE THREAD

**Issue by trissylegs** [gitbutlerapp/gitbutler#3736]
Unfornunately I probabably can't share a screenshot for confidentiality reasons. (I'm trying to use this on a company-wide monorepo). 

But there are some 27,000 remote tracking branches. (Git can handle this fine). But I need to pick a base branch starting with g. So i have to manually scroll past 5114 branches first.

It would be nicer if you search the list for the remote. Idealy drop down lists are only used for a smaller selection. (Not 27,000 items)

```
git branch -r | wc -l
   27232
```

**Comment by PavelLaptev** [comment]
@trissylegs thank you for your feedback :-)
You're talking about this step, right?
I'm wondering how does the app load all these branches. Do you have any performance issues?

<img width="1119" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/cd35b3b6-e7d3-433b-a60f-bada64a5498b">

**Comment by Byron** [comment]
Reopening as I think this issue is still relevant, for performance particularly. I can imagine the UI will need special treatment to assure it won't create 27k elements, while also making the list searchable with a term to reduce the set of options to select from.
