### ISSUE TITLE
Adding a Git repo on Windows opens up the terminal window

### ISSUE THREAD

**Issue by sschuberth** [gitbutlerapp/gitbutler#3769]
I was starting GitButler on Windows for the first time. When asked to add a repository, I navigated to one and selected the folder. Immediately afterwards, the Windows terminal application popped up, with no indication whatsoever why that happened.

Any idea why that happens, and how it can be avoided?

**Comment by Byron** [comment]
Thanks for reporting! I assume it's version 0.11.7 that you are using?
It's the first time (at least) I hear about this, but if it happens each time a repository is added, it should be easily reproducible .

**Comment by sschuberth** [comment]
> I assume it's version 0.11.7 that you are using?

Yes. Sorry for omitting that information initially.

> if it happens each time a repository is added, it should be easily reproducible .

I just verified that it also happens (again) when adding another repo via "Add new project" from the combobar in the upper left of an existing project.

**Comment by DrBarnabus** [comment]
I started getting this with the latest nightly, it's not just adding a new repo it's basically any action for example:

- Edit a file and save
- Click to refresh commits on Trunk
- Click to update workspace

Seems basically everything that causes a git operation opens the terminal for a split second.

**Comment by sschuberth** [comment]
> opens the terminal for a split second.

In my case though, actually the terminal window stays open.

**Comment by Byron** [comment]
I have a feeling that this is due to `git` now being invoked for these operations, but with [the `CREATE_NO_WINDOW` flag](https://github.com/gitbutlerapp/gitbutler/blob/d71e4d361711ca7057ad78f094c70b83d625ddad/crates/gitbutler-git/src/executor/tokio/mod.rs#L78-L82) missing.

Can it be that you are using a signing key or have commit signing enabled in any way?

**Comment by sschuberth** [comment]
> Can it be that you are using a signing key or have commit signing enabled in any way?

I don't have cryptographic singing of commits enabled. In *some* of my repos I use a commit message template to add a `Signed-off-by` footer, but not in the repo I use with GitButler.

**Comment by sschuberth** [comment]
Is there a way to log which exact `git` command line GitButler tries to run?

**Comment by DS-DanielW** [comment]
> I have a feeling that this is due to `git` now being invoked for these operations, but with [the `CREATE_NO_WINDOW` flag](https://github.com/gitbutlerapp/gitbutler/blob/d71e4d361711ca7057ad78f094c70b83d625ddad/crates/gitbutler-git/src/executor/tokio/mod.rs#L78-L82) missing.
> 
> Can it be that you are using a signing key or have commit signing enabled in any way? And if so, if you turn it off, does the Cmd-popup go away?
> 
> Edit: With a plain installation on Windows 11 I didn't reproduce the Cmd window popup, but also know that commit signing is disabled and the added project was never touched by GB either.

Can confirm in my case at least this seems to be the issue, disabling commit signing stopped the windows appearing.

**Comment by Byron** [comment]
Thanks everyone for your help! A fix is brewing in #3800 now.
