### ISSUE TITLE
switch button background is hidden on mouse hover

### ISSUE THREAD

**Issue by Belingheri** [gitbutlerapp/gitbutler#3805]
When the mouse is hover on the switch button the green background is hidden:
![image](https://github.com/gitbutlerapp/gitbutler/assets/33315640/97862a8d-3d0d-4af7-bb20-e0bd6745ed5d)

Same issue with the light mode

gitbutler  `0.11.7` 
OS Fedora `46.1`
runned using the .AppImage bin

**Comment by PavelLaptev** [comment]
That should be fixed. Looks like it was a CSS color function issue.

**Comment by Belingheri** [comment]
> That should be fixed. Looks like it was a CSS color function. But let me know if you see this again, I'll reopen the issue

I tried it with the `v0.12.5` and it work 🚀
Thanks
