### ISSUE TITLE
Failed to update the excludes stack to see if a path is excluded

### ISSUE THREAD

**Issue by neerajjain92** [gitbutlerapp/gitbutler#3876]
I am trying to import a project in gitbutler app, here is the repo https://github.com/neerajjain92/data-structures but getting error 

There was a problem
Failed to update the excludes stack to see if a path is excluded

<img width="467" alt="Screenshot 2024-05-28 at 3 45 28 PM" src="https://github.com/gitbutlerapp/gitbutler/assets/11440750/174bc03e-50cb-4d28-9f45-b057b12bb7f7">

**Comment by neerajjain92** [comment]
I have identified the issue. The problem occurred because GitButler was attempting to locate a .gitignore file, but due to a mix-up, the .gitignore was mistakenly created as a folder in my repository. This caused GitButler to throw an error.

However, the error message provided was not very informative and did not clearly indicate the steps needed to resolve the issue.

**Comment by Byron** [comment]
That's an amazing find, thanks so much for reporting!

I can reproduce the issue and it looks like Git just ignores directories with this name. Clearly, `.gitoxide` should do the same.
(*Note to self: also validate `.gitattribute` files, they are probably similar*).

**Comment by neerajjain92** [comment]
Thanks a lot @Byron for a prompt response

**Comment by Byron** [comment]
You are very welcome! Actually `gitoxide` already tried to ignore directories, but a test was missing and it didn't actually work due to unfortunate reasons.
