### ISSUE TITLE
Cannot close the file card opened by clicking Trunk's commit history files

### ISSUE THREAD

**Issue by lisiur** [gitbutlerapp/gitbutler#3897]
![image](https://github.com/gitbutlerapp/gitbutler/assets/15188817/13db2bb4-d4a4-4b1d-860a-52d49c8f8071)

Currently, we cannot close the file card on the right side by clicking the 'Close' button or
canceling the selection of files.

**Comment by Caleb-T-Owens** [comment]
Thanks for closing this for us @lisiur 👍
