### ISSUE TITLE
"Open in VSCode" does not open the current repository

### ISSUE THREAD

**Issue by l-melon** [gitbutlerapp/gitbutler#4003]
## Description

When I click on the "Open in VSCode" button , VSCode opens, but it does not open the current repository. 

## Steps to Reproduce

1. Click on the "Open in VSCode" button.
![image](https://github.com/gitbutlerapp/gitbutler/assets/71011125/9d165eef-92d0-4444-8f0d-7c0da7fe1d04)

## Expected Behavior

VSCode should open with the current project.

## Actual Behavior

VSCode opens as if it was launched using the `code` command from the terminal.
## Environment

- **Operating System:** Windows 11
- **VSCode Version:** 1.89.1

**Comment by TheGB0077** [comment]
I believe the behavior stands from Windows returning the absolute Path as 

`C:\Users\X\test\repo`, whilst Linux returns `/home/X/test/repo` and when interpolated on the string template we end up with: 

vscode://fileC:\Users\X\test\repo\ ← **Missing the “/“ between file and the path to work**

Although, I found that opening from a specific line works
![image](https://github.com/gitbutlerapp/gitbutler/assets/39922116/f6dd9d75-1f17-462c-acdd-2321026c5bbf)

**Comment by l-melon** [comment]
Opening a file from a specific line only works when there's no VS Code already running. If VS Code is already open, clicking 'Open in VS Code' behaves the same as running `code`.

There is different behaivour depending on the source of the "Open in VS Code".
Clicking "Open in VS Code" from the taskbar or `Changes` windows, similar to running the `code` command. No confirmation dialog appears in this scenario.
![image](https://github.com/gitbutlerapp/gitbutler/assets/71011125/080d9264-23f8-46be-bfcc-eeb707c87e8b)

Clicking "Open in VS Code" from a specific line triggers a dialog asking if I want an external application to open the file. 
![image](https://github.com/gitbutlerapp/gitbutler/assets/71011125/ce506258-311a-46ab-a773-72b7407debd0)

**Comment by l-melon** [comment]
#3503 
#3489

**Comment by Byron** [comment]
Thanks for reporting, and special thanks to @TheGB0077 for the analysis and the fix!

**Comment by vuggy17** [comment]
Is this bug released yet? I'm facing issue that pressing "open in vscode" no nothing with `git-butler_0.12.9_amd64.deb`  package ( window wsl2)

**Comment by Byron** [comment]
Thanks for letting us know. Could you open open a new issue for that?
