### ISSUE TITLE
Show "Integrations" tab even when user's not logged in, for the purpose of discoverability

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#4030]
Context: https://discord.com/channels/1060193121130000425/1206670506271707156/1248558575056326669

**Comment by mtsgrd** [comment]
It feels like we should grey out the authorize button, and prompt the user to login..  but dropping the `<WelcomeSignInAction>` here neither gives us reasonable copy, nor does it provide a clear button. @PavelLaptev I know you're busy atm, but when you get a chance, could you help us out here?

<img width="545" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/1300356/28d9ebcf-5458-4d71-b89f-85541044c721">

**Comment by PavelLaptev** [comment]
@mtsgrd sure I'll take a look. Probably tomorrow-ish
