### ISSUE TITLE
Can't open GitButler if closed when maximized (WSL)

### ISSUE THREAD

**Issue by TrueBrain** [gitbutlerapp/gitbutler#4039]
Steps to reproduce:
- Open GitButler on WSL
- Double click to maximize
- Close GitButler
- Open again

This results in: `Gdk-Message: 10:20:40.636: Error 71 (Protocol error) dispatching to Wayland display.`

Removing the file `.config/com.gitbutler.app/.window-state` solves the issue, resetting the window state. It only happens when maximized. When making it as big as maximized would be, doesn't result in any problem.

**Comment by Byron** [comment]
Thanks for researching this and sharing the workaround of deleting `.config/com.gitbutler.app/.window-state`!

I think the `.window-state` file is created by `tauri`, so my feeling is that this is a tauri bug, however, [I couldn't find one](https://github.com/tauri-apps/tauri/issues?q=is%3Aopen+%22dispatching+to+Wayland+display%22+) there.

If you think the same, you could of course open an issue there as well in case somebody recognizes the issue.

**Comment by donni-h** [comment]
> Thanks for researching this and sharing the workaround of deleting `.config/com.gitbutler.app/.window-state`!
> 
> I think the `.window-state` file is created by `tauri`, so my feeling is that this is a tauri bug, however, [I couldn't find one](https://github.com/tauri-apps/tauri/issues?q=is%3Aopen+%22dispatching+to+Wayland+display%22+) there.
> 
> If you think the same, you could of course open an issue there as well in case somebody recognizes the issue.
I just spent a while debugging this.
It doesn't appear to be a Tauri error, but probably a Weston error (the compositor WSL relies upon) or WSL itself.
When running `WAYLAND_DEBUG=1 git-butler` you will eventually get something like this:
`wl_display@1.error(xdg_wm_base@23, 4, "xdg_surface buffer (1160 x 757) does not match the configured maximized state (0 x 0)")
Gdk-M`

Here are a few programs experiencing similar issues:
https://github.com/wez/wezterm/issues/3765
https://youtrack.jetbrains.com/issue/JBR-7313/Wayland-error-xdgsurface-buffer-does-not-match-the-configured-maximized-state
https://github.com/microsoft/wslg/issues/646

**Comment by donni-h** [comment]
Fun fact I just found out: If you force it to start with X11 as a Backend it works just fine (even maximizes properly!), however the window decorations look different.
