### ISSUE TITLE
Discarding changes in an unapplied branch discards Workspace changes instead

### ISSUE THREAD

**Issue by askielboe** [gitbutlerapp/gitbutler#4062]
1. Make changes to a file in the Workspace.
2. Unapply the changes.
3. Make more changes to the same file in the Workspace.
4. Go to the unapplied branch, right-click the file and select "Discard changes".
5. The changes you made in the active Workspace are now discarded instead of the changes in the unapplied branch.

I would expect one of the following to happen instead:

1. The changes in the unapplied branch where I'm clicking "Discard changes" should be discarded instead.
2. Not be able to click "Discard changes" on a file in an unapplied branch.

Another related bug: Clicking discard on a hunk in an unapplied branch has no effect.

**Comment by Byron** [comment]
I am sorry for this happening and hope that the undo-feature is bringing the worktree changes back after reverting to the previous state.

I could reproduce this in version 0.12.3, but also was able to bring the change back thanks to the undo function.

**Comment by mtsgrd** [comment]
This is fixed by #4074, sorry @Byron , should have updated this issue last night. Thanks @askielboe, for now we don't support discarding things from unapplied branches so I went with option 2. 🙏
