### ISSUE TITLE
In some conditions the push/rebase button can be "undefined"

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#4064]
![image](https://github.com/gitbutlerapp/gitbutler/assets/4030927/4154ae0f-b9b8-4413-98cf-ad93ae317d93)

**Comment by PavelLaptev** [comment]
@krlvi This one is fixed, I suppose. I wasn't able to reproduce the issue.
I'll close the issue for now, but we can reopen it if you encounter this problem again.
