### ISSUE TITLE
Accessibility Feature: Optionally disable scrollbar hiding

### ISSUE THREAD

**Issue by iSchluff** [gitbutlerapp/gitbutler#4067]
Hi, this might be somewhat of an edge case but I mainly develop using speech control and eye tracking using the awesome https://talonvoice.com/

Using the Gitbutler client right now is a bit of an hassle with the eye tracker, because there is no good way to scroll as the scrollbars are hidden by default.
I would like to have an option to disable the scroll bar hiding.

If you agree that this is a worthwhile change I could work on a PR.

**Comment by krlvi** [comment]
Hey @iSchluff, thank you for reporting this, having the app accessible is important so this is definitely something for us to correct. I think @PavelLaptev had some thoughts around fixing this too

**Comment by PavelLaptev** [comment]
Hey @iSchluff! 
Thank you for your feedback.
In the application (Profile settings) we have a switcher for the scrollbar.

<img width="677" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/67368130-e89d-4d29-849a-b1f47c8222da">

I think what we can do here is to add a third option like this:

<img width="730" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/82d1199a-4f29-4b6c-931e-5dea5c0e3487">

---

Here is updated design in Figma link https://www.figma.com/design/FbeLt0yjY9RiNn8MXUXsYs/Client-design?node-id=1507-63554&t=uF2MHe4JyrwcEMfF-1

---

a PR is welcome, just add me to reviewers when you finish 🙂

**Comment by H1ghBre4k3r** [comment]
@PavelLaptev just so I get this right: Shouldn't the first one be something like "Show the scrollbar only when you scroll"?

**Comment by H1ghBre4k3r** [comment]
I just was motivated to create a small PR for this change. Hopefully, this does not interfere with anything you already did, @iSchluff. ^^'

Feel free to leave any review comments you'd like.

**Comment by PavelLaptev** [comment]
> @PavelLaptev just so I get this right: Shouldn't the first one be something like "Show the scrollbar only when you scroll"?

@H1ghBre4k3r Correct! It was a placeholder, updated that to your version. Thanks for noticing 🙏 

<img width="730" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/18498712/f86cbc8d-4e1a-44b6-91c5-c671bc771830">

**Comment by H1ghBre4k3r** [comment]
@PavelLaptev Ah, great! 

Apparently, I was not able to assign you as a reviewer for my PR. But fortunately, you already did that yourself. ^^'
