### ISSUE TITLE
Feature request: Quick multi stage/unstage

### ISSUE THREAD

**Issue by wesharper** [gitbutlerapp/gitbutler#4078]
Because I tend to get pretty engrossed and "in the zone", I often find myself in a scenario where I have a bunch of changed files and I want to make a handful of separate commits. In these cases, I tend to get frustrated at having to click the little checkbox next to each file if there's no easy path to the right stage from either fully-selected or fully-deselected. If that's not clear, here's an image of what I'm talking about:

![image](https://github.com/gitbutlerapp/gitbutler/assets/13283469/d73a820b-90c5-4fda-b738-7c9ce4fcf884)

Ideally, I could quickly unstage all of the highlighted files just by clicking any one of the checkboxes within that selection (or in the right-click context menu).

**Comment by PavelLaptev** [comment]
@wesharper thank you for your request!
It's a very cool UX improvement, and the feature should be included next release.

**Comment by Byron** [comment]
Totally let us know what you think when you got a chance to check it out. Nightly should have it very soon.

**Comment by wesharper** [comment]
Oh yeah, that's flippin' awesome. Thanks team!

**Comment by PavelLaptev** [comment]
Thank you @wesharper!
