### ISSUE TITLE
Adding remote uses SSH when origin uses HTTPS

### ISSUE THREAD

**Issue by vilgotf** [gitbutlerapp/gitbutler#4085]
Adding a remote via GitButler (from the "Apply from fork" button) sets up the remote with SSH. As I use `gh` with HTTPS I'm unable to fetch refs over SSH via `git` and GitButler also fails when its authentication is configured to "Use a Git executable" or "Use a Git credentials helper".

## Expected behavior

GitButler configures remotes with HTTPS or SSH based on the schema of `origin`.

## Workaround

Manually adding the remote with the correct schema works.

## System info

GitButler 0.12.4
Git 2.39.4 (Apple Git-150.1)

**Comment by Byron** [comment]
Thanks for reporting!

**Comment by vilgotf** [comment]
> [it seems to think it's dealing with `sshUrl`s](https://github.com/gitbutlerapp/gitbutler/blob/e735959e69bd85b3f560a2cb0fbe887506764b1f/app/src/lib/components/PullRequestPreview.svelte#L37). Maybe that's the culprit - an HTTPs URL snuck in there and only then it's supposed to do anything at all.

I'm actually hitting the "Remote already exists" error toast. I guess `PullRequest.sshUrl` should be reworked to accept SSH or HTTPS URLs.

**Comment by Caleb-T-Owens** [comment]
Hey! Thanks for bringing this to my attention.

The fix should be as suggested, to use use the repo http url when the trunk is http, and ssh when ssh.

I'll add this to my to-do list
