### ISSUE TITLE
Feature Request: Shortcut for entering settings

### ISSUE THREAD

**Issue by H1ghBre4k3r** [gitbutlerapp/gitbutler#4095]
On macOS, it is quite common for apps to have a registered keyboard shortcut (for probably 99% its `CMD + ,`) to open the settings of the app. 

For sake of habit, this would be a nice quality of life improvement for GitButler. 

Furthermore, It would be nice to have a menu item within the native menu provided by Tauri. Luckily, this directly provides a way to specify shortcuts for menu items, thus managing the "heavy lifting" of registering them.

**Comment by schacon** [comment]
TIL

**Comment by PavelLaptev** [comment]
@H1ghBre4k3r done 🙂
