### ISSUE TITLE
Branch filtering option disappeared 

### ISSUE THREAD

**Issue by ClementChaumel** [gitbutlerapp/gitbutler#4106]
Hi, I unchecked every option in the filter menu for branches and now it's gone and I can't turn them back on!

<img width="466" alt="image" src="https://github.com/gitbutlerapp/gitbutler/assets/11927929/cf276724-7594-45e4-b219-9bedfca53186">

I'm on Mac and using Version 0.12.5 (20240617.130345)

**Comment by ellsworthjc** [comment]
+1. Downloaded today to set it up and ran into the same issue. Excited to try GitButler though!

**Comment by Caleb-T-Owens** [comment]
Hi @ellsworthjc and @ClementChaumel.

As a work around, you can open the developer console by clicking on "View" then "Developer Tools" and then pasting the following script into the console:
```
const projectId = window.location.pathname.split('/')[1];
window.localStorage.removeItem(`includePrs_${projectId}`);
window.localStorage.removeItem(`includeRemote_${projectId}`);
window.localStorage.removeItem(`includeStashed_${projectId}`);
window.localStorage.removeItem(`hideBots_${projectId}`);
window.localStorage.removeItem(`hideInactive_${projectId}`);
```
And then refresh your app (Cmd+R).

We have already implemented a fix that will be included in the next release. 

Sorry for the inconvenience!!

**Comment by Byron** [comment]
I am closing this issue as the bug is fixed in the [latest nightly](https://app.gitbutler.com/downloads) or will be fixed in the next release. Please do report here if that's not the case then.
