### ISSUE TITLE
[enhancement] Select commit to fixup instead of creating new commit

### ISSUE THREAD

**Issue by OJFord** [gitbutlerapp/gitbutler#4118]
### Version

0.12.5

### Operating System

Mac OSX

### Distribution Method

dmg

### Describe the issue

Often I want to amend an existing commit rather than create a new one, which without gitbutler I do by `git fixup deadbeef` where `fixup` is an alias for roughly `commit --fixup=$1 && rebase --autosquash $1^`.

With gitbutler, as far as I'm aware to do this I need to create a new commit, then switch to that branch, rebase it, and switch back to the integration branch (and I guess then do something to update that in the UI).

**Comment by Byron** [comment]
Thanks for sharing!

I turned it into a bug as this seems to be about mixing `git` with the integration branch, a topic that isn't very well fleshed out. It's either GitButler, or running git commands, and I am not aware of documentation that would describe how these collaborate.

Maybe I didn't understand the problem correctly, in that case, please do feel free to re-add the bug label. However, it would definitely be helpful to have an explanation or 'steps to reproduce' which make clear what's going wrong, and what you would expect to happen instead.

**Comment by schacon** [comment]
@OJFord you can simply drag files onto the commit you want to fixup:

https://youtu.be/zZD24Ikxd1g?si=UA4pM7lombRGHV_Z&t=198

Or you could also create a temp commit and then drag it onto the commit to fixup to squash them together. Either way works.
