### ISSUE TITLE
Failed to load Pull Requests "no repo name specified"

### ISSUE THREAD

**Issue by Arilas** [gitbutlerapp/gitbutler#4132]
### Version

0.12.5

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

In a repo, that hosted on a GitHub I cannot create a PR or load a PRs list.

Additional details:
1. remoteUrl is a ssh string with github alias (Because I have multiple GitHub ssh keys, so I've made an alias). Example: `git@arilas.github.com:Arilas/my-repo.git`
2. `GitHubService` line 81: it's incorrectly parse this remoteUrl, so repo is undefined, and owner is `git@arilas`

![image](https://github.com/gitbutlerapp/gitbutler/assets/3540524/189fc347-905a-4c85-9e8e-3d2612efa7bb)

### How to reproduce

1. Create an alias for github in your ssh/config file 
2. Clone a repo using this alias
3. Try to open GitButler
4. Observe errors

### Expected behavior

It should ask user about repo or at least try to parse a string

**Comment by Byron** [comment]
Thanks a lot for reporting!

Indeed, the code that extracts information form the URL [is here](https://github.com/gitbutlerapp/gitbutler/blob/f2da13ea83d93b473c45d601d80f71f1b601069f/app/src/lib/github/service.ts#L80-L84) and it makes more assumptions than it should.

A quick solution *should* be to use [gix_url::parse](https://docs.rs/gix-url/0.27.3/gix_url/fn.parse.html) (also accessible by `gix::url::parse()` in the backend as it should be able to correctly parse this kind of URL as well.

Maybe @ndom91 could also just fix it in the frontend, but be warned that it is a can of worms to do this correctly, thus it's best to outsource this (or one would have to reimplement [this](https://github.com/git/git/blob/master/urlmatch.c#L112)).

**Comment by Arilas** [comment]
@Byron I've made PR which fixes it for me, can you check?

**Comment by ndom91** [comment]
@Arilas that seems like a reasonable quick-fix, but as @Byron said, long-term leveraging a library that handles all the edge cases would be best. 

Imo we can merge the quick-fix for now, and I can bring up using the `gix` methods to parse the remote strings with some of the rust folks here next week. What do you think?
