### ISSUE TITLE
Multi-select with CMD+click re-centres panel to first selection

### ISSUE THREAD

**Issue by win20** [gitbutlerapp/gitbutler#4139]
### Version

0.12.5

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When trying to select multiple changed files in order to drag to new branch panel, using SHIFT works completely fine, all item are selected between the two selections. However, when using CMD + click to select specific files, if the first file that was selected goes out of view (via scrolling up or down), in this case selecting another item makes the panel instantly scroll in such a way that the first item is centred inside the panel.

This can be a be frustrating when having to carefully select multiple files which have files in between that you don't want to select because it means you have to scroll again to where you were.

### How to reproduce

1. Select an item from the leftmost panel
2. Scroll up or down so that first item is not visible
3. CMD + click on another item to select it

See recording:

https://github.com/gitbutlerapp/gitbutler/assets/22985058/a76fcec0-ecb9-40f6-ac4f-1abf1e7fea86

### Expected behavior

When CMD clicking on an item after having selected an item that is out of view, new item should be selected and page should not scroll to centre the first selection, allowing you to easily select multiple items as needed.

**Comment by Byron** [comment]
Thanks a lot for reporting, and the video really helps as well.

CC'ing @ndom91 who might know exactly what to do here.

**Comment by PavelLaptev** [comment]
@win20 thank you for your report! 🙏 
Should be fixed next release.

**Comment by ndom91** [comment]
Thanks @PavelLaptev :pray:

**Comment by win20** [comment]
@PavelLaptev 
Thanks very much! I'll have a look tonight and let you know.

**Comment by win20** [comment]
@PavelLaptev 
Just had a look, works great, thanks again.

**Comment by PavelLaptev** [comment]
Cool! Glad to hear that @win20 :-)
