### ISSUE TITLE
Git authentication is hidden in Windows

### ISSUE THREAD

**Issue by akshaybabloo** [gitbutlerapp/gitbutler#4170]
### Version

0.12.5

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

The image shown in https://docs.gitbutler.com/troubleshooting/fetch-push#available-authentication-methods

![image](https://github.com/gitbutlerapp/gitbutler/assets/7360286/da893ed3-c703-4f64-a08e-8961c304b2df)

Is hidden in Windows and setting up git using the [projects.json](https://docs.gitbutler.com/development/debugging#data-files) is not documented.

The one mentioned in https://github.com/gitbutlerapp/gitbutler/issues/2915 is also hidden.

**Comment by Byron** [comment]
Thanks for reporting!

I also think it's confusing that on Windows this setting doesn't exist at all. Rather, I'd expect it to be greyed out with a message saying something akin of "On Windows, only the Git executable is supported right now".

Maybe it is a legitimate bug though if hiding the menu on Windows was never intended.

**Comment by akshaybabloo** [comment]
Yeah, that will be something good to have.

**Comment by Byron** [comment]
CC @krlvi  who might know something about this. I vaguely remember that at some point Windows started defaulting to using the executable, so maybe the whole UI element was removed then?

**Comment by krlvi** [comment]
@Byron you are correct - on windows there are no config options to choose from. We can either update the docs or have the thing grayed out instead of being absent on windows. I am leaning towards updating the docs though, because those other auth mechanisms cant be supported on windows (at least not with libgit2)

**Comment by Byron** [comment]
Thanks! Indeed, the issue is about the usability of the documentation. When it's updated, the issue should be resolved.

**Comment by krlvi** [comment]
I have updated the docs with this PR https://github.com/gitbutlerapp/gitbutler-docs/pull/25
