### ISSUE TITLE
The problem of setting the remote branch name to Chinese

### ISSUE THREAD

**Issue by hanchao0606** [gitbutlerapp/gitbutler#4187]
### Version

0.5.561

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

"Set remote branch name" is set to empty in Chinese
![1719367523249](https://github.com/gitbutlerapp/gitbutler/assets/22366546/82f53f46-f08a-4c57-9390-3223c5269ca0)
![1719367573888](https://github.com/gitbutlerapp/gitbutler/assets/22366546/ac611776-ed53-4793-af42-3a144c7da909)

**Comment by Byron** [comment]
That's probably related to incorrect handling of unicode in the frontend.

Git has no problem with unicode branch names, so this will work fine:

```
git branch  你好
git branch -d 你好
```

The same should be true for remotes, so there is no reason to not handle this.

On another note, let me tell you that I absolutely appreciate your sharing of issues here - it's super-important to write international software and I think once GitButler works for you, it will work for most. We'd probably still need more testers from areas that have right-to-left writing, but we will get there :).

**Comment by PavelLaptev** [comment]
@hanchao0606 thank you for your feedback. This issue should be fixed next release 🙂

**Comment by Byron** [comment]
That's great to hear! Let's close it pre-emptively, now that I am here, but kindly ask @hanchao0606 to reopen if the issue persists.
