### ISSUE TITLE
Erratic scroll while dragging file

### ISSUE THREAD

**Issue by mtsgrd** [gitbutlerapp/gitbutler#4368]
When I drag a draggable over to the right it scrolls erratically. I have confirmed these are firing are as expected, so I'm wondering if we have any scroll related CSS at play?

https://github.com/gitbutlerapp/gitbutler/blob/1e68325185e377738ab5b6e38de97007a6893cde/app/src/lib/dragging/draggable.ts#L121-L125

https://github.com/user-attachments/assets/d2a0937e-6ae2-4675-b3d3-9d302d0d7d5c

**Comment by mtsgrd** [comment]
@PavelLaptev any chance you know what could be causing this?

**Comment by PavelLaptev** [comment]
I also experienced the same issue, I'll take a look.

**Comment by PavelLaptev** [comment]
@mtsgrd, could you please check if you still have the issue?

**Comment by mtsgrd** [comment]
It's fixed! Thank you.
