### ISSUE TITLE
Profile picture doesn't show

### ISSUE THREAD

**Issue by dr-wahrheit** [gitbutlerapp/gitbutler#4377]
### Version

0.12.9

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

I changed my profile picture in the Profile tab, but the image doesn't show.
<img width="295" alt="image" src="https://github.com/user-attachments/assets/9007d792-08a8-482e-9fe5-2cc4118d8510">

### How to reproduce

1. Open the Profile tab.
2. Click on the edit button over the image box.
3. Choose an image and upload it.

### Expected behavior

I should be able to view the picture.

### Relevant log output

```shell
[Error] Refused to load https://i1.wp.com/cdn.auth0.com/avatars/st.png?ssl=1 because it does not appear in the img-src directive of the Content Security Policy.
[Error] Failed to load resource: Redirect was not allowed (136efaae81bb53df83e4785939f2f6b9, line 0)
[Error] Cannot load image https://s.gravatar.com/avatar/136efaae81bb53df83e4785939f2f6b9?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fst.png due to access control checks.
[Error] Refused to load https://i1.wp.com/cdn.auth0.com/avatars/st.png?ssl=1 because it does not appear in the img-src directive of the Content Security Policy.
```

**Comment by ndom91** [comment]
> Thanks a lot for reporting!
> 
> This clearly is a result of #4312 and I wonder if the web-client portion of the frontend can be made to allow fetching these resources. Maybe @ndom91 has ideas, too.

Thanks for tagging me Byron. We talked about this on discord some more yesterday and I think we're gonna add the wp domain to our CSP. It seems to come from auth0 fallback avatars

**Comment by ndom91** [comment]
@dr-wahrheit we've updated the image loading rules, this should be available in the next nightly release tomorrow morning at the latest (0.5.611) [here](https://app.gitbutler.com/download) or the next GA release `0.12.12`

**Comment by dr-wahrheit** [comment]
Hi! 

I downloaded the release 0.12.12. 
Now I can see my initial on the profile image,  
<img width="148" alt="immagine" src="https://github.com/user-attachments/assets/adc857f0-1943-4b90-9419-8934fbc50da9">

but if I try to upload a new profile image I get this error:

<img width="970" alt="immagine" src="https://github.com/user-attachments/assets/716216bc-4689-457c-83d2-2036ee74f827">

**Comment by Byron** [comment]
Thanks for letting us know! Let's reopen this as the new issue seems very much like the old one, with some added strangeness. The URL `tauri::localhost/<UID>` definitely seems odd, I'd expect the port along with the host. Maybe that's part of the reason it doesn't work?
