### ISSUE TITLE
Empty project history not handled

### ISSUE THREAD

**Issue by JMonsorno** [gitbutlerapp/gitbutler#4427]
### Version

0.12.12

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

On adding (or re-adding for testing) a repo/project to GitButler, if the "Project history" icon is clicked before there is real project history done there is a console error.
![image](https://github.com/user-attachments/assets/9b5b2809-9f68-498f-b317-ce21980beb0d)

Found while testing enhancement change and noticed is still present in current version, have a planned fix for history.ts

### How to reproduce

- Adding (or re-adding for testing) a repo/project to GitButler
- Click "Project history" immediately after adding project

### Expected behavior

Empty History, no console error logged.

**Comment by Byron** [comment]
Thanks for reporting!

Please note that despite trying, I was unable to reproduce the issue on 0.12.12.

> [..] have a planned fix for history.ts

Thank you, looking forward to it!
