### ISSUE TITLE
Mispelled Toast: Copied to cliboard

### ISSUE THREAD

**Issue by jdewar** [gitbutlerapp/gitbutler#4478]
### Version

0.12.14

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When clicking on a commit's sha, the copy button displays a toast with the title's misspelling.

### How to reproduce

Have a commit in a remote branch, mouse over the sea and click the copy icon that appears.  

### Expected behavior

Toast that shows should say 'Copied to clipboard'

**Comment by Byron** [comment]
Thanks for bringing this up!

Would you like to contribute a fix? The change could be made in the web-editor right here: https://github.com/gitbutlerapp/gitbutler/edit/master/app/src/lib/utils/clipboard.ts#L10 .

Thanks for your consideration.
