### ISSUE TITLE
Hope to publish Chinese version

### ISSUE THREAD

**Issue by webvs2** [gitbutlerapp/gitbutler#4484]
### Version

0.12.5

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

Hope to publish Chinese version

### How to reproduce

no

### Expected behavior

no

### Relevant log output

```shell
no
```

**Comment by Byron** [comment]
Could you explain more?

Do you mean a localised version of the application? Or is it related to making the current builds more accessible or available in China?

Thanks for your help.

**Comment by webvs2** [comment]
Sorry, my description is a little short, I need to have a setting that can switch languages, so that I can use the software in my own suitable language, and I noticed that the construction description of the library is a little short, because yesterday I wondered whether I could modify the configuration file to build a Chinese version of the software, which is my idea.
Finally, thank you for your quick response

**Comment by Byron** [comment]
Thank you! For that one would need support for internationalization, groundwork that isn't yet laid out as far as I know. In a second step, a Chinese translation could be added.
It would probably be useful to have such support early as it would enable the community to contribute translations over time.

**Comment by webvs2** [comment]
> Thank you! For that one would need support for internationalization, groundwork that isn't yet laid out as far as I know. In a second step, a Chinese translation could be added. It would probably be useful to have such support early as it would enable the community to contribute translations over time.

I wonder if I can organize the development of a project or contribute to the introduction. I see that the interface is built by front-end technology. Perhaps I or others can contribute to start the internationalization process

**Comment by Byron** [comment]
I think there is no harm in getting GitButler ready for internationalization. I recommend creating a draft PR early for early feedback by the frontend-team.
