### ISSUE TITLE
The "new version available" popup has a non-functional close button.

### ISSUE THREAD

**Issue by JohnDowson** [gitbutlerapp/gitbutler#4559]
### Version

0.12.15

### Operating System

Linux

### Distribution Method

deb (Linux)

### Describe the issue

The "new version available" popup has a non-functional close button.

**Comment by Byron** [comment]
Thanks for reporting - I could also reproduce this with Version 0.5.626 (20240724.145529).

Also CC @ndom91, who can probably fix it in a jiffy.

**Comment by ndom91** [comment]
We shipped [a fix](https://github.com/gitbutlerapp/gitbutler/pull/4555) for this just last night actually 😊. 

Can you try the latest nightly (0.5.636) [here](https://app.gitbutler.com/download) and let us know if you're still running into this?

**Comment by JohnDowson** [comment]
Works fine on 12.20
