### ISSUE TITLE
Empty list of stashed conflicting branches

### ISSUE THREAD

**Issue by gwilymatgearset** [gitbutlerapp/gitbutler#4567]
### Version

0.12.16

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

![image](https://github.com/user-attachments/assets/7ba61901-fe00-472d-affc-e772ad66d81d)

### How to reproduce

There was a merge conflict in one of my virtual branches (I had 4 at the time, 2 which didn't conflict, 1 was integrated and the conflicting one).

Pressed the update button and got this modal.

I'm not sure if it is necessary, but the branch itself was filtered out of the branch view because it is considered inactive and I had that filter enabled.

### Expected behavior

Include the names of the branches which had merge conflicts.

**Comment by Byron** [comment]
Thanks for reporting.

Note that #4472 is the same error message, but let's keep both issues in case this helps with reproduction.
