### ISSUE TITLE
Allow drag and drop of a changed file

### ISSUE THREAD

**Issue by koppor** [gitbutlerapp/gitbutler#4568]
### Version

0.12.9

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

Intuitively, I wanted to drag and drop a change into a new virtual branch. However, this did not work. I need to drag a change file from the column "Changed files" and cannot drag from the column showing the changes of the changed file. When dragging from the heading "cleanup-pr.yml", it should have the same effect as dragging from "cleanup-pr.yml" in the "Changed files"

![grafik](https://github.com/user-attachments/assets/ac898b43-7916-40f2-9052-3ea7f043305e)

### How to reproduce

1. Fresh cloned repo
2. Fresh git butler usage
3. Create one change
4. Try to drag and drop

### Expected behavior

Drag and drop works

**Comment by mtsgrd** [comment]
Hey, thanks for reporting this. I think it's already been addressed in https://github.com/gitbutlerapp/gitbutler/pull/4546 and will be part of the next release. Closing this issue proactively, but please re-open if there's still a problem after the next update!
