### ISSUE TITLE
After "Integrated" status, the button "Create PR" should be "Delete"

### ISSUE THREAD

**Issue by koppor** [gitbutlerapp/gitbutler#4571]
### Version

0.12.16

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

GitButler perfectly shows that a virtual branch is integrated:

![grafik](https://github.com/user-attachments/assets/ce7549a3-f94b-4ef7-9ebf-77a3b321f985)

After such an integration, the most natural thing is to delete the Virtual Branch.

However, the prominent activity is "Create PR".

### Expected behavior

The button "Create PR" should switch to "Delete".

Maybe switching the expansion of the buttons as follows:

![grafik](https://github.com/user-attachments/assets/3b43b81a-ff73-4102-a475-4b4fe9cf3978)

**Comment by mtsgrd** [comment]
Hey, thanks for bringing this up. I agree that it's a bit odd we suggest you create a PR for an integrated branch. In most cases (at least for me) deleting the branch isn't necessarily what you want to do since that removes the changes from your working directory. Instead, updating your base will remove the branch without affecting said changes on disk.

As a start I think it would make sense if we don't show the PR button when a branch has been integrated. Going a step further, I wonder if @PavelLaptev has any thoughts on how we could make it more obvious that "this branch is done, it will be automatically removed when you update your base"?

**Comment by PavelLaptev** [comment]
The current design allows creating a new PR on an already integrated branch.

You can view the flow in [Figma](https://www.figma.com/design/FbeLt0yjY9RiNn8MXUXsYs/Client-design?node-id=4125-32756&t=f3VjO40fn08eV7hL-1). The app follows the same approach.

<img width="2391" alt="image" src="https://github.com/user-attachments/assets/f417a54f-3d96-40ed-af4b-f3a47bd6745d">

But, it seems like we might want to disable any actions on an integrated branch, except deletion. If creating PRs isn’t allowed, it might also make sense to prevent making and committing changes to the branch.

Should we consider something like this draft?

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/e0e72ea8-1410-415d-a17a-2b9194d41ab9">

**Comment by dougkusanagi** [comment]
I would like to know if there is something else to do to make the branch merged to be deleted. All branches of any projects that i commit, push and merge the PR with Gitbutler still in the local workspace and i have to remove them manually. I think is relatable with this issue, if its not just let me know and i open a new one.

## Version
0.12.20

## Operating System
Windows

## Distribution Method
msi (Windows)

**Comment by PavelLaptev** [comment]
> I would like to know if there is something else to do to make the branch merged to be deleted.

After clicking the red 'update' button, the merged branch should disappear. If it doesn't, it might be a bug. I also think there should be a 'delete' button on the integrated lane.

https://github.com/gitbutlerapp/gitbutler/issues/4571#issuecomment-2294939172

@mtsgrd wdyt?

**Comment by koppor** [comment]
I am very open to close the issue. Last time I worked with GitButler, the branch column disappears after "update". 

OK, sometimes too many columns, but this is another issue: https://github.com/gitbutlerapp/gitbutler/issues/4785

**Comment by krlvi** [comment]
> I am very open to close the issue. Last time I worked with GitButler, the branch column disappears after "update".
> 
> OK, sometimes too many columns, but this is another issue: #4785

Thanks for reporting this! Closing now
