### ISSUE TITLE
[Remote branch name] dialog closed after releases left button outside the dialog

### ISSUE THREAD

**Issue by cheng-liven** [gitbutlerapp/gitbutler#4582]
### Version

0.12.16

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

The dialog closes when releases left button outside the dialog regardless of text selection.

### How to reproduce

1. "Set remote branch name"
2. Drag mouse cursor to select the prefilled text, do not release the left button and keep moving the cursor
3. Release mouse left button while cursor is outside the dialog (overshoot the selection)

### Expected behavior

Four changes:

1. Do not close the dialog if left button released outside the dialog 
2. Text inside input should be selected and focused by default when open the dialog, so you can type new branch name directly after open the dialog.
3. Press `Esc` key should close the dialog.
4. Press `Enter` should confirm the change and close the dialog

**Comment by Byron** [comment]
Thanks a lot for reporting!

@ndom91 would probably make short work of it.

**Comment by ndom91** [comment]
Thanks for pointing this out! I was able to reproduce it on the lastest nightly as well (`0.5.641`).

I'll fix this shortly :pray:

**Comment by ndom91** [comment]
@cheng-liven this was just fixed in #4597 and will be released at the latest with the nightly build tonight. You can check out https://app.gitbutler.com/downloads to get the latest version then :pray: 

Feel free to open a new issue if you're still having issues with it then.
