### ISSUE TITLE
Inconsistent Sidebar Width When Collapsed

### ISSUE THREAD

**Issue by patelka2211** [gitbutlerapp/gitbutler#4656]
### Version

0.12.17

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When the sidebar is collapsed, its width varies depending on the active tab. Specifically, the width is inconsistent between the `Workspace` tab and the `Project settings` tab. This discrepancy results in a visually uneven interface and can impact the overall user experience.

Example:
![sidebar-project_settings](https://github.com/user-attachments/assets/29340665-181e-44d6-a639-536f54526bc4)
![sidebar-workspace](https://github.com/user-attachments/assets/3cd9487e-df14-4c44-93cb-7ae6d3327df5)

### Expected behavior

The width of the sidebar, when collapsed, should be consistently 68px regardless of which tab is active. This consistency will ensure a uniform and predictable layout.

**Comment by Byron** [comment]
Thanks for reporting! I admire your attention to detail!

CC @PavelLaptev .

**Comment by patelka2211** [comment]
You’re welcome! I appreciate your kind words. :)

**Comment by patelka2211** [comment]
Closing this issue now since it’s resolved with the release of v0.12.18.
