### ISSUE TITLE
Renaming an applied branch

### ISSUE THREAD

**Issue by mtsgrd** [gitbutlerapp/gitbutler#4666]
I applied a branch written by someone other than me, then renamed it to disassociate it from the original. In the left-hand branch list the original still shows as applied. It feels buggy, but.. there seems to be something unclear in the UX of what it means to rename a branch. Off the top of my head I would suggest:

1. remote exists -> no remote exist => warn user and ask for confirmation of to disassociate from upstream
2. remote exists -> remote exists => warn the user and ask for confirmation of replacing upstream association
3. no remote exists -> remote exists => warn the user and ask for confirmation of adding upstream association
4. no remote exists -> no remote exists => no warning

**Comment by mtsgrd** [comment]
@krlvi do you have any thoughts on this?

At the moment I have a situation where I would want to overwrite a remote branch, but I can't attach a virtual branch to an existing remote branch. This used to work a couple weeks back, and I quite liked being able to do that.

**Comment by krlvi** [comment]
This is now implemented with the new stack-u UI
