### ISSUE TITLE
Display branch-authors in sidebar with a form of ellipsis

### ISSUE THREAD

**Issue by Byron** [gitbutlerapp/gitbutler#4675]
### Version

d9d93f21e853d50aef959db9ea77ad9e100442af

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

With the merge of #4673 it's now possible to open the GitLab repository once again and look at the branches. Some of them 'overflow' the amount of listable authors, because there are so many.

<img width="984" alt="Screenshot 2024-08-11 at 20 13 37" src="https://github.com/user-attachments/assets/fd5ac1b4-441f-432f-870d-1c5c001343c7">

<img width="388" alt="Screenshot 2024-08-11 at 20 13 43" src="https://github.com/user-attachments/assets/720359d5-a3d4-45e4-9e66-f86107bc4bf8">

I don't think it looks particularly good if they are cutoff like that, and would find it more practical to see  some form of ellipsis, maybe even something like `…XX more`.

### How to reproduce

Clone the GitLab repository with `git clone https://gitlab.com/gitlab-org/gitlab`, add it to GitButler, and scroll down through the branch-list until one of these 'big' branches is found.

**Comment by Byron** [comment]
Please feel free to close this @PavelLaptev in case this was desired though.

**Comment by PavelLaptev** [comment]
@Byron thanks for noticing. Yes, it's something I want to fix :-)

**Comment by PavelLaptev** [comment]
@Byron could you please check the PR https://github.com/gitbutlerapp/gitbutler/pull/4676

**Comment by Byron** [comment]
Thank you, loving it ❤️!

**Comment by PavelLaptev** [comment]
Cool 🙂 Thank you!
