### ISSUE TITLE
UI Not loading properly.

### ISSUE THREAD

**Issue by Wolverin-e** [gitbutlerapp/gitbutler#4679]
### Version

0.12.19

### Operating System

Mac OS X

### Distribution Method

dmg (Intel)

### Describe the issue

My UI is not loading properly
<img width="1272" alt="Screenshot 2024-08-12 at 7 28 11 PM" src="https://github.com/user-attachments/assets/5459998f-f047-4b0b-9402-a5a3689568cd">
<img width="1272" alt="Screenshot 2024-08-12 at 7 28 20 PM" src="https://github.com/user-attachments/assets/d55aac24-d585-4b13-ae85-9f61f21bc928">
![Screenshot 2024-08-12 at 7 31 27 PM](https://github.com/user-attachments/assets/f260ff2a-363b-4399-804d-af4787ccf715)
![Screenshot 2024-08-12 at 7 31 37 PM](https://github.com/user-attachments/assets/c3371232-0a1b-4254-ba9f-e23fee340ec1)
<img width="1272" alt="Screenshot 2024-08-12 at 7 26 59 PM" src="https://github.com/user-attachments/assets/dc23e151-ad79-4f38-893e-abefd5103b3a">
<img width="1272" alt="Screenshot 2024-08-12 at 7 27 08 PM" src="https://github.com/user-attachments/assets/2b322780-7a0f-416a-b0f0-7c15c9716510">
<img width="1272" alt="Screenshot 2024-08-12 at 7 27 29 PM" src="https://github.com/user-attachments/assets/12e79ba9-a520-413c-a6b6-75cc743dc2d2">
<img width="1272" alt="Screenshot 2024-08-12 at 7 27 58 PM" src="https://github.com/user-attachments/assets/e32fdd21-4a93-4957-baaf-f9c1afd4acba">

### How to reproduce

- Download Latest Mac Intel DMG
- Install (Ui does not look well here as well)
- Clone a Repository (Ui does not look & work well)

### Expected behavior

The UI should Look & work like as shown in the video
https://youtu.be/PWc4meBj4jo?si=WX5sleIMW5LX6LT5

### Relevant log output

```shell
[Error] ipc->list_branches: {"projectId":"f2324790-4fa2-4cf7-9f1f-9ececc79469f","filter":{}} (2)
Error: There is no default target
Object
	(anonymous function) (ipc.wSV4mBKh.js:1:1046)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] 347daf116d584846b5be7cb08cf9b6ec: There is no default target

o@tauri://localhost/_app/immutable/chunks/ipc.wSV4mBKh.js:1:691
fromError@tauri://localhost/_app/immutable/chunks/ipc.wSV4mBKh.js:1:860
@tauri://localhost/_app/immutable/chunks/ipc.wSV4mBKh.js:1:1022
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

	N (app.4MuxQ0qP.js:6:205)
	(anonymous function) (app.4MuxQ0qP.js:3:3158)
[Error] Unhandled Promise Rejection: Error: There is no default target
	(anonymous function) (groupBy.DTzsBiCl.js:1:17281)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] ipc->list_remote_branches: {"projectId":"f2324790-4fa2-4cf7-9f1f-9ececc79469f"} (2)
Error: There is no default target
Object
	(anonymous function) (ipc.wSV4mBKh.js:1:1046)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] ipc->list_branches: {"projectId":"f2324790-4fa2-4cf7-9f1f-9ececc79469f","filter":{}} (2)
Error: There is no default target
Object
	(anonymous function) (ipc.wSV4mBKh.js:1:1046)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] 5d68025459454c3abc3a12e613b26048: There is no default target

o@tauri://localhost/_app/immutable/chunks/ipc.wSV4mBKh.js:1:691
fromError@tauri://localhost/_app/immutable/chunks/ipc.wSV4mBKh.js:1:860
@tauri://localhost/_app/immutable/chunks/ipc.wSV4mBKh.js:1:1022
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

	N (app.4MuxQ0qP.js:6:205)
	(anonymous function) (app.4MuxQ0qP.js:3:3158)
[Error] Unhandled Promise Rejection: Error: There is no default target
	(anonymous function) (groupBy.DTzsBiCl.js:1:17281)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] ipc->fetch_from_remotes: {"projectId":"f2324790-4fa2-4cf7-9f1f-9ececc79469f","action":"auto"} (2)
Error: There is no default target
Object
	(anonymous function) (ipc.wSV4mBKh.js:1:1046)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

**Comment by Byron** [comment]
Thanks a lot for reporting!

Since GitButler uses the built-in browser's WebView, I wonder if it relies on more recent versions than are present on your system?

Could you see if what `navigator.userAgent` yields on your system?
Here is the output of mine.

<img width="667" alt="Screenshot 2024-08-12 at 17 32 29" src="https://github.com/user-attachments/assets/2c7fae79-cb5b-41b8-9ffc-a1feab02943c">

Thanks a lot for your help.

**Comment by Wolverin-e** [comment]
Hi @Byron 

I did `navigator.userAgent ` & it looks like this:

<img width="1272" alt="Screenshot 2024-08-13 at 10 35 52 AM" src="https://github.com/user-attachments/assets/f24ecbd7-c93c-4ec4-9db0-ccbc3ed87253">

**Comment by Byron** [comment]
Thank you, that's interesting, it looks like the very same version. Does this mean you are on MacOS 14.6.1 as well?

CC @PavelLaptev - it looks like CSS isn't interpreted correctly, but the browser-engine claims to be the same.

**Comment by ndom91** [comment]
@Wolverin-e can you check your network tab in the dev tools? Are there any CSS files that maybe didn't load correctly?

**Comment by Wolverin-e** [comment]
@ndom91 
I was checking the network tab & I don't think I received any 404s.

Here is the HAR Export from my Network Tab: (I performed a No-Cache Hard Reload before recording the activity)
[localhost.har.zip](https://github.com/user-attachments/files/16600497/localhost.har.zip)


Screenshots:
<img width="1552" alt="Screenshot 2024-08-13 at 7 23 20 PM" src="https://github.com/user-attachments/assets/c44b9ea9-a477-4095-9103-c85939a5a6e7">
<img width="1552" alt="Screenshot 2024-08-13 at 7 23 29 PM" src="https://github.com/user-attachments/assets/692279ab-32d9-4584-879e-f746b06e53a0">
<img width="1552" alt="Screenshot 2024-08-13 at 7 23 58 PM" src="https://github.com/user-attachments/assets/b6833a32-c099-4b45-9b6b-407c35431f88">
<img width="1552" alt="Screenshot 2024-08-13 at 7 24 04 PM" src="https://github.com/user-attachments/assets/19da708d-4205-441a-8592-6a22e8235b32">

**Comment by Byron** [comment]
> > Thank you, that's interesting, it looks like the very same version. Does this mean you are on MacOS 14.6.1 as well?
> > CC @PavelLaptev - it looks like CSS isn't interpreted correctly, but the browser-engine claims to be the same.
> 
> @Byron my MacOS version is: `12.0.1`

Thanks! Then my best guess would be that the browser engine used here is 'somehow' old enough to not understand some of the CSS the way it should?

When I check `Safari -> About` I see `Version 17.6 (19618.3.11.11.5)` - is it the same as yours?

**Comment by ndom91** [comment]
> > Thank you, that's interesting, it looks like the very same version. Does this mean you are on MacOS 14.6.1 as well?
> > 
> > CC @PavelLaptev - it looks like CSS isn't interpreted correctly, but the browser-engine claims to be the same.
> 
> @Byron my MacOS version is: `12.0.1`

Looks like MacOS 12.0.1 corresponds to safari ~15.1 (https://tauri.app/v1/references/webview-versions/#webkit-versions-in-safari). 

You're right, this probably doesn't support some of the more modern css features that are being used.

**Comment by Wolverin-e** [comment]
@Byron @ndom91 
`Safari → About` shows: `Version 15.1 (17612.2.9.1.20)`

**Comment by PavelLaptev** [comment]
probably related https://github.com/gitbutlerapp/gitbutler/issues/2878

**Comment by PavelLaptev** [comment]
Closing this one since we havent heard back in a while. Feel free to open a new issue if anything else arises
