### ISSUE TITLE
Visual conflict resolution interface

### ISSUE THREAD

**Issue by LovesAsuna** [gitbutlerapp/gitbutler#4681]
### Version

0.12.19

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Are there any plans to update a visual conflict resolution interface? Ideally, I’m looking for a conflict resolution tool integrated into the IDE, similar to JetBrains, or a UI tool like Fork or GitKraken.

**Comment by Byron** [comment]
Thanks a lot for asking! Maybe @krlvi knows the answer.

Meanwhile, I'd like to mention #3048 as one way of dealing with this would be to make the conflicts available in Git so existing tools can be used to resolve them.

**Comment by LovesAsuna** [comment]
If the target branch(master) conflicts with the virtual branch(workspace), does that mean we can't resolve it using other tools?

**Comment by Byron** [comment]
Actually, that's exactly how it works today - one sees conflicts markers in the worktree files and can resolve them there.

**Comment by LovesAsuna** [comment]
Does this mean I can merge the integration branch with the master and resolve conflicts?

**Comment by Byron** [comment]
Yes, that is the intended workflow.

**Comment by LovesAsuna** [comment]
Is the “GitButler Integration Commit“ in the integration branch something we don't need to pay attention to? I'm concerned that merging might affect it.

**Comment by Byron** [comment]
It's an artificial and 'managed' commit which is used to show which virtual branches are currently visible, but it won't itself be subject to traditional merges (as long as the user doesn't run `git merge` manually, that is).

**Comment by LovesAsuna** [comment]
Since gitbutler's branches seem to be named randomly, using other tools for conflict resolution and then cutting back to gitbutler doesn't work
<img width="295" alt="image" src="https://github.com/user-attachments/assets/8ae3e166-4f5b-460b-9bbe-1ea289ce531f">

**Comment by Byron** [comment]
I don't think that using Git manually on any of these branches is the intended workflow. From what I can tell, if a conflict is detected, one can enter 'edit mode' to and resolve the conflict. Tools are guided by an index which indicates the conflicts. When resolved, in GitButler one can exit edit mode and pick up the latest version of the worktree and mark the conflict as resolved.

Probably I am missing something though, and would need details on the workflow you are employing.

**Comment by LovesAsuna** [comment]
This actually brings me to the multiple working branches I mentioned earlier, where I'm rebasing one working branch against another, which gitbutler doesn't have the ability to do at the moment
