### ISSUE TITLE
I can't commit files

### ISSUE THREAD

**Issue by danielo515** [gitbutlerapp/gitbutler#4726]
### Version

0.12.20

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Hello. I'm in a situation where I can't commit.
I see a file in my staging area which is not in the remote branc (it does not appear on the PR). Every time I commit, the commit appears with 0 files and the file still appears as uncommited. 

### How to reproduce

I have no idea. Here is a screenshot of where I am stuck: 
<img width="1275" alt="Screenshot 2024-08-21 at 08 43 23" src="https://github.com/user-attachments/assets/223802e1-dbe9-4781-8037-89f6dc943d20">

Here are two screenshots, before and after commiting, as you can see, the file is not included: 
<img width="481" alt="Screenshot 2024-08-21 at 08 51 15" src="https://github.com/user-attachments/assets/6b05fdfa-32f6-48c3-a69a-889f206418e4">
<img width="473" alt="Screenshot 2024-08-21 at 08 51 25" src="https://github.com/user-attachments/assets/63c563c8-48ea-4167-bb45-1b5ddd0d1880">

### Expected behavior

I want the file to be committed so I can push it to my remote.
Also, empty commits should be discouraged with a confirmation message or something.

**Comment by mtsgrd** [comment]
Hey, thanks for reporting this. I think I know what's going on, that change should likely be locked to the first branch, but is incorrectly marked as independent from previous changes. Could you confirm that committing works if you put it in the other lane?

I'm going to take a stab at fixing this as soon as possible.

**Comment by danielo515** [comment]
Hello.
I was not able to test this specific instance of the problem, but today I run into the same issue again.
Indeed moving it back to the "original lane" (the default branch) allowed me to commit it properly.
Not sure what causes them to be "linked to a previous commit", I thought my change was quite independent. I guess it was not that much.

**Comment by mtsgrd** [comment]
This issue should be fixed in release 0.13.8.
