### ISSUE TITLE
Wrong shortcuts for zoom on non-US keyboards

### ISSUE THREAD

**Issue by H1ghBre4k3r** [gitbutlerapp/gitbutler#4733]
### Version

0.12.20

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When trying to zoom on a non-US keyboard via `CMD +/-`, nothing changes (at least not the desired behaviour, most of the times). 
On a German keyboard, however, `CMD ß` zooms out and `CMD ´` zooms in. On a Swedish keyboard, `CMD +` zooms out.

### How to reproduce

Use a non-US keyboard and try to zoom. Nothing will happen. 

### Expected behavior

`CMD +` and `CMD -` should zoom in and out, respectively.

**Comment by H1ghBre4k3r** [comment]
The issue seems to be related to incorrect mapping of codes on international keyboards: 
<img width="1517" alt="image" src="https://github.com/user-attachments/assets/41ef6772-1538-4a67-a6d4-b8c2213994ad">

However, [tinykeys](https://github.com/jamiebuilds/tinykeys) also allows us to create mapping for keys (e.g, `-` instead of `Minus`). This should be a reasonable fix for that.

**Comment by Byron** [comment]
Thanks for letting us know and for the additional research!
