### ISSUE TITLE
Enter at beginning of a line should move text

### ISSUE THREAD

**Issue by koppor** [gitbutlerapp/gitbutler#4790]
### Version

0.12.21

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

<kbd>Enter</kbd> should move text

### How to reproduce

1. Add something in the first line of commit message
2. Press <kbd>Pos1</kbd>
3. Press <kbd>Enter</kbd>\
    ![image](https://github.com/user-attachments/assets/841b9adf-6d6e-46f8-a295-ef84b5e86902)
4. Cursor is moved down.

### Expected behavior

Text and cursor should be moved down - and first line empty

**Comment by Byron** [comment]
Thanks for reporting!

I can confirm that the cursor only moves down on enter if the commit text field isn't empty.

I couldn't reproduce the behaviour with `Pos1` (as this key doesn't exist on my keyboard), nor could I reproduce it by moving the cursor to the beginning of the first line by pressing `Ctrl + a` - Enter would work as expected.

Maybe it can be considered a feature not to allow leading with a newline and to disallow moving the cursor down with `Enter` if the textbox is entirely empty. Probably this makes the described behaviour specific to Windows, so I at best partially reproduced it.

**Comment by koppor** [comment]
> I can confirm that the cursor only moves down on enter if the commit text field isn't empty.

Normal text editors move the letters following the cursor to the next line. Before, they move all subsequent lines down by one line. - GitButler just moves the cursor.

**Comment by mtsgrd** [comment]
cc @PavelLaptev

**Comment by PavelLaptev** [comment]
@estib-vega if you have time, could you please take a look :-)

**Comment by estib-vega** [comment]
Merged the fix in https://github.com/gitbutlerapp/gitbutler/pull/4826

**Comment by koppor** [comment]
I confirm that it works.

Now, <kbd>Del</kbd> at the beginning of the line (no issue filed yet; will do as soon as I start missing it) and <kbd>Cursor down</kbd> (https://github.com/gitbutlerapp/gitbutler/issues/5095) should work.
