### ISSUE TITLE
Unable to undo empty and deleted file changes

### ISSUE THREAD

**Issue by Caleb-T-Owens** [gitbutlerapp/gitbutler#4879]
If I've deleted a file or have a file with no contents, I can't right click and use the "discard changes" option

**Comment by Byron** [comment]
I think this is related to #4872, which is about issues discarding changes when a file was locally removed.

**Comment by Caleb-T-Owens** [comment]
I've assigned both to @krlvi

**Comment by krlvi** [comment]
dupe
