### ISSUE TITLE
Does not run on Ubuntu 20.04 due to missing GLIBC 2.32+ libraries

### ISSUE THREAD

**Issue by sglajchEG** [gitbutlerapp/gitbutler#4881]
### Version

0.12.24

### Operating System

Linux

### Distribution Method

deb (Linux)

### Describe the issue

While there is both a deb package and an appimage available for download, git-butler fails to run from both of these due to missing GLIBC 2.32/2.33/2.34 library requirements.

I suspect it is due to this change, changing the target OS the deb/appimage is built against to Ubuntu 22.04.
https://github.com/gitbutlerapp/gitbutler/pull/4767

### How to reproduce

1. Get an Ubuntu 20.04 install
2. Download and install git-butler as either deb or appimage
3. Attempt to run git-butler

### Expected behavior

It launches without issue

### Relevant log output

```shell
Output:

$ git-butler 
git-butler: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by git-butler)
git-butler: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by git-butler)
git-butler: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by git-butler)

Full output of dependency issues:

$ ldd -v /bin/git-butler
...
	Version information:
	/bin/git-butler:
...
		libc.so.6 (GLIBC_2.28) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.29) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.32) => not found
		libc.so.6 (GLIBC_2.33) => not found
		libc.so.6 (GLIBC_2.34) => not found


Package version details:
$ sudo apt-get update && sudo apt install libc6
...
libc6 is already the newest version (2.31-0ubuntu9.16).
```

**Comment by Byron** [comment]
Thanks a lot for reporting!

I think this issue is well-known already, and @ndom91 has the latest information on it. Vague memory suggests this is already fixed or in the process of being fixed, and possibly a fix is already available on [nightly](https://app.gitbutler.com/downloads).

**Comment by ndom91** [comment]
Thanks a lot for reporting. So there's definitely a similar issue I've spent a lot of time investigating regarding the availability of the various versions of `libwebkit2gtk-4.0` on the various versions of Ubuntu. 

As you correctly pointed out, we began using 22.04 to build the release deb, rpm and appimages a few weeks ago. 

But afaik all the required libraries, like `libwebkit2gtk-4.0` and `glibc` should be bundled and shipped with the appimage. Making your locally installed version not matter. Can you confirm that you're getting the same issues with the latest AppImage? 

Ill assign this to myself and take a look tomorrow to see what we can do about the glibc requirement specifically.

**Comment by ndom91** [comment]
I'm able to confirm this issue on my Ubuntu 20.04 VM as well. According to the [tauri v1 docs](https://tauri.app/v1/guides/building/linux/#limitations) we basically have to build it on the lowest version which we want to support. 

So we'd initially upgraded the build CI workflows to Ubuntu 22.04 a few weeks ago, because it used a more recent version of `libwebkit2gtk-4.0` which fixed some CSS bugs and enabled us to use some newer features as well. 

Anyway, I'm building a copy of the nightly with 20.04 based off of the current `master` atm to assess the feasibility of moving back to `ubuntu-20.04`.

**Comment by ndom91** [comment]
I've talked with the team and unfortunately we've decided to no longer support Ubuntu 20.04. That means the latest nightly with support is `0.5.695` and the latest release is `0.12.21` :pray:

**Comment by sglajchEG** [comment]
Thanks for the responses ndom91.
I can confirm that the AppImage as well did not work (with similar `ldd` issues when investigated).
That's unfortunate regarding Ubuntu 20.04 support.
Sadly I don't have control over upgrading in all of my develop environments, so this is a dead end.

Regarding the latest release to support it, _is_ there a way to download an old release number? I was unable to find a way.

**Comment by Byron** [comment]
It's quite sad that due to this, GitButler will loose a certain set of viable platforms. Now I wonder if there is a choice, if dependencies can be configured to support either one or the other. If so, then I could imagine a publishing process where it build the latest release, then patches some manifests, and builds again for older Ubuntu distributions.

Would that technically be possible at all?

**Comment by ndom91** [comment]
@sglajchEG yeah sorry we don't have publically available links for the older versions, but here they are:

### Latest Supported Nightly (`0.5.695`):
- RPM: https://releases.gitbutler.com/releases/nightly/0.5.695-1201/linux/x86_64/git-butler-nightly-0.5.695-1.x86_64.rpm
- AppImage: https://releases.gitbutler.com/releases/nightly/0.5.695-1201/linux/x86_64/git-butler-nightly_0.5.695_amd64.AppImage.tar.gz
- deb: https://releases.gitbutler.com/releases/nightly/0.5.695-1201/linux/x86_64/git-butler-nightly_0.5.695_amd64.deb

### Latest supported stable (`0.12.21`)
- rpm: https://releases.gitbutler.com/releases/release/0.12.21-1199/linux/x86_64/git-butler-0.12.21-1.x86_64.rpm
- AppImage: https://releases.gitbutler.com/releases/release/0.12.21-1199/linux/x86_64/git-butler_0.12.21_amd64.AppImage.tar.gz
- deb: https://releases.gitbutler.com/releases/release/0.12.21-1199/linux/x86_64/git-butler_0.12.21_amd64.deb

Fyi that stable was released only 1 day after that nightly, so they're basically built off of the same code more or less.

**Comment by ndom91** [comment]
@Byron yeah it is unfortunate, but building a separate release that supports those older versions would entail writing a separate CI "Publish" step that runs on Ubuntu20 (vs Ubuntu 22 currently), and then publishing a second set of Linux releases (deb, appimage, maybe rpm?). 

So its not a big technical hurdle, but seeing as we're moving to Tauri v2 very soon, that will only cause more trouble here. As that's built on `libwebkit2gtk-4.1` (as opposed to `-4.0`) and that isn't available in the Ubuntu 20 repos at all apparently :(

**Comment by Byron** [comment]
Thanks for sharing! I see that even though it would be possible, it will be unfeasible in future due to `tauri` 2.0 moving even further away from Ubuntu 20.

**Comment by Byron** [comment]
With the information collected here and the older binaries, would this issue best be closed as 'not planned'?
