### ISSUE TITLE
Error "head invalid" when creating PR

### ISSUE THREAD

**Issue by ukarlsson** [gitbutlerapp/gitbutler#4904]
### Version

0.12.25

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Error when creating PR. It works when I click "Create PR" again, but often I get this error the first time

GitHub validation failed
It seems there was a problem validating the request.

Please see our 
[documentation](https://docs.gitbutler.com/)
for additional help.
head invalid

### How to reproduce

Click "Create PR"

### Expected behavior

![Screenshot 2024-09-13 at 11 38 20](https://github.com/user-attachments/assets/9f29fe8d-7f9a-4119-8e49-079058f03fe3)
Screenshot of error

**Comment by Byron** [comment]
Thanks a lot for reporting!

This is an issue where I have no idea how to approach it, at least assuming that a foundational feature like creating a PR isn't broken for everyone. And that I could validate, as I was able to create a PR without a problem in a private repository.

Can you provide more information that might help to reproduce the issue?

**Comment by ukarlsson** [comment]
Ok many thanks for the response. Any logs I can supply?

It is pretty consistent now that first time I press create PR I get this error, and then the second time it works

**Comment by Byron** [comment]
I think for this interaction, the developer console might have additional logs. You can open it with `Cmd + Opt + i`.
The `head invalid` message is probably created by the API, which means the first time around, the `head` is invalid, the second time it's working. Like a race condition, or something processed out of order.

**Comment by ukarlsson** [comment]
Ok, got info from network console now

Error is

```
{
    "message": "Validation Failed",
    "errors": [
        {
            "resource": "PullRequest",
            "field": "head",
            "code": "invalid"
        }
    ],
    "documentation_url": "https://docs.github.com/rest/pulls/pulls#create-a-pull-request",
    "status": "422"
}
```

Summary
```
URL: https://api.github.com/repos/sanalabs/sierra-platform/pulls
Status: 422
Source: Network
Address: 140.82.121.6:443
Initiator: 
fetch.js:54
```

Request data
```
{"head":"refactor-namespace-processing","base":"master","title":"Update namespace handling in analytics cache refresh","body":"","draft":false}
```

**Comment by ukarlsson** [comment]
When I press create PR again the request body is slightly different, and head is indeed different

```
{"head":"uk/refactor-namespace-processing","base":"master","title":"Update namespace handling in analytics cache refresh","body":"","draft":false}
```

It seem like it is missing `uk/...` prefix the first time

**Comment by Byron** [comment]
That is very interesting, thanks a lot for providing information this detailed!

Maybe @mtsgrd has seen this before, or an idea what it could be.

**Comment by mtsgrd** [comment]
I had a quick look, I think this is the problem: https://github.com/gitbutlerapp/gitbutler/blob/a0b83556d2245202dc810ab5502ea117165a49cc/apps/desktop/src/lib/utils/branch.ts#L3-L5

Called from here: https://github.com/gitbutlerapp/gitbutler/blob/d7c00a0b9fb04188b6c38babd7ddee6174567f31/apps/desktop/src/lib/branch/BranchHeader.svelte#L120-L125

@estib-vega any chance you could fixup the ref name -> branch name function?

**Comment by ukarlsson** [comment]
Thanks, really looking forward to a fix!

**Comment by estib-vega** [comment]
Yes! Taking a look now

Sorry about that @ukarlsson!

**Comment by ukarlsson** [comment]
Can I test this fix?

**Comment by estib-vega** [comment]
Hey @ukarlsson, yes you can. This PR should already address your issue https://github.com/gitbutlerapp/gitbutler/pull/4927.

There's another fix still waiting to be reviewed: https://github.com/gitbutlerapp/gitbutler/pull/4928.
For context: That second one will add support for remote names that have slashes in them.

**Comment by ukarlsson** [comment]
Ok, any easy way to download a build with the fix included?

**Comment by estib-vega** [comment]
@ukarlsson The nightly should already have the first change in: [Apple Silicon Nightly Build](https://releases.gitbutler.com/releases/nightly/0.5.753-1282/macos/aarch64/GitButler_Nightly_0.5.753_aarch64.dmg)

**Comment by xyzqm** [comment]
I'm still experiencing this issue on the latest build, and clicking Create PR twice doesn't seem to work either.
