### ISSUE TITLE
Could not install on ubuntu 2024

### ISSUE THREAD

**Issue by emadbaqeri** [gitbutlerapp/gitbutler#4914]
### Version

0.12.25

### Operating System

Linux

### Distribution Method

deb (Linux)

### Describe the issue

I've downloaded the app `.deb` file on the fresh Ubuntu 24.04.1 LTS and want to install it using `sudo apt install ./git-butler_0.12.25_amd64.deb` but I end up with this output from the command:

```sh
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'git-butler' instead of './git-butler_0.12.25_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 git-butler : Depends: libwebkit2gtk-4.0-dev but it is not installable
              Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
### How to reproduce

Download the `.deb` file and try installing it on  Ubuntu 24.04.1 LTS x86_64 using `sudo apt install ./git-butler_0.12.25_amd64.deb`

### Expected behavior

I just want it to install normally as it should.

### Relevant log output

```shell
.-/+oossssoo+/-.               emad@obonto
        `:+ssssssssssssssssss+:`           -----------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 24.04.1 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: 81BF Lenovo ideapad 520-15IKB
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.8.0-44-generic
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 8 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1722 (dpkg), 7 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.2.21
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 46.0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3]
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-dark [GTK2/3]
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: WarpTerminal
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-8550U (8) @ 1.800GHz
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce MX150
      -+sssssssssssssssssyyyssss+-         GPU: Intel UHD Graphics 620
        `:+ssssssssssssssssss+:`           Memory: 2521MiB / 15774MiB
            .-/+oossssoo+/-.
```

**Comment by emadbaqeri** [comment]
I've also checked [this blog post](https://tauri.app/blog/2023/02/03/tauri-2-0-0-alpha-3/) on tauri blog

**Comment by emadbaqeri** [comment]
[this issue](https://github.com/tauri-apps/vue-cli-plugin-tauri/issues/35) also closed but this is true for my case and it's not been resolved

**Comment by emadbaqeri** [comment]
I've also installed the `libwebkit2gtk` using synaptics GUI but still have the issue

![image](https://github.com/user-attachments/assets/ff8e75b1-ac3b-47ca-b8d9-c52daa245448)

**Comment by Byron** [comment]
Thanks a lot for reporting, and for not giving up in getting the installation to work!

@ndom91 also works on Linux and might have an idea as to what might be happening here.

**Comment by ndom91** [comment]
Hey yeah thanks for reaching out. 

Unfortunately Ubuntu 24.04 no longer provides `libwebkit2gtk-4.0` in their repositories. Only the `4.1` version. 

Tauri v1 applications, like ours, require `-4.0` and tauri v2 apps require `-4.1`. 

There is a pinned [issue](https://github.com/tauri-apps/tauri/issues/9662) in the Tauri repository which talks about this specific issue. Long story short, you'll have to install 4.0 manually somehow, or alternatively you could give our AppImage release a shot 🙏

**Comment by emadbaqeri** [comment]
Thanks @ndom91 and @Byron, I'll be using `AppImage` ;)
Is there any plan for migrating from tauri 1.0 to 2.0? If there is I would love to contribute with that

**Comment by ndom91** [comment]
@emadbaqeri yeah actually, we were about to pull the trigger on that upgrade last week ([pr](https://github.com/gitbutlerapp/gitbutler/pull/4789)), but it turns out that the tauri updater plugin changed the way the name of the binary is generated.

This is an issue when updating from v1 to v2 on MacOS, for example, because the app will refuse to finish the upgrade process and launch a binary that is of a different name than the one that's currently running (itself), more details here: https://github.com/gitbutlerapp/tauri/pull/1

**Comment by mbtuckersimm** [comment]
`0.5.849` installed fine for me on Linux Mint 22.

**Comment by soundslocke** [comment]
Same here, the `0.5.849` nightly deb works now for me in Ubuntu 24.04. I had been using the AppImage to work around this.

**Comment by ndom91** [comment]
Okay great, thanks for confirming folks!

I'll close this issue as we've seemingly nailed down the underlying issue and upgraded to Tauri v2.

A quick summary for folks

- Tauri v1 uses `libwebkit2gtk-4.0` and that's only natively supported in Ubuntu 22.04 (or similar) or earlier
- Tauri v2 (which we're on now as of nightly `0.5.841`) is only supported on Ubuntu 22.04 (or similar) and greater

**Comment by Masber** [comment]
Hi, Ubuntu 24.10 not working

```
sudo apt install libwebkit2gtk-4.1-dev
You might want to run 'apt --fix-broken install' to correct these.
Unsatisfied dependencies:
 git-butler : Depends: libwebkit2gtk-4.0-dev but it is not installable
              Depends: libwebkit2gtk-4.0-37 but it is not installable
 libwebkit2gtk-4.1-dev : Depends: libsoup-3.0-dev but it is not going to be installed
                         Depends: libjavascriptcoregtk-4.1-dev (= 2.46.1-0ubuntu1) but it is not going to be installed
                         Depends: gir1.2-soup-3.0-dev
Error: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by ndom91** [comment]
> Hi, Ubuntu 24.10 not working
> 
> ```
> sudo dpkg -i Downloads/GitButler_Nightly_0.5.856_amd64.deb
> Selecting previously unselected package git-butler-nightly.
> (Reading database ... 338697 files and directories currently installed.)
> Preparing to unpack .../GitButler_Nightly_0.5.856_amd64.deb ...
> Unpacking git-butler-nightly (0.5.856) ...
> dpkg: dependency problems prevent configuration of git-butler-nightly:
>  git-butler-nightly depends on libwebkit2gtk-4.1-dev; however:
>   Package libwebkit2gtk-4.1-dev is not installed.
> 
> dpkg: error processing package git-butler-nightly (--install):
>  dependency problems - leaving unconfigured
> Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
> Processing triggers for desktop-file-utils (0.27-2build1) ...
> Processing triggers for hicolor-icon-theme (0.18-1) ...
> Errors were encountered while processing:
>  git-butler-nightly
> ```

Looks like you're missing a dependency, `libwebkit2gtk-4.1-dev`. 

You should be able to install it with `sudo apt install -f`. If not, manually try installing that package with apt
