### ISSUE TITLE
Flickering file preview when clicking between files

### ISSUE THREAD

**Issue by PavelLaptev** [gitbutlerapp/gitbutler#4966]
### Version

dev

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When I click between files in a commit, the file preview flickers — it disappears and then reappears.

Here’s the video capture:

https://github.com/user-attachments/assets/7e6d003e-ed3e-4db0-9bcc-7389129e7ada

Strangely, I can't reproduce this issue when clicking between files in the "Uncommitted Changes" section. It’s probably related to loading somehow.

### How to reproduce

1. Make a local commit with multiple file
2. Click between files to open a preview. You should see the flickering file preview

### Expected behavior

The file preview should stay, only the content inside should be changed

https://github.com/user-attachments/assets/3b0c56d9-c40c-40c1-a801-65da6c2ac5e4

**Comment by PavelLaptev** [comment]
@estib-vega I'm not sure that it's fixable and you can repro this, but can you check this out when you have time?

**Comment by estib-vega** [comment]
@PavelLaptev I see it in the stable version but seems to be fixed. Can't reproduce it in the Dev version nor the Nightly

**Comment by estib-vega** [comment]
Issue seems to have been fixed 👍
