### ISSUE TITLE
Unable to view Target commits with unmerged upstream commits

### ISSUE THREAD

**Issue by ValeraS** [gitbutlerapp/gitbutler#4988]
### Version

0.12.26

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

GitButler doesn't show commits from `Target` if there are unmerged upstream commits.
![image](https://github.com/user-attachments/assets/996e17ee-f45a-49a8-8b78-63fbb57c9a0e)

After updating the Workspace, commits become visible.
![image](https://github.com/user-attachments/assets/f295550c-60d0-46f7-8a5e-4c50b9162e07)

Before version 0.12.26, commits were always visible.

**Comment by Byron** [comment]
Thanks for reporting!

This is a tough one though as I have nearly no idea where to start. It's certainly something with the commit classification logic.

Assuming you have used v0.12.25, then the issue should be somewhere in the set of these commits: https://github.com/gitbutlerapp/gitbutler/compare/release/0.12.25...release/0.12.26 .

**Comment by ValeraS** [comment]
It seems this has already been fixed [here](https://github.com/gitbutlerapp/gitbutler/pull/4985).

**Comment by Byron** [comment]
That would be great! Could you validate it with [the latest nightly](https://app.gitbutler.com/downloads)?

**Comment by ValeraS** [comment]
Yes, it works with the latest nightly.
