### ISSUE TITLE
symbol lookup error when running the AppImage version on my Antix (Debian 11) Linux

### ISSUE THREAD

**Issue by etherealxx** [gitbutlerapp/gitbutler#4996]
### Version

0.12.26

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

got this error when trying to run the AppImage version:
```bash
$ '/home/ethereal/Downloads/Compressed/git-butler_0.12.26_amd64.AppImage'
git-butler: symbol lookup error: /tmp/.mount_git-bub2HuLi/usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: gbm_bo_create_with_modifiers2
```
context : the deb file fails to install on my device, but i'm too lazy to fulfill all the different dependencies so  tried the AppImage version.
another context is that my libwebkit2gtk version is : `libwebkit2gtk-4.0-37_2.44.3-1~deb11u1.0nosystemd1_amd64.deb`

My fastfetch:
```bash
$ fastfetch
       _,met$$$$$gg.           ethereal@ethx
    ,g$$$$$$$$$$$$$$$P.        -------------
  ,g$$P"         """Y$$.".     OS: Debian GNU/Linux bullseye 11.11 x86_64
 ,$$P'               `$$$.     Host: HP Laptop 14s-dk0xxx
',$$P       ,ggs.     `$$b:    Kernel: Linux 5.10.142-antix.2-amd64-smp
`d$$'     ,$P"'   .    $$$     Uptime: 52 mins
 $$P      d$'     ,    $$$P    Packages: 2681 (dpkg)
 $$:      $.   -    ,d$$'      Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'       Display (AUO733C): 1366x768 @ 60 Hz in 14″
 Y$$.    `.`"Y$$$$P"'          DE: icewm
 `$$b      "-.__               WM: IceWM 3.6.0 (Linux/x86_64) (X11)
  `Y$$                         Theme: gtk2 [Qt], Arc-EvoPro2 [GTK2/3]
   `Y$$.                       Icons: Adwaita [Qt], papirus-antix [GTK2/3]
     `$$b.                     Font: qt5ct [Qt], Ubuntu (10.5pt) [GTK2/3]
       `Y$$b.                  Cursor: DMZ-Black
          `"Y$b._              Terminal: roxterm
             `"""              CPU: AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2z
                               GPU: AMD Radeon R2/R3/R4/R5 Graphics [Integrated]
                               Memory: 2.28 GiB / 3.73 GiB (61%)
                               Swap: 65.64 MiB / 6.35 GiB (1%)
                               Disk (]8;;file:////]8;;): 36.34 GiB / 38.63 Gi4
                               Local IP (wlan0): 10.252.133.41/22
                               Battery (Primary): 37% [Discharging]
                               Locale: en_US.UTF-8
```
```bash
$ cat /etc/antix-version
antiX-22_x64-full Grup Yorum 18 October 2022
```
```bash
$ inxi -S
System:
  Host: ethx Kernel: 5.10.142-antix.2-amd64-smp arch: x86_64 bits: 64
  Desktop: IceWM v: 3.6.0 Distro: antiX-22_x64-full Grup Yorum 18 October
    2022
```
```bash
$ cat /sbin/init | 
  awk 'match($0, /(upstart|systemd|sysvinit)/) { print toupper(substr($0, RSTART, RLENGTH));exit; }' 2> /dev/null
SYSVINIT
```

### How to reproduce

- Download and Run the AppImage on a device with the same Antix Linux version as mine, latest update

### Expected behavior

The app runs fine.

**Comment by Byron** [comment]
Thanks a lot for reporting!

These kinds of issues around the AppImage are well-known and seem quite common, and thus far, there is no solution yet, unfortunately.

CC @ndom91, who knows all about it, and maybe even knows that this is a duplicate.

**Comment by etherealxx** [comment]
Yeah i'm well aware of the other AppImage related issue, and after checking, this one has different error message. So i was thinking maybe it's worth opening a new issue. And in my case too, i can't install both version on my Antix laptop, so i currently can't access GitButler besides on my Windows 11 device. Though the deb file one probably related to the tauri v1/v2 thing

**Comment by ndom91** [comment]
Hey sorry for the late response. So that version of `libwebkit2gtk` should definitely work. I'm a little suspicious of the fact that you're lacking systemd though. 

Could you do me a favor and try any other tauri application? For example, this image uploader [EzUp](https://github.com/HuakunShen/EzUp/releases/tag/v0.1.15)? They're also using Tauri v1 and have both appimage and deb's available.

**Comment by etherealxx** [comment]
@ndom91 EzUp runs fine on me, both the deb file and the appimage
![image](https://github.com/user-attachments/assets/9d0f0199-c45b-4a5d-a9e5-eb1737502602)

and yes, my device does not use systemd init

**Comment by ndom91** [comment]
Hmm okay so other Tauri apps work. I was thinking that missing systemd might be a deal-breaker for Tauri applications in general.

I recently had to pin the GHA runner to `libwebkit2gtk` version `2.36.0` for an unrelated issue, but I know that version for sure works. 

Do you have the ability to try that?

**Comment by etherealxx** [comment]
Sadly i can't try that, the previous version available for me is 2.34.2 and even that needs the previous version of several other dependencies, which i afraid to do without potentially breaking my system.

**Comment by ndom91** [comment]
Okay if we can't change the libwebkit2gtk version on your side, you can give the latest nightly a try 😊 

For other reasons, we pinned the version of libwebkit2gtk to an older version in the build env, so it may work for you now as well.

**Comment by etherealxx** [comment]
Trying the nightly builds, the deb file version still can't be installed because of unmet dependencies and things like that (unrelated to this issue), but the AppImage now works, most of the time.
![2024-10-25_21-39](https://github.com/user-attachments/assets/cbf070ed-8ba3-4874-8c92-53a45f755def)
It was a smooth experience until i add a local repo, then it shows these errors
```
d215aa77f73d4d9eb456cf8e717648d3: No secret service provider or dbus session found
s@tauri://localhost/_app/immutable/chunks/ipc.BjY819oU.js:1:734
fromError@tauri://localhost/_app/immutable/chunks/ipc.BjY819oU.js:1:903
@tauri://localhost/_app/immutable/chunks/ipc.BjY819oU.js:1:1111 asyncFunctionResume@[native code] @[native code]
promiseReactionJobWithoutPromise@[native code] promiseReactionJob@[native code]
```
Apparently it shows whenever i do interactions with the branch lanes, like making a new lane or moving items between two. It works as expected, but the error just shows. Could be UI related things.

**Comment by ndom91** [comment]
Okay good to hear it's generally running. The secret store is used to store github login token, for example. 

On my system I used `gnome-keyring` (I believe the pkg was called). Although I'm not sure if that would work in a non-systemd env

**Comment by etherealxx** [comment]
gnome keyring is available and already installed for me before (version 42.1-1+b2), though idk if i need to set it up for this or not

**Comment by ndom91** [comment]
> gnome keyring is available and already installed for me before (version 42.1-1+b2), though idk if i need to set it up for this or not

Hmm okay interesting, when I start gitbutler I get the gnome auth prompt and then all is well. Do you have an xdg-desktop-portal installed? 

Let me double check if there's any additional packages I may have there.

**Comment by etherealxx** [comment]
yes i have xdg-desktop-portal, it says latest version (1.8.1-1). How does the gnome auth prompt looks like? i'm pretty sure i didn't get it. 
Also how do i get the First Time User Experience again? Like as if i installed Gitbutler for the first time (maybe removing something like `.gitbutler` or similiar)

By the way, i'm still using that time's nightly version (0.5.837), it still works for my device. However, the current (today's) nightly (0.5.843) didn't work for me.

```
$ "./GitButler Nightly_0.5.843_amd64.AppImage"
gitbutler-tauri: symbol lookup error: /tmp/.mount_GitButL3Ogm9/usr/lib/libwebkit2gtk-4.1.so.0: undefined symbol: gbm_bo_create_with_modifiers2
```

**Comment by ndom91** [comment]
@etherealxx we've just published the nightly after merging our Tauri v2 update. There's a few things that have changed in there, including a whole different veresion of `libwebkit2gtk` used to build it.

Can you give `0.5.849` a shot? ([app.gitbutler.com/downloads](https://app.gitbutler.com/downloads)) :pray:

**Comment by etherealxx** [comment]
using `0.5.850`, my libc version isn't sufficient. It crashes (force close) the terminal each time i runs it. I captured the output using `$ exec '/home/ethereal/Downloads/Compressed/gitbutler_nightly_0.5.850_amd64.AppImage' 2>&1 | tee /home/ethereal/Downloads/Compressed/gitbutler_log.txt`

```
gitbutler-tauri: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by gitbutler-tauri)
gitbutler-tauri: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by gitbutler-tauri)
gitbutler-tauri: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_gitbutxX2R7J/usr/lib/libwebkit2gtk-4.1.so.0)
gitbutler-tauri: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_gitbutxX2R7J/usr/lib/libwebkit2gtk-4.1.so.0)
gitbutler-tauri: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /tmp/.mount_gitbutxX2R7J/usr/lib/libwebkit2gtk-4.1.so.0)
gitbutler-tauri: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_gitbutxX2R7J/usr/lib/libwebkit2gtk-4.1.so.0)
gitbutler-tauri: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_gitbutxX2R7J/usr/lib/libgtk-3.so.0)
gitbutler-tauri: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_gitbutxX2R7J/usr/lib/libgtk-3.so.0)
```
and a bunch of similiar message like that. Keep in mind that i'm using `Debian GNU/Linux bullseye 11.11 x86_64` which now entering `oldstable`.

**Comment by ndom91** [comment]
@etherealxx hmm okay yeah that's a fairly old version. Even without the non-systemd complexity, I believe the current `libwebkit2gtk-4.1` is no longer provided / supported by even the Debian vanilla 11 repositories.

**Comment by etherealxx** [comment]
Pretty sad to hear that even though it was working for me at one time. Understandable though.
I suggest maybe probably putting a system requirement for Linux since unlike the other OSes, Linux distros is wide and varied, and this will not be the last time people with old system reporting this kind of problem (they don't know).

**Comment by Byron** [comment]
Thank you! I also would wish that we had a compatibility guide, even if it's just linking to the same in Tauri, maybe along with repercussions and typical error messages so people would more easily find it. Maybe this should even be accessible from the download page or part of compatibility notes in the package people would download just be sure it's right there when needed.

**Comment by ndom91** [comment]
Thanks for the recommendations, that makes a lot of sense. I'll add a Linux support matrix to the docs site.

**Comment by ndom91** [comment]
Unfortunately I couldn't find any useful page in the v1 nor the v2 tauri docs to link to, but I've added the following to our docs website - https://docs.gitbutler.com/releases. Unfortunately I can't put together a comprehensive list of repositories and their versions and which are supported and not, but hopefully folks can get an idea of the issue and if they're curious look up more via the linked Tauri issue :pray:
