### ISSUE TITLE
Add "Zed" as code editor

### ISSUE THREAD

**Issue by louis-sicko** [gitbutlerapp/gitbutler#5038]
When I use Gitbutler with the Zed Editor, I can only open the project in VS Code. It would be nice to have a setting to change the default editor to Zed or others.

**Comment by Caleb-T-Owens** [comment]
Is this hard to do, because I've started using VSCodium and this is bothering me too 😆 ?

**Comment by krlvi** [comment]
Hey @louis-sicko ! Thanks to @xxxoooxoxo and his #5142 it is now possible to set Zed as the "open in" editor :)
This is available in the most recent release https://github.com/gitbutlerapp/gitbutler/releases/tag/release%2F0.13.2
Im closing this issue now, feel free to open a new one if you come up with any ideas or spot bugs
