### ISSUE TITLE
Misleading pop-up alerts for unapply and drop changes

### ISSUE THREAD

**Issue by LovesAsuna** [gitbutlerapp/gitbutler#5088]
### Version

0.12.27

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

<img width="379" alt="image" src="https://github.com/user-attachments/assets/10d2e789-a92e-48c2-a34e-1bd504517655">

The popup will prompt to delete the virtual branch, but this is not actually a delete behavior

**Comment by PavelLaptev** [comment]
@LovesAsuna Thanks for reporting the issue! It should be resolved in the next release :-)
