### ISSUE TITLE
Error "The reference did not exist" while listing branches

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#5144]
Often times this happens on application startup. It has happened to be but also has been reported by users on discord:
https://discord.com/channels/1060193121130000425/1073202153163857920/1293975411684016128
https://discord.com/channels/1060193121130000425/1206670506271707156/1295647968803815424

My hypothesis is that this is a race condition getting `BranchListingDetails` for branches while the app is fetching from the remote

- upon opening the app, in the left sidebar with branches it is trying to show remote branches, and it is progressively fetching branch details for them
- at the same time the app is doing a "fetch"
- some number of those branches were already deleted at the remote, and after the fetch is complete, this is reflected locally too
- so while the app is fetching branch details, it fails to fetch details for the ones that are now gone

NB: It appears that the error is harmless, but it can be quite noisy especially if there were many merged branches

![image](https://github.com/user-attachments/assets/6ef4de83-9f6e-4698-bc1b-382ead54727d)

**Comment by anirudhsama** [comment]
FYI it seems to happen on every app launch as well, even when there are no changes on remote. See recording: https://cln.sh/XTrhxKPj

**Comment by Byron** [comment]
As one would expect, this is [a `gitoxide` error](https://github.com/GitoxideLabs/gitoxide/blob/beba7204a50a84b30e3eb81413d968920599e226/gix/src/reference/errors.rs#L119-L120), but the prefix seems to be added in the frontend, judging [from the `find_reference()` calls in the backend](https://github.com/gitbutlerapp/gitbutler/blob/9175e60e608c1a6933986a3fe67dac6f77d6d4a2/crates/gitbutler-branch-actions/src/branch.rs#L465-L474).

This makes me think that the hex-hash prefix is the name of the branch, but I am not sure.

I could look into this if I could get a hint on how to reproduce the issue.

**Comment by krlvi** [comment]
@anirudhsama have you noticed these on the most recent release?

**Comment by anirudhsama** [comment]
No, this has been fixed. I think it was the same as https://github.com/gitbutlerapp/gitbutler/issues/5229

**Comment by krlvi** [comment]
awesome, thanks for letting us know. feel free to ping if you run into any other issues
