### ISSUE TITLE
Duplicate Entry in Cargo file leads to issues building on nix

### ISSUE THREAD

**Issue by Daholli** [gitbutlerapp/gitbutler#5221]
### Version

0.13.2

### Operating System

Linux

### Distribution Method

deb (Linux)

### Describe the issue

Heyho,

I would like to package the new version on gitbutler on nix, but due to nix unique way of handling packaging, we get build errors due to duplicate entries of cargo

https://github.com/NixOS/nixpkgs/pull/347819

The system wants to symlink the same thing twice but cannot do so, Not sure what causes the duplicated entry of gix-attributes in the cargo lock.

(if you feel like this is way out of specs please ignore my request)

### How to reproduce

Run
```
nix-shell -p nixpkgs-review --run "nixpkgs-review pr 347819"
```

on any a x86_64-linux system with nix installed

### Expected behavior

The package builds fine from source like it did in 0.12.6

### Relevant log output

```shell
building '/nix/store/qksp5w0b861p7cwqjccvgi0viznnpvg8-cargo-vendor-dir.drv'...
ln: failed to create symbolic link '/nix/store/g6krgpmcpqc0bwr26gyn2zp84qlaj4pf-cargo-vendor-dir/gix-attributes-0.22.5/f5fa2yliymrvc2qamkp6b7j5qd9fkrra-gix-attributes-0.22.5': Permission denied
error: builder for '/nix/store/qksp5w0b861p7cwqjccvgi0viznnpvg8-cargo-vendor-dir.drv' failed with exit code 1;
       last 1 log lines:
       > ln: failed to create symbolic link '/nix/store/g6krgpmcpqc0bwr26gyn2zp84qlaj4pf-cargo-vendor-dir/gix-attributes-0.22.5/f5fa2yliymrvc2qamkp6b7j5qd9fkrra-gix-attributes-0.22.5': Permission denied
       For full logs, run 'nix log /nix/store/qksp5w0b861p7cwqjccvgi0viznnpvg8-cargo-vendor-dir.drv'.
error: 1 dependencies of derivation '/nix/store/cl50j785xrp456m5aw5z6l82knlsc6ij-gitbutler-0.13.2.drv' failed to build
```
```

**Comment by Daholli** [comment]
ah... nvm i see what the issue is... it is a depedency that also needs gix but uses a different version, that does not seem like something you guys can fix

**Comment by Byron** [comment]
Thanks a lot for reporting.

Would you be able to share which other dependency is using `gix-attributes` and causes the clash?
What confuses me is how this can happen since this codebase really only uses one copy of `gix` and thus `gix-attributes`.
Thanks again.

**Comment by Daholli** [comment]
I can try to look into it, I just saw that there is a reference to gix master and one to the one from cargo

**Comment by Daholli** [comment]
`argo tree --invert registry+https://github.com/rust-lang/crates.io-index#gix-attributes@0.22.5`

shows me this

```
gix-attributes v0.22.5
└── gix-worktree v0.34.1
    └── gix-testtools v0.15.0
        └── gitbutler-testsupport

```

**Comment by Byron** [comment]
Indeed, this dev-dependency uses a different version of `gix-attributes` primarily because the release system has trouble dealing with this :/.

**Comment by Daholli** [comment]
No worries, then I will try to push the effort on the nix side a little and read up on that, so maybe we can have newer releases of gitbutler again.

**Comment by Byron** [comment]
Maybe it's also possible to 'patch' the manifest to not include dev dependencies? Or do nix packages rely on being able to run tests? But of course, fixing the issue at the source would be better, multiple versions of the same crate can always be used in the same graph.

**Comment by Daholli** [comment]
theoretically I could create a Cargo file that just removes that reference, and it might work. but It would mean that for every release update you need to think about removing it, shortterm that works, longterm that feels like a very tedious thing to do, but ill try to see if this even does something

**Comment by Daholli** [comment]
Tampering with the Cargo.lock file just lead to build errors :D dammit, I guess I have too little knowledge of both rust and nix to properly fix this, I will look how other packages did this, since it has been mentioned a few times but they recieved updates in the end. maybe one of the solutions is feasable for this aswell
