### ISSUE TITLE
Page Jumping and Save Button Not Triggered When Editing AI Prompt

### ISSUE THREAD

**Issue by benjaminmodayil** [gitbutlerapp/gitbutler#5224]
### Version

0.13.2

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When navigating to the AI Prompt create/edit page and interacting with the text input field, the page exhibits unexpected jump scrolling behavior. After updating the prompt and clicking the submit button, the page jumps again, but the save button is not activated, requiring the user to scroll back to manually click it.

https://github.com/user-attachments/assets/9205478b-7f11-4753-92e5-e8d51e9ab128

### How to reproduce

1. Navigate to the AI Prompt create/edit page (or refresh if already on the page before continuing). 
2. Click into the text input for a prompt (notice slight jump).
3. Type an update to the prompt.
3. Click the submit button (notice jump but if you scroll back to the save button it is not clicked).  

### Expected behavior

No jump scrolling on text input changes and when a user tries to click the save button.

**Comment by Byron** [comment]
Thanks a lot for reporting and the nice video - it was easy to reproduce the issue as well.
CC @ndom91 .

**Comment by ndom91** [comment]
@Byron thanks for tagging me, I'm going to pass the hot potato on to @PavelLaptev however for a first glance :blush:

**Comment by PavelLaptev** [comment]
This is fixed :-)
