### ISSUE TITLE
%{branch_name} seemingly does not work within commit messages like docs mention

### ISSUE THREAD

**Issue by benjaminmodayil** [gitbutlerapp/gitbutler#5225]
### Version

0.13.2

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When using %{branch_name} there is no actual replacing and those characters are actually just returned.

Screenshots show %{diff} result working and then %{branch_name}. Note the branch name is defined when on the Workspace views.

**%{diff} example** (_WORKING ✅_) -- code in diff was manually removed for screenshot purposes
![CleanShot 2024-10-19 at 10 53 48@2x](https://github.com/user-attachments/assets/6ec35d62-6adb-4db4-87c9-fe5985e67147)
![CleanShot 2024-10-19 at 10 55 06@2x](https://github.com/user-attachments/assets/8efd0d19-3964-4b9d-82dc-0c87d1a72b85)

####  **%{branch_name} example** (_BROKEN 💔_)
 
![CleanShot 2024-10-19 at 10 56 29@2x](https://github.com/user-attachments/assets/9ecc6a1f-4990-4dfc-8011-ab7c52467dac)
![CleanShot 2024-10-19 at 10 55 56@2x](https://github.com/user-attachments/assets/35b0f0ee-55ef-42c4-a2f3-441d8b4881b6)

### How to reproduce

Use the AI commit feature to return the value of %{branch_name}

### Expected behavior

According to the [docs](https://arc.net/l/quote/goowzrom):
> %{branch_name} - The name of the current branch. Available in "Commit Message" custom prompt only.

**Comment by Byron** [comment]
Thanks a lot for reporting!

With this issue I am completely out of my element, but think @krlvi would know how to deal with this.
