### ISSUE TITLE
I can not use `Anthropic` models for branch names and commit messages

### ISSUE THREAD

**Issue by h0x91b-wix** [gitbutlerapp/gitbutler#5234]
### Version

0.13.2

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

After update (I do not remember what was previous version)

I can not use `anthropic` models for branch names and commit messages, I see popup with error:

```
Failed to generate commit message
Connection error.
```

In the console I see:

```
Refused to connect to https://api.anthropic.com/v1/messages because it does not appear in the connect-src directive of the Content Security Policy.
```

**Comment by h0x91b-wix** [comment]
OpenAI BTW is working..

**Comment by Byron** [comment]
Thanks a lot for reporting!

I think @ndom91 knows all about possible causes of this.

**Comment by ndom91** [comment]
@h0x91b-wix thanks for reporting! I was able to reproduce this when using ones own Anthropic API Key (as opposed to the GitButler one).

I'll prepare a PR fixing this shortly :+1:
