### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by wereHamster** [gitbutlerapp/gitbutler#5257]
### Version

0.13.4

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Switching to Workspace hangs, because app crashes with $TITLE

In my Safari I get the same error with the regexp:

```
> ''.split(/(?<![A-Z])(?=[A-Z])/)
SyntaxError: Invalid regular expression: invalid group specifier name
```

Safari Version 16.2, macOS 13.1

[Safari added the lookbehind support in 16.4.](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#JavaScript)

The offending function was added in commit https://github.com/gitbutlerapp/gitbutler/commit/43f8fa1b2c9b5ff8d0943e2d46012a15dd6c569e.

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/820b2bfd-1315-4a31-a359-3e42f2197850">

### How to reproduce

I guess you can reproduce when you run the app on the same macOS version as I have.

**Comment by Byron** [comment]
Thanks a lot for reporting!

Let me CC @ndom91 who would probably be in for a quick fix :).

**Comment by wereHamster** [comment]
btw I bit the bullet and upgraded my macOS / Safari, so I won't be able to validate the fix 😬

**Comment by krlvi** [comment]
@ndom91 can we set up a lint rule for this?

**Comment by ndom91** [comment]
> @ndom91 can we set up a lint rule for this?

Yeah I wanted to merge this into the other string utils too, I'll clean this up and look into adding a rule to avoid regex look behind 👍
