### ISSUE TITLE
Randomly redirecting to the onboarding page

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#5314]
For some reason, under unknown conditions, the app redirects users to the onboarding screen, even though they are logged in and have projects. 
Reloading does not fix it but restarting the app does. 

https://discord.com/channels/1060193121130000425/1206670506271707156/1299323747794288650

**Comment by ndom91** [comment]
Just saw this, will take a look tomorrow 👍

**Comment by krlvi** [comment]
this is now fixed
