### ISSUE TITLE
Drop target for commits should be the branch, not the workspace

### ISSUE THREAD

**Issue by ipsquiggle** [gitbutlerapp/gitbutler#5341]
### Version

0.13.7

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

When dragging a commit from one lane to another, the workspace area of the lane gets highlighted. This made me wonder/worry that I was going to "uncommit" the changes into that lane, rather than moving the commit between branches. (It did, in fact, move between branches as desired.)

Minor UX/expectations bug.

### How to reproduce

Have two branches with commits. Drag a change from one branch to the other. Observe that the workspace is highlighted as the drop target, instead of the branch.
![image](https://github.com/user-attachments/assets/48fe1686-a8da-44c8-bf12-0082be08ad19)

**Comment by Byron** [comment]
Thanks a lot for reporting!

In my somewhat pristine lane it also says that commits should be dropped there…

<img width="381" alt="Screenshot 2024-10-28 at 20 56 40" src="https://github.com/user-attachments/assets/c952b354-52c3-4d29-9e9b-89f6c04ccfaa">

…even though I am only allowed to drop them where I should drop files.

<img width="696" alt="Screenshot 2024-10-28 at 20 57 33" src="https://github.com/user-attachments/assets/fbf540d7-81cd-4398-a730-3a35a8388770">

This could be interesting for @PavelLaptev who would know if that's intended or something that should be fixed.

**Comment by PavelLaptev** [comment]
> 
> In my somewhat pristine lane it also says that commits should be dropped there…
>
That's true. We should highlight the section where items will appear after being dropped.

Probably @estib-vega or @ndom91 could take a look 👀
