### ISSUE TITLE
Unable to generate branch name with AI

### ISSUE THREAD

**Issue by cuervolu** [gitbutlerapp/gitbutler#5456]
### Version

0.13.9

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

In the latest update of GitButler, I'm unable to use the "Generate branch name" feature; it seems this issue originates from a file called `SeriesHeader.svelte`.

Also, a quick question: where can I see the version of GitButler in this new update? Since the toolbar is gone, I had to check the GitHub repo to find the latest version.

![image](https://github.com/user-attachments/assets/e95e287f-7d52-4075-98c6-a1ddf655ec28)

### How to reproduce

1. Click the three dots next to the branch you want to name.
2. Select "Generate branch name."
3. A toast will appear with the message "Something went wrong."

### Expected behavior

Mostly, I expect to be able to generate branch names using the AI feature. Also, I think the errors could be clearer. I'm not sure if this error is due to something I did wrong or if it's a bug in the program.

### Relevant log output

```shell
[2024-11-05][21:50:06][Rt@tauri://localhost/_app/immutable/entry/app.BUmR2gS2.js:2:2973][ERROR] 1808d531f25342b2a475e65c81c7a4c9: undefined is not an object (evaluating 'Ft.files.flatMap')

@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2529
@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2516
Et@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2808
onclick@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:585:847
@tauri://localhost/_app/immutable/chunks/Badge.DdS_Bi0-.js:261:137
Ie@tauri://localhost/_app/immutable/chunks/props.eUjFkiCo.js:1:3775

[2024-11-05][21:50:13][Rt@tauri://localhost/_app/immutable/entry/app.BUmR2gS2.js:2:2973][ERROR] 20bf7e00af184ca7b2e61a1e3a442d84: undefined is not an object (evaluating 'Ft.files.flatMap')

@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2529
@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2516
Et@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2808
onclick@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:585:847
@tauri://localhost/_app/immutable/chunks/Badge.DdS_Bi0-.js:261:137
Ie@tauri://localhost/_app/immutable/chunks/props.eUjFkiCo.js:1:3775

[2024-11-05][21:54:04][Rt@tauri://localhost/_app/immutable/entry/app.BUmR2gS2.js:2:2973][ERROR] a27f7bcfb639476ba23b3f6a8d752864: undefined is not an object (evaluating 'Ft.files.flatMap')

@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2529
@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2516
Et@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:800:2808
onclick@tauri://localhost/_app/immutable/nodes/7.CwKfiX2N.js:585:847
@tauri://localhost/_app/immutable/chunks/Badge.DdS_Bi0-.js:261:137
Ie@tauri://localhost/_app/immutable/chunks/props.eUjFkiCo.js:1:3775
```

**Comment by Byron** [comment]
Thanks a lot for reporting!

I have a feeling that this is the same bug as #5460 , even though the error messages seem a little different. For completeness, I linked the PR that fixes an issue with generating branch names, and that should be testable in the next nightly or stable release.

Sorry again for the hassle.

**Comment by krlvi** [comment]
Hey @cuervolu, thank you for reporting this issue! This one is actually different from from #5460
I believe I made a fix for this last night - https://github.com/gitbutlerapp/gitbutler/pull/5458 would you be able to try again with version `0.13.10`? 
Sorry for this disturbance

**Comment by cuervolu** [comment]
Hey @krlvi, thank you very much for the prompt response. Yes, it was indeed fixed in the new update. Thank you for the quick correction!
