### ISSUE TITLE
Unable to generate commit message in 0.13.10

### ISSUE THREAD

**Issue by dhruvanbhalara** [gitbutlerapp/gitbutler#5460]
### Version

0.13.10

### Operating System

Windows

### Distribution Method

msi (Windows)

### Describe the issue

Unable to generate commit message with the latest version in Windows.
I've tried changing AI options as well. In both options it's failing to generate a commit message.

### How to reproduce

install **0.13.10** version in the window MSI build, modify any file and try to generate a commit message based on the content
![image](https://github.com/user-attachments/assets/e4f4d0c1-4126-4084-912a-ae8929dbb932)

### Expected behavior

it should allow generating the commit message, reverting back to **0.13.8** works as expected.

### Relevant log output

```shell
Failed to generate commit message
Failed to fetch
```

**Comment by Byron** [comment]
Thanks a lot for reporting, and sorry for the hassle!

I think this issue will be fixed in the next nightly or the next stable release, please see the linked PR.

**Comment by krlvi** [comment]
Hi @dhruvanbhalara, thank you so much for taking the time to report this. We have merged a fix and a new app release is on the way. Version `0.13.11` will be out in apporx 30 minutes from now with a fix

**Comment by dhruvanbhalara** [comment]
Hi @krlvi,
I've verified the issue with `0.13.1``, and it's now resolved I'm closing this issue.
