### ISSUE TITLE
Sidebar branch entry shows "Lane" instead of the branch name

### ISSUE THREAD

**Issue by cesarameba** [gitbutlerapp/gitbutler#5469]
### Version

0.13.11

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Seems like with the UI change to make branch headers more compact in the UI, gone is the option to rename them? So they have to stay "Lane" forever?
![image](https://github.com/user-attachments/assets/3e4e13e7-5619-4803-b0aa-97580f9a76f3)

**Comment by krlvi** [comment]
Hey there! It is possible to change the name of a branch further down in the lane (clicking into the name field or via the context menu).

You may have identified that currently, in the sidebar what is being displayed ("Lane") is incorrect. You can disregard this for now, as this is cosmetic only (the value is not used). However, this is a bug! A fix is coming later today

<img width="1377" alt="Screenshot 2024-11-06 at 15 41 36" src="https://github.com/user-attachments/assets/2121b28f-f05e-4534-bade-f1971ba18a82">

**Comment by cesarameba** [comment]
Got it, yeah, that's what I'm hitting. I thought they were separate things, but this makes more sense. Thank you so much for responding! Looking forward to the fix.

**Comment by krlvi** [comment]
> Got it, yeah, that's what I'm hitting. I thought they were separate things, but this makes more sense. Thank you so much for responding! Looking forward to the fix.

If you dont mind, i will rename the issue title so that I can more easily track that we fix this asap :)

**Comment by krlvi** [comment]
Resolved in this PR: https://github.com/gitbutlerapp/gitbutler/pull/5463
Will be part of release `0.13.12`

**Comment by krlvi** [comment]
@cesarameba im closing this as completed. thank you for reporting and feel free to create another issue if you run into any other problem
