### ISSUE TITLE
Stuck in a bad state, I can't use gitbutler anymore

### ISSUE THREAD

**Issue by ionTea** [gitbutlerapp/gitbutler#5486]
I've somehow ended up in a bad state, and not sure what to do.
I tried deleting my project and adding it again but it's not doing anything

<img width="1512" alt="Screenshot 2024-11-07 at 14 44 19" src="https://github.com/user-attachments/assets/ef738233-b80d-4779-9bda-a9550e1044a3">

https://github.com/user-attachments/assets/c9a819a0-21be-4d22-838f-7407e61206f2

**Comment by estib-vega** [comment]
Hello @ionTea, sorry for the inconvenience and thanks for reporting!

Looking at the error popup at the bottom right, it looks like the application thinks that you have uncommitted changes in the repo you are trying to open.

Could you confirm whether that's the case?
Executing `git status` from within your repository *should* clarify this.

**Comment by estib-vega** [comment]
Also taking a look at the video, it seems that you're getting some error popups that seem familiar.

What version are you on? And if it is below 0.13.12, could try updating to the latest version of the app?

**Comment by ionTea** [comment]
Now it seems to be working again, not sure what I did. I just switched to my branch and worked using good ol' git old fashioned style.

For the record I am on `Version 0.13.12 (20241106.191107)` and I updated earlier today before this issue arose

**Comment by estib-vega** [comment]
> Now it seems to be working again, not sure what I did. I just switched to my branch and worked using good ol' git old fashioned style.
> 
> For the record I am on `Version 0.13.12 (20241106.191107)` and I updated earlier today before this issue arose

Interesting. Do you still get the `There is no default target` errors?

Glad to hear the other issue is gone, though :)

**Comment by ionTea** [comment]
Before I couldn't even switch to the gitlab branch, but after working on another branch for a while it just started working. Not sure if me doing commits and pushing etc. did something to fix the state I was in but I had no changes according to git when these issues started happening

**Comment by estib-vega** [comment]
Weird 🤔 .
I'll keep an eye out for this kind of errors.

Thanks again for reporting and for helping out with the investigation!

**Comment by estib-vega** [comment]
Seems to have been a flaky state. Closing.
