### ISSUE TITLE
Not allowed multiple applied branches

### ISSUE THREAD

**Issue by bonbon2000** [gitbutlerapp/gitbutler#5585]
### Version

0.13.15

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

No longer allowed multiple branches applied. I use the app to be able to keep applied changes across multiple remote branches. Since latest software update it's broken. As soon as I apply one branch from the workspace list, all current applied branches are unapplied.

**Comment by Byron** [comment]
Thanks a lot for sharing, and I am really sorry to hear that. This sounds like something that is too major to miss :/

Maybe you could try [the latest nightly](https://app.gitbutler.com/downloads) version to see if it's already fixed? If not, would you be able to share a video of the issue, maybe it's possible to reproduce it from that as well.

**Comment by bonbon2000** [comment]
Will close this. Rebooted machine for other reasons and seems to work now. Might have ended up in a weird state after updating Gitbutler.
