### ISSUE TITLE
Commit message character counter - include the message body in the counting

### ISSUE THREAD

**Issue by krlvi** [gitbutlerapp/gitbutler#5594]
https://discord.com/channels/1060193121130000425/1073202153163857920/1308337642105999382

**Comment by PavelLaptev** [comment]
The title counter is meant to help users keep the summary within a limit—for example, 50 characters in GitHub.
But what’s the purpose of showing a character counter for the body?

**Comment by PavelLaptev** [comment]
Closing this issue. It should be included in the next release.
