### ISSUE TITLE
Caret moves to the end of PR description on first input

### ISSUE THREAD

**Issue by AndersRobstad** [gitbutlerapp/gitbutler#5645]
### Version

0.13.16

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When opening a PR with a template from Gitbutler the caret jumps to the end of the template on first keydown

### How to reproduce

So when i place the caret at the top of the template to start writing I have to first click on any key, then move the caret back to the top, and then I'm able to start writing the PR description. In the video below I place the caret at the end of `## Description` and hit `Enter` (*any key causes the same behavior*), then the caret moves to the end of the template. 

![Skjermopptak 2024-11-22 kl  08 55 09](https://github.com/user-attachments/assets/027b8f8a-d7c1-4663-a800-2f977c3cae5e)

### Expected behavior

When having placed the caret inside the PR description I expect it to be placed there when I start writing

**Comment by Byron** [comment]
Thanks a lot for reporting and for the perfect description (and illustration) of the issue.

I could easily reproduce it as well and think that @estib-vega would fix this in a jiffy.
