### ISSUE TITLE
Sign commits reverts to off after an update (happened on 2 updates)

### ISSUE THREAD

**Issue by GordonBeeming** [gitbutlerapp/gitbutler#5658]
### Version

Version 0.13.17 (20241122.113600)

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

After an update, the `Sign commits` flag reverts to false for my repo, this has happened for the last 2 updates (that I've noticed), closing GitButler and opening again does not revert the flag

![GB-Screenshot 2024-11-25 at 11 57 12@2x](https://github.com/user-attachments/assets/27ac9ce4-3bf4-478a-8ea3-ba837f90bcdd)

### How to reproduce

1. Set Sign commits on
2. Wait for an update
3. Update
4. Observe the setting has switched back to false

### Expected behavior

Sign commits should stay on after an update

**Comment by Byron** [comment]
Thanks a lot for reporting.
I will keep an eye out myself now, and randomly CC @estib-vega in case he has an idea how something like it could happen.

**Comment by GordonBeeming** [comment]
@Byron @estib-vega It's been a couple of updates and I've not experienced this again for any repos
I'm going to close the issue and it can always be re-opened if someone experiences it again in the future.
