### ISSUE TITLE
New Window Blank (Multi Window)

### ISSUE THREAD

**Issue by Keloran** [gitbutlerapp/gitbutler#5677]
### Version

0.13.17

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

If I open a project in a new window (undocumented) it throws a blank window, and a ton of errors in the console
![screenshot-2024-11-25-20-11-04](https://github.com/user-attachments/assets/89a7e7d2-48e7-4c1b-92e8-fbf95091b444)

### How to reproduce

Have a project open
open the project drop down
hold alt, select a different project

### Expected behavior

Opens a new window with the new project details inside

### Relevant log output

```shell
[Error] Unhandled Promise Rejection: Command plugin:log|log not allowed by ACL
	(anonymous function) (app.Bx55z6I1.js:3:353)
[Error] Unhandled Promise Rejection: Command plugin:store|load not allowed by ACL
[Error] Unhandled Promise Rejection: Command plugin:log|log not allowed by ACL
	(anonymous function) (app.Bx55z6I1.js:3:353)
[Error] Unhandled Promise Rejection: Command plugin:log|log not allowed by ACL
	(anonymous function) (app.Bx55z6I1.js:3:353)
> Selected Element
[Error] Unhandled Promise Rejection: Command plugin:log|log not allowed by ACL
	(anonymous function) (app.Bx55z6I1.js:3:353)
< <body class="text-base" spellcheck="false">…</body>
[Error] Unhandled Promise Rejection: Command plugin:log|log not allowed by ACL
	(anonymous function) (app.Bx55z6I1.js:3:353)
```

**Comment by Byron** [comment]
Thanks so much for reporting!

Indeed, it's a hidden feature but now even on MacOS, it goes into a spin-loop in the frontend. Here is how it looks like in the profiler.

<img width="1437" alt="Screenshot 2024-11-26 at 07 12 01" src="https://github.com/user-attachments/assets/32776933-ff73-4357-afcb-cfdc3f2acd95">

It's one of the hidden (and probably untested) features there were meant to assure the application won't step onto its own feet while multiple instances on various projects are open.

CC @ndom91 maybe it's an easy fix?

**Comment by ndom91** [comment]
I'll take a closer look, there doesn't seem to be any built-in Tauri logging permissions to explicitly allow it on multiple windows / instances, but I could repro this in dev and received a bit more info in the logs:

![image](https://github.com/user-attachments/assets/4d341400-4828-4de1-97e0-956398ab6267)

**Comment by ndom91** [comment]
Found a fix, however, I'm not sure of the security implications. Will do a bit more research

**Comment by Byron** [comment]
I see! It looks like Tauri v2 has a more fine-grained permission system where there is a main window, and new windows that aren't a main window then may have trouble.

It's strange though that it ended up in a hot loop for me, but it's great you got passed that 🙌.
