### ISSUE TITLE
Gitbutler no longer asks for passphrase

### ISSUE THREAD

**Issue by vreima** [gitbutlerapp/gitbutler#5681]
Hello,

Gitbutler seems to no longer ask for a passphrase, just fails with an error. This has been an issue for 2 or 3 weeks now.

![image](https://github.com/user-attachments/assets/e72f90b1-baf0-4ba1-80aa-4a72e87b7fc7)

**Comment by Byron** [comment]
Thanks a lot for posting!

For all I know, this subsystem wasn't changed (which of course, might be wrong), but if it's not, maybe this behaviour changes if GitButler is launched from a terminal which has already been authenticated. This would mean that in the terminal, like `cmd.exe`, you would run a `git push` or `git fetch`, so it pops up a password query once. When GItButler is launched from there using the full path, it *could* inherit the environment and maybe won't have to ask.

Of course, this is at most a workaround, but it would be useful to see if this works.

Something else to try would be to download [a release from a couple of weeks ago](https://github.com/gitbutlerapp/gitbutler/releases), but I just noticed that binaries aren't attached, unfortunately. But if GitButler could be downgraded, it would be possible to find the lower bound of the version that introduced the issue.

**Comment by estib-vega** [comment]
Hello @vreima, thanks a lot for reporting this.
I believe a fix for this should be available in version 0.14.0.
If you get the change, please let me know if that's not the case.

**Comment by vreima** [comment]
Hello @estib-vega, I just updated and I can confirm that 0.14.0 works and correctly asks for the passphrase. Thank you!

**Comment by estib-vega** [comment]
@vreima Awesome!
Thanks for the confirmation and please let us know if anything else misbehaves :)
