### ISSUE TITLE
Hang during GitHub Sign In

### ISSUE THREAD

**Issue by ZbigniewRA** [gitbutlerapp/gitbutler#5728]
Version: 0.14.1
Windows, msi

I've installed GitButler, opened it for the first time, and attempted to log in using GitHub.
Logged in using browser window (got a success message), but then was distracted and did not go back to the GitButler client.
I attempted to go back to GitButler the next day, and it was hanging (not responding to anything, "whitened" window indicating an unresponsive application). I had to forcefully close it.

**Comment by Byron** [comment]
Thanks a lot for reporting!

Was it logged in after killing the application and reopening it? Or is it generally hanging when trying to login using GitHub?
Thanks again.

**Comment by ZbigniewRA** [comment]
I'm pretty sure I had to log in again using GitHub. But it works now and I had no further problems with logging in.

**Comment by Byron** [comment]
I see, thank you.

Maybe it's related to the UI waiting forever until something happens, even though the callback from the browser after login isn't 100% reliable. Maybe it's possible to leave the UI usable enough so the user can retry without killing the app. CC @ndom91 .

**Comment by ndom91** [comment]
@ZbigniewRA unfortunatey without any more details its hard for me to determine what might have caused the application to degrade like that. I took a quick look at the relevant code section and there isn't any long polling or looping ithing that might cause trouble.

You can find the location of the logs depending on your platform here: https://docs.gitbutler.com/development/debugging#logs

**Comment by ZbigniewRA** [comment]
I tired to reproduce the problem (using new version 0.14.2), but everything works ok.
I don't want to share logs from my employer's machine.
I will close this issue.
