### ISSUE TITLE
Re-entering the app while having left it in edit-mode shows error

### ISSUE THREAD

**Issue by Byron** [gitbutlerapp/gitbutler#5768]
### Version

0.14.2

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

See subject

### How to reproduce

* Enter edit mode, for instance by resolving conflicts or editing an existing commit
* close the app
* reopen the app - observe the error popup
* cancelling the edit mode now triggers a "Something went wrong" error
* reloading the app makes it go back to normal

This should be easily reproducible, here is a video.

https://github.com/user-attachments/assets/566dcd04-814b-4ca8-8d01-342b11a8fa11

### Relevant log output

```shell
This is equivalent to the error popup, everything else seems to be internal to the UI (there are no more backend errors).


2024-12-07T15:07:11.119383Z ERROR list_virtual_branches: crates/gitbutler-tauri/src/virtual_branches.rs:54: error=Error(<verification-failed>

Caused by:
    project is on refs/heads/gitbutler/edit. Please checkout gitbutler/workspace to continue) project_id=a0557a3c-6177-467c-8922-31ae59c30616
```
```

**Comment by Byron** [comment]
I didn't investigate, but think @Caleb-T-Owens may find it interesting.

**Comment by Caleb-T-Owens** [comment]
Thanks, this seems like a little reactivity bug. I'll take a look on Monday morning
