### ISSUE TITLE
async buttons don't prevent multi-action (e.g. edit mode cancel)

### ISSUE THREAD

**Issue by Byron** [gitbutlerapp/gitbutler#5770]
### Version

0.14.2

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

When in edit mode, it's possible to click the cancel button multiple times, triggering the same action twice, with the second one showing an error.

https://github.com/user-attachments/assets/567345dd-9b97-4040-96e5-e30bffb52486

I think this is a general problem so I phrased it as such, while hopingthat maybe this can be solved in general by having a reusable async-button that is properly wired with the action is triggered while disallowing multi-triggering while the action is in progress.

### How to reproduce

* Click the `Resolve Conflicts` button
* Click the `Cancel` button in the edit modal in short succession

### Expected behavior

Buttons that trigger actions with the backend should in general be 'synced' to the action they trigger.

**Comment by Byron** [comment]
CC @PavelLaptev for the general case, and @Caleb-T-Owens for the specific incarnation.

**Comment by PavelLaptev** [comment]
From the UX POV the button should remain disabled until the task is completed

**Comment by Caleb-T-Owens** [comment]
I'll take this on, Monday morning.

**Comment by Byron** [comment]
Thanks! I also thought there is some sort of 'Action' button which has such logic for asynchronous background tasks built in.
