### ISSUE TITLE
Extra automatic backspace when deleting characters in the PR description textbox

### ISSUE THREAD

**Issue by sderrow** [gitbutlerapp/gitbutler#5805]
### Version

0.14.3

### Operating System

macOS

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

I think there's a small bug in the text field for writing the description of the PR in the "Create a pull request" modal where the preceding space before a word is also deleted after you finish deleting each character in the word separately.

### How to reproduce

- Type something in the description text box like: "This PR does"
- Hit backspace 4 times to delete just the word "does"
- Notice it actually deletes 5 characters and goes right up against the word "PR"

This means you have to hit the spacebar again after deleting, which isn't how any other textbox I've encountered works, and led to multiple words that were missing spaces between them

### Expected behavior

Should only delete the actual characters you clicked "backspace" to delete

**Comment by Byron** [comment]
Thanks a lot for reporting!

It was easy to reproduce, and I found a few more surprises while mashing keys.

https://github.com/user-attachments/assets/a40664ae-b613-4329-a248-3ac12df8c722

CC @estib-vega who wouldn't have trouble finishing this off :).

**Comment by estib-vega** [comment]
Oh, trimming issue it seems.
Let me fix that!

@sderrow Thanks for reporting this!

**Comment by Byron** [comment]
Thanks for pointing this out, I could also reproduce the backspace issue when creating a new commit, both in the subject line as well as in the body text. Since @gwilymatgearset reproduced it in the PR description box, I think it's fair to reopen the issue. CC @estib-vega .
